export const module = {
  id: 'behavioral-finance',
  semesterId: 'semester-4',
  title: 'Behavioral Finance',
  shortTitle: 'Behavioral',
  description:
    'Prüfungsorientierte Lerninhalte zu Heuristiken, kognitiven Verzerrungen und Entscheidungen unter Unsicherheit.',
  status: `in-progress`,
  examDate: null,
  accent: `var(--color-module-purple)`,
  topics: [
    {
      id: 'gesamtzusammenfassung',
      title: 'Gesamtzusammenfassung · Alle Kapitel',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · Kapitel 1–10 · Gesamtzusammenfassung',
      estimatedMinutes: 765,
    },
    {
      id: `einfuehrung`,
      title: `Kapitel 1 · Einführung in die Behavioral Finance`,
      status: `available`,
      hasContent: true,
      source: `Behavioral Finance · BF1 – Einführung · Folien 1–32`,
      estimatedMinutes: 50,
    },
    {
      id: 'modell-der-zwei-systeme',
      title: 'Kapitel 2 · Das Modell der zwei Systeme',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF2 – Modell 2 Systeme · Folien 33–48',
      estimatedMinutes: 45,
    },
    {
      id: 'heuristiken-und-kognitive-verzerrungen',
      title: 'Kapitel 3 · Heuristiken und kognitive Verzerrungen',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF3 – Heuristiken & Kognitive Verzerrung · Folien 49–130',
      estimatedMinutes: 95,
    },
    {
      id: 'entscheidungen-unter-unsicherheit',
      title: 'Kapitel 4 · Entscheidungen unter Unsicherheit',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF4 – Entscheidungen unter Unsicherheit · Folien 131–164',
      estimatedMinutes: 65,
    },
    {
      id: 'zeit-in-der-oekonomie',
      title: 'Kapitel 5 · Zeit in der Ökonomie',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF5 – Zeit in der Ökonomie · Folien 165–190',
      estimatedMinutes: 55,
    },
    {
      id: 'prospect-theory-und-ihre-konsequenzen',
      title: 'Kapitel 6 · Prospect Theory und ihre Konsequenzen',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF6 - Prospect Theory und ihre Konsequenzen · Folien 191-235',
      estimatedMinutes: 100,
    },
    {
      id: 'altersvorsorge-und-private-finanzplanung',
      title: 'Kapitel 7 · Altersvorsorge und private Finanzplanung',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF7 - Altersvorsorge und private Finanzplanung · Folien 236-272',
      estimatedMinutes: 90,
    },
    {
      id: 'spekulationsblasen-an-finanzmaerkten',
      title: 'Kapitel 8 · Spekulationsblasen an Finanzmärkten',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF8 - Spekulationsblasen an Finanzmärkten · Folien 273-293',
      estimatedMinutes: 75,
    },
    {
      id: 'kapitalanlage-und-kapitalmarktanomalien',
      title: 'Kapitel 9 · Kapitalanlage und Kapitalmarktanomalien',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF9 – Kapitalanlage und Kapitalmarktanomalien · Folien 294–340',
      estimatedMinutes: 100,
    },
    {
      id: 'behavioral-corporate-finance',
      title: 'Kapitel 10 · Behavioral Corporate Finance',
      status: 'available',
      hasContent: true,
      source: 'Behavioral Finance · BF10 – Behavioral Corporate Finance · Folien 341–361',
      estimatedMinutes: 90,
    },
  ],
};
