export const questions = [
  // ===================================================================
  // Kapitel 1 · Einführung in die Behavioral Finance
  // ===================================================================
  {
    id: 'einfuehrung-q01',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie lässt sich Behavioral Finance im Verhältnis von Ökonomie und Psychologie am genauesten einordnen?',
    options: [
      'Sie ist eine rein normative Disziplin, die ausschließlich vorgibt, wie man sich verhalten soll.',
      'Sie ist eine verhaltenswissenschaftlich fundierte Finanzmarkttheorie in der Schnittmenge von Ökonomie (normativ) und Psychologie (deskriptiv).',
      'Sie ist ein Teilgebiet der Psychologie ohne ökonomischen Bezug.',
      'Sie ersetzt die Ökonomie vollständig durch psychologische Beschreibungen.',
    ],
    correctAnswer: 1,
    explanation: 'Behavioral Finance liegt in der Schnittmenge: Die Ökonomie ist normativ (wie man sich verhalten soll), die Psychologie deskriptiv (wie der Mensch tatsächlich handelt). Die ökonomisch geprägte Schnittmenge heißt Verhaltensökonomie.',
  },
  {
    id: 'einfuehrung-q02',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welches Menschenbild beschreibt die Behavioral Finance laut Daxhammer/Facsar (2018)?',
    options: [
      'Den vollständig rationalen Homo Oeconomicus ohne jede Verzerrung.',
      'Den Homo Oeconomicus Humanus, der nur zu begrenzt rationalem Verhalten in der Lage und durch kognitive und emotionale Aspekte beeinflusst ist.',
      'Den ausschließlich von Emotionen gesteuerten Menschen ohne kognitive Fähigkeiten.',
      'Einen Menschen mit unbegrenzter Willenskraft und festen Präferenzen.',
    ],
    correctAnswer: 1,
    explanation: 'Daxhammer/Facsar: Marktteilnehmer sind nur zu begrenzt rationalem Verhalten fähig; es kristallisiert sich ein Homo Oeconomicus Humanus heraus, der häufig durch kognitive und emotionale Aspekte beeinflusst wird.',
  },
  {
    id: 'einfuehrung-q03',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie unterscheiden sich Maximalprinzip und Minimalprinzip des ökonomischen Prinzips?',
    options: [
      'Beim Maximalprinzip ist der Input fix und der Output wird maximiert; beim Minimalprinzip ist der Output fix und der Input wird minimiert.',
      'Beim Maximalprinzip ist der Output fix; beim Minimalprinzip ist der Input fix.',
      'Beide Prinzipien fixieren sowohl Input als auch Output.',
      'Beide Prinzipien lassen Input und Output frei variieren.',
    ],
    correctAnswer: 0,
    explanation: 'Maximalprinzip: Input fix, Output so groß wie möglich. Minimalprinzip: Output fix, Input so klein wie möglich. Die Verwechslung ist ein klassischer Klausurfehler.',
  },
  {
    id: 'einfuehrung-q04',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Eigenschaften gehören zum idealisierten Menschenbild des Homo Oeconomicus?',
    options: [
      'rational, eigennützig und risikoavers',
      'vollständig informiert mit feststehenden Präferenzen',
      'unbegrenzte Willenskraft, frei von Emotionen und Selbstkontrollproblemen',
      'systematisch begrenzt rational mit Rückgriff auf Heuristiken',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Der Homo Oeconomicus ist rational, eigennützig, risikoavers, vollständig informiert, mit festen Präferenzen, reagiert auf die Umwelt und besitzt unbegrenzte Willenskraft. Begrenzte Rationalität mit Heuristiken ist gerade die verhaltensökonomische Gegenannahme.',
  },
  {
    id: 'einfuehrung-q05',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche Aussage trennt formelle und substantielle Rationalität korrekt?',
    options: [
      'Formelle Rationalität bedeutet Nutzenmaximierung; substantielle Rationalität bedeutet nur systematische Auswahl.',
      'Formelle Rationalität liegt vor, wenn systematisch aus bekannten Alternativen gewählt wird; substantielle Rationalität orientiert sich an der Nutzenmaximierung.',
      'Beide Begriffe sind identisch und austauschbar.',
      'Substantielle Rationalität ist der weitere Begriff, formelle der engere.',
    ],
    correctAnswer: 1,
    explanation: 'Formelle Rationalität: systematische Auswahl aus bekannten Alternativen (fast jedes Handeln ist dann rational). Substantielle Rationalität: Orientierung an der Nutzenmaximierung — der engere, anspruchsvollere Begriff.',
  },
  {
    id: 'einfuehrung-q06',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche drei einschränkenden Annahmen setzt die Verhaltensökonomik an die Stelle der Kernannahmen des Homo Oeconomicus?',
    options: [
      'begrenzte Rationalität (statt vollständiger Rationalität)',
      'begrenzte Willenskraft (statt unbegrenzter Willenskraft)',
      'begrenzter Eigennutz (statt reinen Eigennutzes)',
      'unbegrenzte Information (statt begrenzter Information)',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die drei einschränkenden Annahmen sind begrenzte Rationalität (Heuristiken), begrenzte Willenskraft (Vertagung) und begrenzter Eigennutz (Fairness).',
  },
  {
    id: 'einfuehrung-q07',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Zuordnungen der Modellprinzipien traditionell → behavioral sind korrekt?',
    options: [
      'Kalkül: Erwartungsnutzentheorie → Prospect Theory',
      'Zeitpräferenz: exponentielles → hyperbolisches Diskontieren',
      'Nutzenkonzept: reiner Eigennutz → Fairness und Wohlergehen anderer',
      'Kalkül: Prospect Theory → Erwartungsnutzentheorie',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die drei Achsen sind paarweise zu merken: Erwartungsnutzentheorie → Prospect Theory, exponentielles → hyperbolisches Diskontieren, reiner Eigennutz → Fairness. Die letzte Option dreht die Kalkül-Richtung falsch um.',
  },
  {
    id: 'einfuehrung-q08',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wodurch unterscheidet sich die verhaltensökonomische Entscheidungskette von der neoklassischen?',
    options: [
      'In der Neoklassik schiebt sich die subjektive Risikowahrnehmung zwischen Risiko und Entscheidung.',
      'Verhaltensökonomisch entscheidet das objektive Risiko direkt, ohne Zwischenschritt.',
      'Verhaltensökonomisch schiebt sich die subjektive Risikowahrnehmung — geprägt durch Framing und Risikoeinstellung — zwischen objektives Risiko und Entscheidung.',
      'Beide Ketten sind identisch, nur die Begriffe sind verschieden.',
    ],
    correctAnswer: 2,
    explanation: 'In der Neoklassik führt objektives Risiko direkt zur Entscheidung. Verhaltensökonomisch schiebt sich die subjektive Risikowahrnehmung dazwischen, geprägt durch Risikodarstellung (Framing) und individuelle Risikoeinstellung.',
  },
  {
    id: 'einfuehrung-q09',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche Rolle spielen Emotionen aus verhaltensökonomischer Sicht?',
    options: [
      'Sie sind reiner Störfaktor und sollten vollständig ausgeblendet werden.',
      'Sie wirken nur als Verzerrung und nie als Entscheidungshilfe.',
      'Sie können als heuristische Entscheidungsregel dienen und ermöglichen dort handlungsfähige Entscheidungen, wo rationale Optimierung scheitert.',
      'Sie sind langsamer als kognitive Prozesse und daher vernachlässigbar.',
    ],
    correctAnswer: 2,
    explanation: 'Wo rationale Optimierung an begrenzter Problemlösungsfähigkeit scheitert, dienen Emotionen als heuristische Entscheidungsregel und ermöglichen überhaupt erst handlungsfähige Entscheidungen.',
  },
  {
    id: 'einfuehrung-q10',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Typen ökonomischer Experimente werden im Kapitel unterschieden?',
    options: [
      'Laborexperimente',
      'Feldexperimente',
      'natürliche Experimente',
      'Gedankenexperimente ohne empirischen Bezug',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Ökonomische Experimente werden in Labor-, Feld- und natürliche Experimente unterschieden; ihre Zwecke sind u. a. Theorien überprüfen, Schwächen finden, Institutionen vergleichen und Politikkonzepte testen.',
  },

  // ===================================================================
  // Kapitel 2 · Das Modell der zwei Systeme
  // ===================================================================
  {
    id: 'modell-der-zwei-systeme-q01',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Wie charakterisiert Kahneman System 1?',
    options: [
      'bewusst, konzentriert und anstrengend',
      'automatisch, schnell und unbewusst, arbeitet u. a. mit Heuristiken',
      'ausschließlich für mathematische Beweisführungen zuständig',
      'der einzige Modus des Homo Oeconomicus',
    ],
    correctAnswer: 1,
    explanation: 'System 1 funktioniert automatisch, schnell und unbewusst und arbeitet mit Heuristiken. System 2 ist das bewusste, konzentrierte, aber faule System.',
  },
  {
    id: 'modell-der-zwei-systeme-q02',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Mit welchem System arbeitet der Homo Oeconomicus ausschließlich?',
    options: [
      'System 1',
      'System 2',
      'sowohl System 1 als auch System 2 gleichberechtigt',
      'mit keinem der beiden Systeme',
    ],
    correctAnswer: 1,
    explanation: 'Der Homo Oeconomicus wäre ein reiner System-2-Akteur. Reale Menschen entscheiden überwiegend mit System 1 und weichen daher systematisch vom rationalen Idealbild ab.',
  },
  {
    id: 'modell-der-zwei-systeme-q03',
    topicId: 'modell-der-zwei-systeme',
    type: 'multiple',
    question: 'Welche Tätigkeiten sind typische System-2-Aktivitäten?',
    options: [
      'in einer schmalen Parklücke einparken',
      'eine Steuererklärung anfertigen',
      'erkennen, dass ein Gegenstand weiter entfernt ist',
      'die Gültigkeit einer Beweisführung prüfen',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Einparken, Steuererklärung und Prüfen einer Beweisführung sind kontrollierte, anstrengende System-2-Aktivitäten. Das Erkennen der Entfernung läuft mühelos über System 1.',
  },
  {
    id: 'modell-der-zwei-systeme-q04',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Warum sind intuitive Denkfehler nach Kahneman schwer zu verhindern?',
    options: [
      'Weil System 2 permanent läuft und nicht abgeschaltet werden kann.',
      'Weil System 1 nicht abgeschaltet werden kann und automatisch reagiert, bevor System 2 prüfen kann.',
      'Weil das Gehirn niemals auf System 1 zurückgreift.',
      'Weil Heuristiken stets zu korrekten Ergebnissen führen.',
    ],
    correctAnswer: 1,
    explanation: 'System 1 lässt sich nicht abstellen und reagiert automatisch; es springt an, bevor System 2 prüfen kann. Daher sind intuitive Denkfehler schwer zu vermeiden.',
  },
  {
    id: 'modell-der-zwei-systeme-q05',
    topicId: 'modell-der-zwei-systeme',
    type: 'multiple',
    question: 'Welche Faktoren erzeugen kognitive Leichtigkeit (cognitive ease)?',
    options: [
      'wiederholte Erfahrung',
      'klare Darstellung',
      'gute Laune',
      'kaum lesbare Schrift (Disfluency)',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Ursachen kognitiver Leichtigkeit sind wiederholte Erfahrung, klare Darstellung, geprimte Vorstellung und gute Laune. Schlecht lesbare Schrift erzeugt das Gegenteil (Disfluency) und mobilisiert System 2.',
  },
  {
    id: 'modell-der-zwei-systeme-q06',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Im Cognitive Reflection Test (Schläger und Ball): Ein Schläger und ein Ball kosten zusammen 1,10 €, der Schläger kostet 1 € mehr als der Ball. Was kostet der Ball?',
    options: [
      '0,10 €',
      '0,05 €',
      '1,00 €',
      '0,11 €',
    ],
    correctAnswer: 1,
    explanation: 'System 1 antwortet sofort 0,10 €, richtig sind aber 0,05 € (Schläger 1,05 € + Ball 0,05 € = 1,10 €). Bei kaum lesbarer Schrift sank die Fehlerquote von 90 % auf 35 %, weil System 2 aktiviert wurde.',
  },
  {
    id: 'modell-der-zwei-systeme-q07',
    topicId: 'modell-der-zwei-systeme',
    type: 'single',
    question: 'Was demonstriert der Stroop-Konflikt?',
    options: [
      'dass System 1 bei vertrautem Kontext logische Fehler übersieht',
      'dass das automatische Lesen (System 1) mit der bewussten Aufgabe (System 2) kollidiert und das Unterdrücken Anstrengung kostet',
      'dass kognitive Leichtigkeit immer zu wahren Urteilen führt',
      'dass System 2 schneller reagiert als System 1',
    ],
    correctAnswer: 1,
    explanation: 'Im Stroop-Konflikt kollidiert das automatische Lesen (System 1) mit der bewussten Aufgabe, Schreibweise oder Position zu nennen (System 2). Das Unterdrücken der automatischen Reaktion kostet Anstrengung und verlangsamt.',
  },

  // ===================================================================
  // Kapitel 3 · Heuristiken und kognitive Verzerrungen
  // ===================================================================
  {
    id: 'heuristiken-q01',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Was ist eine Heuristik im Sinne des Kapitels?',
    options: [
      'eine normative, mathematisch strukturierte Handlungsanweisung mit reproduzierbarem Ergebnis',
      'eine Problemlösungsstrategie bei eingeschränktem Wissen und wenig Zeit, eine Daumenregel zur Entlastung von System 2',
      'ein Verfahren, das in gleichen Situationen stets zu gleichen Ergebnissen führt',
      'die normative Referenz der Ökonomen-Modelle',
    ],
    correctAnswer: 1,
    explanation: 'Eine Heuristik ist eine Daumen-/Faustregel zur schnellen Entscheidungsfindung bei eingeschränktem Wissen und wenig Zeit. Sie entlastet System 2, kann aber zu systematischen Verzerrungen (Biases) führen. Die normative, mathematisch strukturierte Referenz ist der Algorithmus.',
  },
  {
    id: 'heuristiken-q02',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'In welcher Stimmungslage werden laut Kapitel die meisten Fehler gemacht?',
    options: [
      'bei negativer Stimmung, weil dann analytisch (System 2) gearbeitet wird',
      'bei positiver Stimmung, weil dann heuristisch (System 1) und fehleranfällig gearbeitet wird',
      'unabhängig von der Stimmung gleich viele Fehler',
      'nur bei neutraler Stimmung',
    ],
    correctAnswer: 1,
    explanation: 'Positive Stimmung führt zu heuristischem, fehleranfälligem Verarbeiten; negative Stimmung zu analytischem, gründlichem Vorgehen. Bei positiver Stimmung werden die meisten Fehler gemacht.',
  },
  {
    id: 'heuristiken-q03',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Wie lässt sich die Verfügbarkeitsheuristik beschreiben?',
    options: [
      'Die Wahrscheinlichkeit eines Ereignisses wird über die Abrufbarkeit von Gedächtnisinhalten geschätzt: Leicht Vorstellbares gilt als wahrscheinlicher.',
      'Ereignisse werden überbewertet, wenn sie in ein bekanntes Schema passen.',
      'Schätzungen orientieren sich an einem zuvor genannten Ausgangswert.',
      'Fakten werden im Sinne der vorgefassten Meinung interpretiert.',
    ],
    correctAnswer: 0,
    explanation: 'Bei der Verfügbarkeitsheuristik hängt die Wahrscheinlichkeitsschätzung von der Abrufbarkeit von Gedächtnisinhalten ab. Verfügbarkeit ist jedoch nicht gleich Häufigkeit.',
  },
  {
    id: 'heuristiken-q04',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Das Linda-Problem (Bankangestellte vs. Bankangestellte und feministisch aktiv) illustriert welchen Fehler der Repräsentativitätsheuristik?',
    options: [
      'die Vernachlässigung der A-priori-Wahrscheinlichkeit (Base-rate-Fallacy)',
      'den Conjunction Bias: die Konjunktion zweier Merkmale kann nie wahrscheinlicher sein als ein Einzelmerkmal',
      'das Gesetz der kleinen Zahlen',
      'die falsche Prognosesicherheit',
    ],
    correctAnswer: 1,
    explanation: 'Beim Linda-Problem wählen viele die Konjunktion (Bankangestellte UND feministisch), weil sie zum Schema passt — doch die Konjunktion kann nie wahrscheinlicher sein als das Einzelmerkmal (Conjunction Bias).',
  },
  {
    id: 'heuristiken-q05',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Welcher Denkfehler liegt vor, wenn p(A|B) und p(B|A) gleichgesetzt werden (Brustkrebs-Beispiel)?',
    options: [
      'Die A-priori-Wahrscheinlichkeit wird übergewichtet.',
      'Bedingte Wahrscheinlichkeiten werden durch schematisches Denken verwechselt; korrekt liefert das Bayes-Theorem p(Bk|Hr) = 12,2 % statt der unterstellten 93 %.',
      'Der Stichprobenumfang wird überschätzt.',
      'Die Verfügbarkeitskaskade verzerrt die Schätzung.',
    ],
    correctAnswer: 1,
    explanation: 'Menschen setzen p(A|B) und p(B|A) gleich. Im Brustkrebs-Beispiel ist 93 % das p(Hochrisiko|Brustkrebs); das gesuchte p(Brustkrebs|Hochrisiko) beträgt nach Bayes nur 12,2 %.',
  },
  {
    id: 'heuristiken-q06',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'multiple',
    question: 'Welche Varianten gehören zum Überoptimismus (Overconfidence)?',
    options: [
      'Self-serving-Bias (Erfolg = ich, Misserfolg = Zufall)',
      'Kontrollillusion',
      'Selbstüberschätzung',
      'Verankerung an einem sachfremden Ausgangswert',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Zum Überoptimismus zählen Self-serving-Bias, Kontrollillusion und Selbstüberschätzung. Die Verankerung an einem Ausgangswert ist der Anchoring-Effekt, keine Overconfidence-Variante.',
  },
  {
    id: 'heuristiken-q07',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Welchen empirischen Befund liefern Barber/Odean (2000) zum Zusammenhang von Handelshäufigkeit und Rendite?',
    options: [
      'Häufiges Handeln steigert die Nettorendite deutlich.',
      'Mit steigendem Portfolioumsatz sinkt die Nettorendite; häufiges Handeln (Overconfidence) verringert die Performance.',
      'Die Handelshäufigkeit hat keinen Einfluss auf die Rendite.',
      'Frauen handeln deutlich häufiger als Männer.',
    ],
    correctAnswer: 1,
    explanation: 'Sortiert man Anleger nach Portfolioumsatz, sinkt die Nettorendite mit steigendem Umsatz monoton. Häufiges Handeln aus Overconfidence verringert die Nettorendite; alleinstehende Männer handeln am häufigsten.',
  },
  {
    id: 'heuristiken-q08',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Im Asian-Disease-Problem: Wie wählt die Mehrheit im Gewinn-Frame (Rettung) und im Verlust-Frame (Sterben)?',
    options: [
      'im Gewinn-Frame riskant, im Verlust-Frame sicher',
      'im Gewinn-Frame die sichere Variante (risikoavers), im Verlust-Frame die riskante Variante (risikofreudig)',
      'in beiden Frames die sichere Variante',
      'in beiden Frames die riskante Variante',
    ],
    correctAnswer: 1,
    explanation: 'Bei rechnerisch identischen Alternativen wählt die Mehrheit im Gewinn-Frame die sichere Variante A (risikoavers) und im Verlust-Frame die riskante Variante D (risikofreudig) — der Framing-Effekt.',
  },
  {
    id: 'heuristiken-q09',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'multiple',
    question: 'Welche Aussagen zum Verankerungseffekt (Anchoring) sind korrekt?',
    options: [
      'Menschen orientieren sich bei Schätzungen an einem zuvor genannten Ausgangswert, auch wenn dieser sachfremd ist.',
      'Der Ankerungsindex misst die Stärke des Effekts; 100 % bedeutet sklavisches Folgen, 0 % keine Wirkung.',
      'Im Experiment von Ariely et al. (2003) stieg die Zahlungsbereitschaft monoton mit dem Quintil der völlig sachfremden Sozialversicherungsnummer.',
      'Nur Laien, nicht aber Experten lassen sich von Ankern beeinflussen.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Anchoring: Orientierung an einem (auch sachfremden) Ausgangswert, gemessen über den Ankerungsindex. Bei Ariely et al. stieg die WTP monoton mit der SS#-Ziffer. Sowohl Laien als auch Experten verschieben Schätzungen Richtung Anker.',
  },
  {
    id: 'heuristiken-q10',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Welche Folge hat Mental Accounting für Portfolios?',
    options: [
      'Es verbessert die Risikostreuung durch getrennte Konten.',
      'Risikodiversifikationseffekte werden häufig nicht genügend beachtet, weil Positionen getrennt statt gemeinsam betrachtet werden.',
      'Es führt stets zur korrekten Gesamtbewertung aller Tatbestände.',
      'Es hat keine Auswirkungen auf Anlageentscheidungen.',
    ],
    correctAnswer: 1,
    explanation: 'Durch Mental Accounting werden Konsequenzen verschiedenen mentalen Konten zugeordnet statt gemeinsam betrachtet — dadurch werden Risikodiversifikationseffekte in Portfolios häufig nicht genügend beachtet.',
  },
  {
    id: 'heuristiken-q11',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'single',
    question: 'Was beschreibt der Decoy-Effekt (asymmetrische Dominanz) am Economist-Abo-Beispiel?',
    options: [
      'Ein bewusst minderwertiger Köder (Print für 125 EUR) verschiebt die Wahl zugunsten des Print+Online-Pakets von 32 % auf 84 %.',
      'Der Köder wird am häufigsten gewählt.',
      'Die Wahl ändert sich nicht durch das Hinzufügen einer dritten Option.',
      'Der Onlinetarif wird durch den Köder attraktiver.',
    ],
    correctAnswer: 0,
    explanation: 'Obwohl niemand das reine Print-Angebot wählt (0 %), steigt der Anteil von Print+Online durch den Köder von 32 % auf 84 % — asymmetrische Dominanz.',
  },
  {
    id: 'heuristiken-q12',
    topicId: 'heuristiken-und-kognitive-verzerrungen',
    type: 'multiple',
    question: 'Welche Beschreibungen weiterer Heuristiken/Effekte treffen zu?',
    options: [
      'Affektheuristik: Gefühle ersetzen die Analyse ("Was fühle ich?" statt "Was denke ich?").',
      'WYSIATI: System 1 konstruiert aus wenigen Infos eine kohärente Geschichte und ignoriert Fehlendes.',
      'Halo-Effekt: Eine herausragende Eigenschaft strahlt auf das Gesamturteil aus.',
      'Hindsight Bias: Vor Bekanntwerden des Ergebnisses wird die Schätzung nach unten korrigiert.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Affektheuristik, WYSIATI und Halo-Effekt sind korrekt beschrieben. Der Rückschaufehler (Hindsight Bias) verschiebt die ERINNERTE Schätzung NACH Bekanntwerden des Ergebnisses Richtung der bekannten Lösung ("I knew it all along").',
  },

  // ===================================================================
  // Kapitel 4 · Entscheidungen unter Unsicherheit
  // ===================================================================
  {
    id: 'entscheidungen-q01',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Worin liegt der einzige Unterschied zwischen Ungewissheit und Risiko im engeren Sinne?',
    options: [
      'in der Anzahl der möglichen Umweltzustände',
      'im Wissen über die Eintrittswahrscheinlichkeiten: bei Risiko i.e.S. bekannt (objektiv oder subjektiv), bei Ungewissheit unbekannt',
      'darin, dass bei Ungewissheit die Konsequenzen vollständig bekannt sind',
      'darin, dass Risiko i.e.S. keine stochastischen Modelle erlaubt',
    ],
    correctAnswer: 1,
    explanation: 'Bei Ungewissheit kennt der Entscheider nur die Zahl der Zustände, keine Wahrscheinlichkeiten. Bei Risiko i.e.S. liegen objektive oder subjektive Wahrscheinlichkeiten vor, sodass stochastische Modelle anwendbar sind.',
  },
  {
    id: 'entscheidungen-q02',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'multiple',
    question: 'Welche Zuordnungen von Informationsstand und Entscheidungssituation sind korrekt?',
    options: [
      'Vollkommene Information → sichere Erwartungen, Konsequenzen vollständig bekannt',
      'Unvollkommene Information mit bekannten Wahrscheinlichkeiten → Entscheidung unter Risiko',
      'Unvollkommene Information ohne Wahrscheinlichkeiten → unsichere Erwartungen',
      'Vollkommene Information → Entscheidung unter Risiko',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Vollkommene Information bedeutet Sicherheit. Unvollkommene Information trennt Risiko (Wahrscheinlichkeiten bekannt) von unsicheren Erwartungen (Wahrscheinlichkeiten unbekannt). Vollkommene Information führt nicht zu Risiko.',
  },
  {
    id: 'entscheidungen-q03',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Was empfiehlt die Maximin-Regel (Wald-Regel)?',
    options: [
      'die Alternative mit dem höchsten bestmöglichen Ergebnis (optimistisch)',
      'die Alternative mit dem höchsten schlechtestmöglichen Ergebnis (pessimistisch)',
      'die Alternative mit dem höchsten Zeilendurchschnitt',
      'die Alternative mit dem geringsten maximalen Bedauern',
    ],
    correctAnswer: 1,
    explanation: 'Die Maximin-Regel (auch Minimax-/Wald-Regel) wählt das höchste Zeilenminimum — die Alternative mit dem besten schlechtestmöglichen Ergebnis, also extrem pessimistisch.',
  },
  {
    id: 'entscheidungen-q04',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'multiple',
    question: 'Welche Zuordnungen von Entscheidungsregel bei Ungewissheit und Grundeinstellung treffen zu?',
    options: [
      'Maximax-Regel: extrem optimistisch (höchstes bestmögliches Ergebnis)',
      'Hurwicz-Kriterium: gewichtete Mischung aus bestem und schlechtestem Ergebnis (Optimismusparameter)',
      'Laplace-Regel: alle Zustände gleich gewichtet (Prinzip des unzureichenden Grundes)',
      'Savage-Niehans-Regel: höchster Zeilendurchschnitt der Originalwerte',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Maximax ist optimistisch, Hurwicz ein gewichteter Kompromiss, Laplace gewichtet alle Zustände gleich. Die Savage-Niehans-Regel arbeitet mit einer Bedauernsmatrix (Wert minus Spaltenmaximum) und minimiert den maximalen Schaden (Minimax-Regret).',
  },
  {
    id: 'entscheidungen-q05',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Wie funktioniert die Bayes-Regel (μ-Prinzip) bei Entscheidung unter Risiko?',
    options: [
      'Sie wählt die Alternative mit der geringsten Standardabweichung.',
      'Sie gewichtet jedes Zustandsergebnis mit seiner Wahrscheinlichkeit und wählt die Alternative mit dem höchsten Erwartungswert.',
      'Sie wählt die Alternative mit dem höchsten bestmöglichen Ergebnis.',
      'Sie berücksichtigt die individuelle Risikoeinstellung über eine Nutzenfunktion.',
    ],
    correctAnswer: 1,
    explanation: 'Die Bayes-Regel gewichtet jedes Ergebnis mit seiner Wahrscheinlichkeit und wählt den höchsten Erwartungswert. Sie ignoriert die Streuung und passt damit nur für risikoneutrale Entscheider.',
  },
  {
    id: 'entscheidungen-q06',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Warum eignet sich die Bayes-Regel nur für risikoneutrale Entscheider?',
    options: [
      'weil sie nur das schlechteste Ergebnis betrachtet',
      'weil sie ausschließlich den Erwartungswert berücksichtigt und die Streuung (das Risiko) ignoriert',
      'weil sie keine Wahrscheinlichkeiten verwendet',
      'weil sie eine konkave Nutzenfunktion unterstellt',
    ],
    correctAnswer: 1,
    explanation: 'Die Bayes-Regel betrachtet nur den Erwartungswert und ignoriert die Streuung. Risikoscheue Entscheider bewerten die Streuung negativ und benötigen daher die μσ-Regel.',
  },
  {
    id: 'entscheidungen-q07',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Wann ist eine Alternative im μ-σ-Diagramm nach Markowitz effizient?',
    options: [
      'wenn sie das höchste Risiko bei höchstem Erwartungswert hat',
      'wenn keine andere Alternative sie dominiert (kein höherer Erwartungswert bei gleichem Risiko, kein geringeres Risiko bei gleichem Erwartungswert, nicht beides zugleich)',
      'wenn sie genau auf der 45-Grad-Linie liegt',
      'wenn ihre Standardabweichung null ist',
    ],
    correctAnswer: 1,
    explanation: 'Eine Alternative ist effizient, wenn keine andere sie dominiert: kein Portfolio mit gleichem Erwartungswert und geringerem Risiko, gleichem Risiko und höherem Erwartungswert oder beidem zugleich. Effiziente Punkte liegen links oben.',
  },
  {
    id: 'entscheidungen-q08',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Was ist die Risikoprämie π im Bernoulli-Prinzip?',
    options: [
      'das fiktive sichere Ergebnis mit demselben Nutzen wie die riskante Handlung',
      'der vom Erwartungswert vorzunehmende Abschlag, der gerade Indifferenz herbeiführt: π = E(X) − s',
      'der Erwartungsnutzen der riskanten Alternative',
      'die Standardabweichung der Auszahlungen',
    ],
    correctAnswer: 1,
    explanation: 'Die Risikoprämie π ist der Abschlag vom Erwartungswert, der Indifferenz herbeiführt: π = E(X) − s. Das Sicherheitsäquivalent s ist das fiktive sichere Ergebnis mit gleichem Nutzen.',
  },
  {
    id: 'entscheidungen-q09',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'multiple',
    question: 'Welche Zuordnungen von Risikoeinstellung, Nutzenfunktion und Risikoprämie sind korrekt?',
    options: [
      'Risikoaversion: konkave Nutzenfunktion, π > 0',
      'Risikoneutralität: lineare Nutzenfunktion, π = 0',
      'Risikofreude: konvexe Nutzenfunktion, π < 0',
      'Risikoaversion: konvexe Nutzenfunktion, π < 0',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Konkav → risikoavers (π > 0), linear → risikoneutral (π = 0), konvex → risikofreudig (π < 0). Risikoaversion ist gerade konkav, nicht konvex.',
  },
  {
    id: 'entscheidungen-q10',
    topicId: 'entscheidungen-unter-unsicherheit',
    type: 'single',
    question: 'Eine Lotterie zahlt mit 50 % 100 € und mit 50 % 0 €, also E(X) = 50 €. Ein Entscheider ist bei einem Sicherheitsäquivalent von s = 40 € indifferent. Welche Risikoeinstellung liegt vor und wie hoch ist die Risikoprämie?',
    options: [
      'risikofreudig, π = −10 €',
      'risikoneutral, π = 0 €',
      'risikoscheu, π = 50 − 40 = 10 €',
      'risikoscheu, π = 90 €',
    ],
    correctAnswer: 2,
    explanation: 'π = E(X) − s = 50 − 40 = 10 € > 0, also risikoscheu. Bei π > 0 ist der Entscheider risikoavers, bei π = 0 risikoneutral, bei π < 0 risikofreudig.',
  },

  // ===================================================================
  // Kapitel 5 · Zeit in der Ökonomie
  // ===================================================================
  {
    id: 'zeit-q01',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was beschreibt die Zeitpräferenz des Geldes?',
    options: [
      'Künftiger Konsum wird höher bewertet als heutiger Konsum gleicher Höhe.',
      'Heutiger Konsum wird höher bewertet als künftiger Konsum gleicher Höhe; der positive Zinssatz ist der Preis für den Konsumverzicht.',
      'Heutiger und künftiger Konsum werden stets gleich bewertet.',
      'Der Zinssatz ist immer negativ.',
    ],
    correctAnswer: 1,
    explanation: 'Bei der Zeitpräferenz (Gegenwartspräferenz) wird heutiger Konsum höher bewertet als künftiger gleicher Höhe. Der positive Zinssatz ist der Preis für den Verzicht auf gegenwärtigen Konsum.',
  },
  {
    id: 'zeit-q02',
    topicId: 'zeit-in-der-oekonomie',
    type: 'multiple',
    question: 'Welche Gründe für die Existenz eines Zinssatzes nennt das Kapitel?',
    options: [
      'Unsicherheit und Kompensation für Risiko (Risikoprämie)',
      'Opportunitätskosten und Inflation',
      'Ungeduld und multiple Persönlichkeiten (heutiges vs. späteres Ich)',
      'die vollständige Risikofreiheit aller Anlagen',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Kapitel nennt sechs Gründe: Unsicherheit, Kompensation für Risiko, Opportunitätskosten, Inflation, Ungeduld und multiple Persönlichkeiten. Risikofreiheit gehört nicht dazu.',
  },
  {
    id: 'zeit-q03',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Wodurch ist das exponentielle Diskontieren (DU-Modell) gekennzeichnet?',
    options: [
      'durch einen vom Zeitpunkt abhängigen Diskontfaktor (1 + i·n)',
      'durch einen konstanten, exponentiellen Diskontfaktor (1/(1+i))^n',
      'durch einen mit der Zeit steigenden Diskontsatz',
      'durch den vollständigen Verzicht auf jede Abzinsung',
    ],
    correctAnswer: 1,
    explanation: 'Im DU-Modell ist der Diskontfaktor konstant und exponentiell: (1/(1+i))^n. Jede zusätzliche Verzögerungsperiode wirkt sich mit demselben Faktor 1/(1+i) aus.',
  },
  {
    id: 'zeit-q04',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was bedeutet Zeitkonsistenz und wie verhält sich exponentielles Diskontieren?',
    options: [
      'Eine Entscheidung soll sich ändern, wenn man beide Optionen um die gleiche Zeitspanne verschiebt; exponentielles Diskontieren ist zeitinkonsistent.',
      'Eine Entscheidung soll sich nicht ändern, wenn man beide Optionen um die gleiche Zeitspanne verschiebt; exponentielles Diskontieren ist zeitkonsistent.',
      'Zeitkonsistenz betrifft nur das hyperbolische Diskontieren.',
      'Exponentielles Diskontieren kehrt die Präferenz bei jeder Verschiebung um.',
    ],
    correctAnswer: 1,
    explanation: 'Zeitkonsistenz: Die Entscheidung darf sich nicht ändern, wenn beide Optionen um die gleiche Spanne verschoben werden. Exponentielles Diskontieren ist zeitkonsistent — die reine Verschiebung ändert die Rangfolge nicht.',
  },
  {
    id: 'zeit-q05',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Worin unterscheidet sich der Diskontfaktor des hyperbolischen vom exponentiellen Diskontieren?',
    options: [
      'Hyperbolisch steht (1+i)^n im Nenner, exponentiell (1 + i·n).',
      'Hyperbolisch steht (1 + i·n) im Nenner statt (1+i)^n; der effektive Diskontsatz ist nahe der Gegenwart höher.',
      'Beide verwenden denselben Nenner.',
      'Hyperbolisch verzichtet vollständig auf den Zinssatz i.',
    ],
    correctAnswer: 1,
    explanation: 'Beim hyperbolischen Diskontieren steht (1 + i·n) statt (1+i)^n im Nenner. Der effektive Diskontsatz hängt vom Zeitpunkt ab: nahe der Gegenwart ist er höher, also die Ungeduld größer.',
  },
  {
    id: 'zeit-q06',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Was zeigt die Präferenzumkehr beim hyperbolischen Diskontieren?',
    options: [
      'Die Rangfolge zweier Optionen bleibt bei zeitlicher Verschiebung immer gleich.',
      'Allein die zeitliche Verschiebung kehrt die Rangfolge um — bei nahem Horizont wählt man die sofortige, bei fernem Horizont die spätere, größere Auszahlung.',
      'Bei nahem Horizont wartet man, bei fernem Horizont greift man sofort zu.',
      'Die Höhe der Auszahlung spielt keine Rolle.',
    ],
    correctAnswer: 1,
    explanation: 'Bei nahem Horizont (1000 € in 1 Jahr vs. 1060 € in 2 Jahren) greift man sofort zu; bei fernem Horizont (1000 € in 9 Jahren vs. 1060 € in 10 Jahren) wartet man. Allein die Verschiebung kehrt die Rangfolge um.',
  },
  {
    id: 'zeit-q07',
    topicId: 'zeit-in-der-oekonomie',
    type: 'single',
    question: 'Welchen empirischen Befund liefert Thaler (1981) zum impliziten Jahreszins beim Verzicht auf 15 $?',
    options: [
      'Der implizite Jahreszins steigt mit zunehmender Wartezeit.',
      'Der implizite Jahreszins sinkt mit zunehmender Wartezeit (ca. 400 % bei 1 Monat, ca. 21 % bei 10 Jahren) — ein Beleg für hyperbolisches Diskontieren.',
      'Der implizite Jahreszins ist über alle Fristen konstant.',
      'Probanden verlangen für lange Fristen die höchste Verzinsung.',
    ],
    correctAnswer: 1,
    explanation: 'Bei Thaler (1981) sinkt der implizite Jahreszins mit der Frist (ca. 400 % bei 1 Monat, 233 % bei 1 Jahr, 21 % bei 10 Jahren) — ein empirischer Beleg für hyperbolisches Diskontieren.',
  },
  {
    id: 'zeit-q08',
    topicId: 'zeit-in-der-oekonomie',
    type: 'multiple',
    question: 'Welche weiteren Zeitanomalien werden im Kapitel genannt?',
    options: [
      'Vorzeicheneffekt: Gewinne werden stärker diskontiert als Verluste',
      'Größeneffekt: kleine Beträge werden stärker diskontiert als große',
      'Vorliebe für steigende Konsumprofile bei gleicher Gesamtsumme',
      'Vorliebe für fallende Konsumprofile bei gleicher Gesamtsumme',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Vorzeicheneffekt (Gewinne stärker diskontiert), Größeneffekt (kleine Beträge stärker diskontiert) und die Vorliebe für STEIGENDE Konsumprofile sind die genannten Anomalien — nicht für fallende.',
  },

  // ===================================================================
  // Kapitel 6 · Prospect Theory und ihre Konsequenzen
  // ===================================================================
  {
    id: 'prospect-q01',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Was zeigt das Allais-Paradoxon?',
    options: [
      'dass Menschen stets die Alternative mit dem höchsten Erwartungswert wählen',
      'einen Widerspruch zur Erwartungsnutzentheorie: die Mehrheitswahl in zwei strukturgleichen Problemen ist logisch inkonsistent',
      'dass Wahrscheinlichkeiten objektiv korrekt gewichtet werden',
      'dass die Prospect Theory empirisch widerlegt ist',
    ],
    correctAnswer: 1,
    explanation: 'Das Allais-Paradoxon zeigt eine Anomalie: In Problem I wählt die Mehrheit B (statt des erwartungswerthöheren A), in Problem II C. Die Folgerung aus I widerspricht der Präferenz aus II — das verletzt die Erwartungsnutzentheorie und motiviert die Prospect Theory.',
  },
  {
    id: 'prospect-q02',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Worauf bezieht sich die Bewertung in der Prospect Theory?',
    options: [
      'auf das absolute Endvermögen',
      'auf Gewinne und Verluste relativ zu einem Referenzpunkt',
      'ausschließlich auf objektive Wahrscheinlichkeiten',
      'auf den durchschnittlichen Marktpreis',
    ],
    correctAnswer: 1,
    explanation: 'Die Prospect Theory ist ein deskriptives Modell: Bewertet werden Gewinne und Verluste relativ zu einem Referenzpunkt, nicht das absolute Endvermögen.',
  },
  {
    id: 'prospect-q03',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'multiple',
    question: 'Welche Aussagen zu den zwei Phasen der Entscheidungsfindung in der Prospect Theory sind korrekt?',
    options: [
      'Editing (Aufbereitung): Operationen wie Kombination, Vereinfachung, Segregation, Kodierung und Cancellation.',
      'Evaluation (Bewertung): über die Wertfunktion v und die Gewichtungsfunktion π.',
      'Der subjektive Wert eines Prospekts ergibt sich als V(x;p) = π(p)·v(x).',
      'Die Gewichtungsfunktion π ist eine exakte Maßzahl der objektiven Wahrscheinlichkeit.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'In der Editing-Phase werden Prospects durch Operationen aufbereitet, in der Evaluation über Wertfunktion v und Gewichtungsfunktion π bewertet: V = π(p)·v(x). π ist gerade KEINE exakte Maßzahl, sondern die subjektive Einschätzung der Wahrscheinlichkeit.',
  },
  {
    id: 'prospect-q04',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Wie verläuft die Wertfunktion der Prospect Theory?',
    options: [
      'durchgehend konkav über Gewinne und Verluste',
      'konkav im Gewinnbereich (risikoscheu), konvex im Verlustbereich (risikofreudig) und im Verlustbereich steiler (Verlustaversion)',
      'durchgehend konvex',
      'linear mit gleicher Steigung in beiden Bereichen',
    ],
    correctAnswer: 1,
    explanation: 'Die S-förmige Wertfunktion ist konkav im Gewinn- (risikoscheu) und konvex im Verlustbereich (risikofreudig), dabei im Verlust steiler — Verluste werden etwa doppelt so stark bewertet wie gleich hohe Gewinne (Verlustaversion).',
  },
  {
    id: 'prospect-q05',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Was beschreibt der Reflexionseffekt?',
    options: [
      'Bei positiven und negativen Prospekten ist das Risikoverhalten identisch.',
      'Die Spiegelung von Gewinnen zu Verlusten kehrt das Risikoverhalten um: bei positiven Prospekten Risikoaversion, bei negativen Risikofreude.',
      'Verluste werden grundsätzlich weniger stark gewichtet als Gewinne.',
      'Die Risikoeinstellung hängt nur von der Höhe des Betrags ab.',
    ],
    correctAnswer: 1,
    explanation: 'Der Reflexionseffekt: Spiegelt man Gewinne zu Verlusten, kehrt sich das Risikoverhalten um — bei positiven Prospekten dominiert Risikoaversion, bei negativen Risikofreude.',
  },
  {
    id: 'prospect-q06',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Was beschreibt der Dispositionseffekt an der Börse?',
    options: [
      'Gewinne werden zu lange gehalten, Verluste zu früh realisiert.',
      'Gewinne werden zu früh realisiert (Risikoaversion im Gewinnbereich), Verluste werden ausgesessen (Risikofreude im Verlustbereich).',
      'Alle Positionen werden gleichzeitig verkauft.',
      'Der Einstandspreis spielt keine Rolle.',
    ],
    correctAnswer: 1,
    explanation: 'Der Dispositionseffekt (Sunk-Cost an der Börse): Gewinne werden zu früh realisiert (Risikoaversion im Gewinnbereich), Verluste werden ausgesessen (Risikofreude im Verlustbereich) — relativ zum Einstandspreis als Referenzpunkt.',
  },
  {
    id: 'prospect-q07',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Wie erklärt die Prospect Theory den Besitztumseffekt (Endowment Effect)?',
    options: [
      'Der Kaufpreis liegt stets über dem Verkaufspreis.',
      'Der geforderte Verkaufspreis liegt über dem Kaufpreis, weil Verkauf als Verlust und Kauf als Gewinn kodiert wird und die Verlustkurve steiler ist.',
      'Käufer und Verkäufer bewerten ein Gut immer identisch.',
      'Der Effekt beruht auf der Überbewertung kleiner Wahrscheinlichkeiten.',
    ],
    correctAnswer: 1,
    explanation: 'Beim Endowment Effect liegt der geforderte Verkaufspreis über dem Kaufpreis: Verkauf wird als Verlust, Kauf als Gewinn kodiert; die steilere Verlustkurve erzeugt die Bewertungsasymmetrie.',
  },
  {
    id: 'prospect-q08',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Wie verläuft die Gewichtungsfunktion π(p) der Prospect Theory?',
    options: [
      'Kleine Wahrscheinlichkeiten werden unterbewertet, große überbewertet.',
      'Kleine, unwahrscheinliche Ereignisse werden überbewertet (π(p) > p), mittlere und hohe Wahrscheinlichkeiten unterbewertet (π(p) < p).',
      'Alle Wahrscheinlichkeiten werden exakt gewichtet (π(p) = p).',
      'Nur Wahrscheinlichkeiten über 50 % werden gewichtet.',
    ],
    correctAnswer: 1,
    explanation: 'Kleine, objektiv unwahrscheinliche Ereignisse werden überbewertet (π(p) > p), mittlere und hohe Wahrscheinlichkeiten unterbewertet (π(p) < p). An den Endpunkten (0 % und 100 %) verläuft die Funktion sehr steil (Certainty-Effekt).',
  },
  {
    id: 'prospect-q09',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'multiple',
    question: 'Wie verbucht Hedonic Framing Gewinne und Verluste, um den wahrgenommenen Nutzen zu maximieren?',
    options: [
      'Gewinne werden eher getrennt (segregiert).',
      'Verluste werden integriert (zusammengefasst).',
      'Kleine Verluste werden mit großen Gewinnen integriert.',
      'Große Gewinne werden in kleine Verluste aufgeteilt.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Hedonic Framing: Gewinne segregieren, Verluste integrieren, kleine Verluste mit großen Gewinnen integrieren und kleine Gewinne von großen Verlusten trennen — so wird der wahrgenommene Nutzen maximiert.',
  },
  {
    id: 'prospect-q10',
    topicId: 'prospect-theory-und-ihre-konsequenzen',
    type: 'single',
    question: 'Warum wird die Fahrradversicherung (Prämie 40 €, Wert 600 €, Diebstahlwahrscheinlichkeit 5 %) subjektiv attraktiv, obwohl sie im Erwartungswert teurer ist?',
    options: [
      'weil der objektive Erwartungswert der Versicherung günstiger ist (−40 € statt −30 €)',
      'weil die kleine Diebstahlwahrscheinlichkeit überbewertet wird: π(0,05) ist viel größer als 0,05',
      'weil große Wahrscheinlichkeiten überbewertet werden',
      'weil Verluste schwächer gewichtet werden als Gewinne',
    ],
    correctAnswer: 1,
    explanation: 'Objektiv ist "keine Versicherung" mit −30 € günstiger als die Versicherung mit −40 €. Subjektiv wird die kleine Diebstahlwahrscheinlichkeit überbewertet (π(0,05) ≫ 0,05), sodass die Versicherung attraktiv erscheint.',
  },

  // ===================================================================
  // Kapitel 7 · Altersvorsorge und private Finanzplanung
  // ===================================================================
  {
    id: 'altersvorsorge-q01',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'multiple',
    question: 'Warum ist die Altersvorsorge besonders anfällig für Verzerrungen?',
    options: [
      'außergewöhnlich langer Anlagehorizont',
      'begrenzte Lernmöglichkeiten (man entscheidet nur wenige Male im Leben)',
      'oft fehlendes Finanzwissen',
      'tägliche Wiederholung identischer Entscheidungen mit sofortigem Feedback',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Drei Bedingungen verstärken das Problem: extrem langer Horizont, kaum Gelegenheit zum Lernen und geringe Kenntnisse über Finanzmärkte. Tägliche Wiederholung mit Feedback liegt gerade NICHT vor.',
  },
  {
    id: 'altersvorsorge-q02',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'multiple',
    question: 'Welche Befunde widersprechen der neoklassischen Lebenszyklus-Hypothese?',
    options: [
      '"Ältere" Haushalte weisen tendenziell positive Sparquoten auf — kein Abbau im Ruhestand.',
      'Das Konsumprofil wird stark vom Einkommensprofil beeinflusst.',
      'Das Modell sagt ein buckelförmiges Sparprofil mit Vermögensabbau im Ruhestand voraus.',
      'Das Konsumniveau bleibt unabhängig vom Einkommen vollständig konstant.',
    ],
    correctAnswers: [0, 1],
    explanation: 'Empirisch zeigen ältere Haushalte positive Sparquoten und das Konsumprofil hängt stark vom Einkommen ab — beides widerspricht dem Modell. Das buckelförmige Profil ist die Modellvorhersage (Punkt 3), nicht der widersprechende Befund.',
  },
  {
    id: 'altersvorsorge-q03',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was zeigt das Organspende-Beispiel (Opt-In vs. Opt-Out) zum Default-Effekt?',
    options: [
      'Der Default hat kaum Einfluss auf die Beteiligungsquote.',
      'Der Default entscheidet dramatisch: Opt-In-Länder ~4–28 %, Opt-Out-Länder ~86–100 % Zustimmung.',
      'In Opt-Out-Ländern liegen die Quoten niedriger als in Opt-In-Ländern.',
      'Defaults wirken nur bei der Altersvorsorge, nicht bei Organspende.',
    ],
    correctAnswer: 1,
    explanation: 'Der Default entscheidet dramatisch über die Beteiligungsquote: Opt-In ~4–28 %, Opt-Out ~86–100 %. Default-Effekte gelten als eines der robustesten Ergebnisse der angewandten Wirtschaftsliteratur.',
  },
  {
    id: 'altersvorsorge-q04',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was zeigt das Marmeladen-Experiment (Iyengar/Lepper 2000) zum Choice Overload?',
    options: [
      'Das größere Sortiment führte zu mehr Aufmerksamkeit UND mehr Käufen.',
      'Das größere Sortiment (24 Sorten) zog mehr Aufmerksamkeit (60 % vs. 40 % blieben stehen), senkte aber die Kaufquote (3 % vs. 30 %).',
      'Das kleinere Sortiment führte zu weniger Aufmerksamkeit und weniger Käufen.',
      'Die Sortimentsgröße hatte keinen Einfluss.',
    ],
    correctAnswer: 1,
    explanation: 'Mehr Auswahl lockt an (60 % vs. 40 % blieben stehen), lähmt aber den Abschluss (nur 3 % vs. 30 % kauften). Zu viele Optionen führen zur Entscheidungslähmung — dasselbe Muster zeigt sich bei Vorsorgeplänen.',
  },
  {
    id: 'altersvorsorge-q05',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'multiple',
    question: 'Welche Lösungen gegen Beitritts-Hindernisse (Trägheit, Komplexität) nennt das Kapitel?',
    options: [
      'automatische Anmeldung (Opt-out) — Teilnahmequoten steigen massiv',
      'eindeutige, einfache Auswahlmöglichkeiten (Schnellanmelde-Option)',
      'eine möglichst große Zahl von Fondsoptionen anbieten',
      'Beitritt nur per aktiver Zustimmung (Opt-in) erzwingen',
    ],
    correctAnswers: [0, 1],
    explanation: 'Lösungen sind die automatische Anmeldung (Opt-out, z. B. Madrian/Shea: 37 % → 86 %) und eindeutige, einfache Auswahlmöglichkeiten. Mehr Fonds und reines Opt-in verschärfen die Probleme.',
  },
  {
    id: 'altersvorsorge-q06',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Wie funktioniert das SMarT-Programm ("Save More Tomorrow", Thaler/Benartzi)?',
    options: [
      'Es senkt die Sparrate bei jeder Gehaltskürzung.',
      'Es koppelt Beitragserhöhungen an künftige Gehaltssteigerungen, wodurch die Sparquote über die Jahre kontinuierlich steigt.',
      'Es zwingt zu einer einmaligen hohen Sofortzahlung.',
      'Es verbietet jede automatische Erhöhung.',
    ],
    correctAnswer: 1,
    explanation: 'SMarT koppelt Beitragserhöhungen an künftige Gehaltssteigerungen. Die Sparquote der Auto-Increase-Gruppe stieg von 3,5 % (1998) auf 13,6 % (2002) — deutlich stärker als bei einmaliger Beratung.',
  },
  {
    id: 'altersvorsorge-q07',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was beschreibt die bedingte 1/N-Regel bei der Fondsauswahl?',
    options: [
      'Teilnehmer verteilen ihr Geld gleichmäßig auf ALLE angebotenen Fonds.',
      'Teilnehmer wählen 3–4 Fonds und verteilen gleichmäßig darauf, sodass die Aktienquote allein vom Verhältnis Aktien- zu Anleihefonds im Menü abhängt.',
      'Teilnehmer investieren stets vollständig in Aktienfonds.',
      'Die Allokation ist unabhängig vom angebotenen Fondsmenü.',
    ],
    correctAnswer: 1,
    explanation: 'Bei der bedingten 1/N-Regel verteilen Teilnehmer ihr Geld gleichmäßig auf die 3–4 GEWÄHLTEN Fonds. Dadurch hängt die Aktienquote vom Menü ab (UC mit 4 Anleihe-/1 Aktienfonds: 34 %; TWA mit 1/5: 75 %) — ein reiner Menüeffekt.',
  },
  {
    id: 'altersvorsorge-q08',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Was beschreibt die Trendfolge (Extrapolation) bei der Anlageentscheidung?',
    options: [
      'Neue Teilnehmer richten ihre Aktienquote stark an der jüngsten Marktentwicklung aus (hoch in der Hausse, Einbruch nach Crash).',
      'Alle Teilnehmer halten eine konstante Aktienquote unabhängig vom Markt.',
      'Teilnehmer kaufen antizyklisch nach Kursverlusten.',
      'Die Aktienquote folgt ausschließlich dem Lebenszyklusfonds.',
    ],
    correctAnswer: 0,
    explanation: 'Bei der Trendfolge extrapolieren neue Teilnehmer die jüngste Marktentwicklung: hohe Aktienquoten in der Hausse der späten 1990er, Einbruch auf 54 % nach dem Markteinbruch 2002 — während die Quote aller (trägen) Teilnehmer kaum schwankt.',
  },
  {
    id: 'altersvorsorge-q09',
    topicId: 'altersvorsorge-und-private-finanzplanung',
    type: 'single',
    question: 'Wie verbessern Lebenszyklus-/Target-Maturity-Fonds (Mitchell et al. 2009) das Portfolio?',
    options: [
      'Sie senken den Aktienanteil und erhöhen extreme Allokationen.',
      'Sie erhöhen den Aktienanteil, reduzieren extreme Vermögensallokationen und verringern das nicht-systematische Risiko durch automatisches Rebalancing.',
      'Sie verzichten vollständig auf Aktien.',
      'Sie verstärken die naive Diversifizierung.',
    ],
    correctAnswer: 1,
    explanation: 'Lebenszyklus-/Target-Maturity-Fonds übernehmen das Rebalancing automatisch: höherer Aktienanteil, weniger extreme Allokationen, geringeres nicht-systematisches Risiko — die Lösung gegen naive Diversifizierung und Trendfolge.',
  },

  // ===================================================================
  // Kapitel 8 · Spekulationsblasen an Finanzmärkten
  // ===================================================================
  {
    id: 'spekulationsblasen-q01',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Wie definiert das Kapitel eine Spekulationsblase?',
    options: [
      'eine kurzfristige, geringfügige Preisschwankung ohne Folgen',
      'eine starke und langfristige Übertreibung bei den Preisen für Wertpapiere, Immobilien oder andere Anlagegüter',
      'eine effiziente Anpassung der Preise an die Fundamentaldaten',
      'eine reine Erscheinung des Anleihemarktes',
    ],
    correctAnswer: 1,
    explanation: 'Eine Spekulationsblase ist eine Marktanomalie: eine starke und langfristige Übertreibung bei den Preisen für Wertpapiere, Immobilien oder andere Anlagegüter (Putnoki 2018).',
  },
  {
    id: 'spekulationsblasen-q02',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Was beschreibt die Preis-Story-Preis-Schleife des Spekulationsfiebers?',
    options: [
      'eine einmalige Preisanpassung ohne Rückkopplung',
      'eine selbstverstärkende Feedback-Schleife: steigende Kurse erzeugen Geschichten, die den Glauben an die Fortsetzung des Booms bestärken und weitere Kursanstiege auslösen',
      'die rationale Einpreisung aller verfügbaren Informationen',
      'das Absinken der Ansteckungsrate unter die Abklingrate',
    ],
    correctAnswer: 1,
    explanation: 'Die Preis-Story-Preis-Schleife ist eine selbstverstärkende Feedback-Schleife: Beobachtungen und mediale Berichterstattung erzeugen steigende Kurse und Geschichten, die den Boom-Glauben immer neu bestätigen.',
  },
  {
    id: 'spekulationsblasen-q03',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Was kennzeichnet eine rationale (fast-rationale) Blase?',
    options: [
      'Die Akteure sind völlig uninformiert über die Blase.',
      'Die Akteure wissen, dass die Blase platzen wird, kennen aber den Zeitpunkt nicht und hoffen, vorher an einen "größeren Narren" zu verkaufen.',
      'Der Preis spiegelt stets exakt den Fundamentalwert.',
      'Es gibt keinen Wiederverkaufswert.',
    ],
    correctAnswer: 1,
    explanation: 'Bei rationalen Blasen ist der Preis Funktion des erwarteten (Wieder-)Verkaufswerts. Die Akteure wissen, dass die Blase platzt, kennen aber den Zeitpunkt nicht — "Markt der größeren Narren".',
  },
  {
    id: 'spekulationsblasen-q04',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'In welcher Reihenfolge verlaufen die fünf Phasen nach Kindleberger/Minsky?',
    options: [
      'Euphorie → Verlagerung → Positives Feedback → Abscheu → Kritische Phase',
      'Verlagerung → Positives Feedback → Euphorie → Kritische Phase → Abscheu',
      'Abscheu → Kritische Phase → Euphorie → Positives Feedback → Verlagerung',
      'Positives Feedback → Verlagerung → Kritische Phase → Euphorie → Abscheu',
    ],
    correctAnswer: 1,
    explanation: 'Die Sequenz lautet: Verlagerung → Positives Feedback → Euphorie → Kritische Phase (finanzielle Not, am Gipfel) → Abscheu (Panik/Crash auf dem Abwärtsast).',
  },
  {
    id: 'spekulationsblasen-q05',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Wo liegt die "kritische Phase" (finanzielle Not) auf der Blasenkurve?',
    options: [
      'ganz am Anfang im flachen Bereich',
      'am Gipfel (Hochpunkt) der Kurve, die Abscheu (Crash) folgt erst danach',
      'erst spät auf dem abfallenden rechten Ast',
      'parallel zur Verlagerungsphase',
    ],
    correctAnswer: 1,
    explanation: 'Die kritische Phase (finanzielle Not) liegt am Gipfel. Die Abscheu (Panik, Crash) folgt erst danach auf dem Abwärtsast — die Reihenfolge ist klausurrelevant.',
  },
  {
    id: 'spekulationsblasen-q06',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'multiple',
    question: 'Welche vier Auslöser-Kategorien des Herdentriebs nennt das Kapitel?',
    options: [
      'Informationskaskaden (eigene Infos werden ignoriert)',
      'Reputationsinteressen (Sorge um den eigenen Ruf)',
      'Informationsquellen und historische Marktbewegungen (Chart-Analyse)',
      'vollständiger Verzicht auf jede soziale Orientierung',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die vier Kategorien sind Informationskaskaden, Reputationsinteressen, gemeinsame Informationsquellen und die Analyse historischer Marktbewegungen. Verzicht auf soziale Orientierung ist gerade kein Herdentrieb.',
  },
  {
    id: 'spekulationsblasen-q07',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Welche Verhaltensanomalie tritt am Gipfel auf und welche erst spät nach dem Crash?',
    options: [
      'am Gipfel gelernte Hilflosigkeit, nach dem Crash erlernte Sorglosigkeit',
      'am Gipfel erlernte Sorglosigkeit, spät nach dem Crash gelernte Hilflosigkeit',
      'beide treten gleichzeitig am Gipfel auf',
      'beide treten in der Verlagerungsphase auf',
    ],
    correctAnswer: 1,
    explanation: 'Erlernte Sorglosigkeit tritt am Gipfel auf, gelernte Hilflosigkeit erst spät nach dem Absturz. Herding markiert den Beginn der Wende.',
  },
  {
    id: 'spekulationsblasen-q08',
    topicId: 'spekulationsblasen-an-finanzmaerkten',
    type: 'single',
    question: 'Wie wirken Spekulationsblasen volkswirtschaftlich?',
    options: [
      'ausschließlich schädlich',
      'ambivalent: kurzfristig konsum- und investitionsfördernd, langfristig drohen Verlust der Preisfunktion sowie Kaufkraft- und Vertrauensverlust',
      'ausschließlich förderlich',
      'völlig neutral ohne realwirtschaftliche Effekte',
    ],
    correctAnswer: 1,
    explanation: 'Blasen wirken ambivalent: kurzfristig fördernd (Einkommens-, Bilanz-, Übertragungseffekt), langfristig drohen Verlust der Informationsfunktion von Preisen, Kaufkraftverlust und Vertrauensverlust mit Übergreifen auf die Realwirtschaft.',
  },

  // ===================================================================
  // Kapitel 9 · Kapitalanlage und Kapitalmarktanomalien
  // ===================================================================
  {
    id: 'kapitalanlage-q01',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'multiple',
    question: 'Welche drei Formen der Informationseffizienz unterscheidet Fama?',
    options: [
      'schwache Form: nur vergangene Informationen im Kurs',
      'halb-strenge Form: alle öffentlich zugänglichen Informationen',
      'strenge Form: öffentliche und private Informationen',
      'totale Form: ausschließlich zukünftige Informationen',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Fama unterscheidet die schwache (vergangene Infos), halb-strenge (alle öffentlichen Infos) und strenge Form (öffentliche und private Infos). Eine "totale Form" existiert nicht.',
  },
  {
    id: 'kapitalanlage-q02',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Was besagt das Grossman/Stiglitz-Paradoxon (1980)?',
    options: [
      'Märkte sind immer vollkommen effizient.',
      'Vollkommene Effizienz ist logisch unmöglich, weil Information kostet: Ohne Ertrag sucht niemand Information, was die Suche wieder lohnend macht — das Gleichgewicht liegt zwischen den Extremen.',
      'Information ist stets kostenlos verfügbar.',
      'Psychologie bestimmt die Markteffizienz vollständig.',
    ],
    correctAnswer: 1,
    explanation: 'Das Information-Paradoxon: Wäre alles eingepreist, lohnte sich keine kostenpflichtige Informationssuche; sucht aber niemand, lohnt sie sich wieder. Vollkommene Effizienz ist daher logisch unmöglich; das Gleichgewicht liegt zwischen den Extremen.',
  },
  {
    id: 'kapitalanlage-q03',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'multiple',
    question: 'Welche Aussagen kennzeichnen die Behavioral-Finance-Sicht im Gegensatz zur Traditional Finance?',
    options: [
      'Höhere Renditen lassen sich auch ohne höheres Risiko erzielen.',
      'Wertpapierrenditen lassen sich zum Teil prognostizieren.',
      'Märkte sind teilweise falsch bewertet; Preise werden durch beschränkt rationale Investoren beeinflusst.',
      'Mehrrendite ist ausschließlich das Ergebnis höheren Risikos.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Behavioral Finance: höhere Renditen auch ohne höheres Risiko, teilweise Prognostizierbarkeit, teilweise falsch bewertete Märkte durch beschränkt rationale Investoren. "Mehrrendite nur durch höheres Risiko" ist die traditionelle Sicht.',
  },
  {
    id: 'kapitalanlage-q04',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'multiple',
    question: 'Welche Zuordnungen von Kapitalmarktanomalie und möglicher verhaltensökonomischer Erklärung sind korrekt?',
    options: [
      'Home Bias → Verfügbarkeitsheuristik (mehr Infos über das Heimatland)',
      'Dispositionseffekt → Prospect Theory (Verlustaversion)',
      'Januar-Effekt → mentale Kontenführung (Verlustrealisierung zum Jahresende, Rückkauf im Januar)',
      'Chartanalyse → Risikoprämie für Liquidität',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Home Bias → Verfügbarkeitsheuristik, Dispositionseffekt → Prospect Theory/Verlustaversion, Januar-Effekt → mentale Kontenführung. Die Chartanalyse wird über die Repräsentativität (nur zufällige Muster) erklärt, nicht über eine Liquiditätsprämie.',
  },
  {
    id: 'kapitalanlage-q05',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Was besagt der Winner-Loser-Effekt (De Bondt/Thaler 1985)?',
    options: [
      'Vergangene Gewinner bleiben dauerhaft Gewinner.',
      'Vergangene Verlierer werden zukünftige Gewinner und vergangene Gewinner zukünftige Verlierer — als Folge von Überreaktionen.',
      'Die Vergangenheitsperformance hat keinen Einfluss auf die Zukunft.',
      'Loser-Portfolios fallen weiter, Winner-Portfolios steigen weiter.',
    ],
    correctAnswer: 1,
    explanation: 'Beim Winner-Loser-Effekt kehren sich die Rollen um: Das Loser-Portfolio erzielt steigende kumulierte Überrenditen, das Winner-Portfolio fällt zurück. Vergangene Verlierer werden zukünftige Gewinner — Folge von Überreaktion und Repräsentativität.',
  },
  {
    id: 'kapitalanlage-q06',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Was beschreibt der Value-Effekt (Fama/French 1992)?',
    options: [
      'Growth-Aktien (niedriges B/M) erzielen die höchsten Renditen.',
      'Aktien mit hohem Buchwert/Marktwert-Verhältnis (Value) erzielen höhere Renditen als Growth-Aktien (niedriges B/M).',
      'Das B/M-Verhältnis hat keinen Einfluss auf die Rendite.',
      'Hohes B/M korreliert mit hohem CAPM-Beta.',
    ],
    correctAnswer: 1,
    explanation: 'Value-Aktien (hohes B/M) erzielen höhere Renditen als Growth-Aktien (niedriges B/M); die risikoadjustierte Differenz betrug 19,99 % (1963–1990). Die Risiko-Hypothese ist widerlegt, weil hohes Beta mit NIEDRIGEM B/M korreliert.',
  },
  {
    id: 'kapitalanlage-q07',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Warum gilt Fehlbewertung als wahrscheinlichste Erklärung des Value-Effekts und nicht Risiko oder Zufall?',
    options: [
      'weil Data-Mining den Effekt vollständig erklärt',
      'weil Wachstum mean reverting ist und Anleger gute (Growth) bzw. schlechte (Value) Fundamentaldaten zu weit fortschreiben, während die Risiko-Hypothese empirisch widerlegt ist (Beta korreliert negativ mit B/M)',
      'weil der Effekt nur in einem einzigen Markt auftritt',
      'weil hohes B/M zwingend hohes Risiko bedeutet',
    ],
    correctAnswer: 1,
    explanation: 'Zufall ist unwahrscheinlich (Fama/French zeigen den Effekt international out-of-sample), Risiko ist widerlegt (hohes Beta korreliert mit niedrigem B/M). Fehlbewertung bleibt: Wachstum ist mean reverting, Anleger extrapolieren Fundamentaldaten zu weit.',
  },
  {
    id: 'kapitalanlage-q08',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'multiple',
    question: 'Welche Aussagen zu Size- und Momentum-Effekt sind korrekt?',
    options: [
      'Size-Effekt: Small Caps erzielen historisch höhere Durchschnittsrenditen als Large Caps (Small minus Large, SMB).',
      'Momentum-Effekt: Gewinner der jüngsten Vergangenheit bleiben kurzfristig Gewinner; der stabile Trendkern dauert typischerweise rund ein Jahr.',
      'Der Momentum-Effekt ist zeitlich begrenzt und lässt danach nach.',
      'Large Caps erzielen historisch höhere Renditen als Small Caps.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Size-Effekt (SMB): Small Caps schlagen Large Caps. Momentum: Trends setzen sich kurzfristig fort, der stabile Kern dauert etwa ein Jahr und der Effekt ist zeitlich begrenzt. Dass Large Caps Small Caps schlagen, ist falsch.',
  },
  {
    id: 'kapitalanlage-q09',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Wie funktioniert die antizyklische Strategie über die implizite Risikoprämie (Mean Reversion)?',
    options: [
      'Bei hoher Prämie untergewichten, bei niedriger Prämie übergewichten.',
      'Bei hoher Prämie übergewichten (kaufen), bei niedriger Prämie untergewichten (verkaufen), in Erwartung der Rückkehr zum Mittelwert.',
      'Die Prämie wird ignoriert, da sie nicht prognostizierbar ist.',
      'Es wird stets prozyklisch gehandelt.',
    ],
    correctAnswer: 1,
    explanation: 'Die implizite Risikoprämie schwankt um ihren langfristigen Mittelwert (Mean Reversion). Bei hoher Prämie (über Mittel, Angst) wird übergewichtet/gekauft, bei niedriger Prämie (unter Mittel, Euphorie) untergewichtet/verkauft — antizyklisches Handeln.',
  },
  {
    id: 'kapitalanlage-q10',
    topicId: 'kapitalanlage-und-kapitalmarktanomalien',
    type: 'single',
    question: 'Wie entsteht das idealtypische Vier-Phasen-Muster eines Kurstrends (Momentum)?',
    options: [
      'Der Kurs übertreibt zuerst und unterreagiert zuletzt.',
      'Der Ist-Kurs unterreagiert zuerst auf eine Information (Verankerung, grüne Lücke) und schießt später psychologisch über den fairen Wert hinaus (Übertreibung, rote Fläche).',
      'Der Ist-Kurs folgt dem fairen Wert stets exakt.',
      'Der faire Wert steigt schneller als der Ist-Kurs in allen Phasen.',
    ],
    correctAnswer: 1,
    explanation: 'Das Trendmuster entsteht aus dem Wechsel von Unterreaktion (Verankerung, Kurs hinkt hinterher) zu Übertreibung (psychologische Trendverselbständigung über den fairen Wert hinaus). Erst hinkt der Kurs hinterher, dann verselbständigt sich der Anstieg.',
  },

  // ===================================================================
  // Kapitel 10 · Behavioral Corporate Finance
  // ===================================================================
  {
    id: 'corporate-finance-q01',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Worin unterscheidet sich Behavioral Corporate Finance von der traditionellen Corporate-Finance-Theorie?',
    options: [
      'Behavioral Corporate Finance geht von vollständig rationalen Managern und effizienten Kapitalmärkten aus.',
      'Behavioral Corporate Finance nimmt begrenzt rationale Manager und nicht vollständig effiziente Kapitalmärkte an, während die traditionelle Theorie von vollständig rationalen Agenten ausgeht.',
      'Beide Theorien unterscheiden sich nur in der verwendeten Terminologie, inhaltlich sind sie identisch.',
      'Behavioral Corporate Finance betrifft ausschließlich Investorenverhalten, nie das Verhalten von Managern.',
    ],
    correctAnswer: 1,
    explanation: 'Die traditionelle Theorie unterstellt vollständig rationale Agenten (Manager reagieren rational auf Governance-Anreize, nehmen effiziente Märkte an). Behavioral Corporate Finance stellt dem empirische Evidenz entgegen: Manager sind begrenzt rational, Kapitalmärkte nicht vollständig effizient.',
  },
  {
    id: 'corporate-finance-q02',
    topicId: 'behavioral-corporate-finance',
    type: 'multiple',
    question: 'Welche Rahmenbedingungen begünstigen laut Vorlesung die Managerial Overconfidence?',
    options: [
      'Hohe Komplexität von Investitionsentscheidungen unter Unsicherheit',
      'Individualität von Investitionsentscheidungen mit erst spät messbarer Qualität (ausbleibende Lerneffekte)',
      'Beförderung erfolgreicher Manager (Gefahr der Selbstattribution) und Kontrollillusion',
      'Ein streng regelbasiertes, vollautomatisiertes Risikomanagementsystem ohne menschliches Ermessen',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Komplexität, Individualität von Entscheidungen, Selbstattribution nach Beförderung und Kontrollillusion begünstigen Selbstüberschätzung. Ein automatisiertes Risikomanagementsystem ist dagegen gerade eine Gegenmaßnahme, keine begünstigende Rahmenbedingung.',
  },
  {
    id: 'corporate-finance-q03',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Was zeigt die empirische CAR-Analyse zu M&A-Transaktionen (u. a. Bradley et al. 1988, Sirower 1998)?',
    options: [
      'Bieterunternehmen (Acquirer) und Zielunternehmen (Targets) profitieren stets etwa gleich stark von der Übernahme.',
      'Die kumulierten Überrenditen (CAR) fallen bei Targets deutlich höher aus als bei Acquirern — Bieteraktionäre profitieren nur marginal oder gar nicht.',
      'Acquirer erzielen durchweg höhere CAR als die übernommenen Targets.',
      'CAR-Analysen zeigen keinerlei systematischen Unterschied zwischen Targets und Acquirern.',
    ],
    correctAnswer: 1,
    explanation: 'Bradley et al. (1988): CAR Targets +28 %, CAR Acquirer +2 %. Sirower (1998): CAR Targets +30,1 %, CAR Bieter −2,6 %. Der Wertzuwachs konzentriert sich fast vollständig beim Zielunternehmen.',
  },
  {
    id: 'corporate-finance-q04',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Was besagt die Hybris-Hypothese als Erklärung für wertvernichtende M&A-Transaktionen?',
    options: [
      'Manager kaufen Zielunternehmen bewusst unter ihrem ökonomischen Wert.',
      'Sind Märkte informationseffizient, ist bereits alles im Kurs des Zielunternehmens verarbeitet — Übernahmeangebote deutlich über dem ökonomischen Wert lassen sich dann durch Selbstüberschätzung (Hybris) des Managements erklären, mit der Folge des "winner\'s curse".',
      'Hybris beschreibt ausschließlich das Verhalten der Aktionäre des Zielunternehmens.',
      'Die Hybris-Hypothese ist identisch mit der Free Cash Flow Hypothese.',
    ],
    correctAnswer: 1,
    explanation: 'Bei informationseffizienten Märkten sind Übernahmepreise weit über dem ökonomischen Wert nur durch die Selbstüberschätzung (Hybris) des Bieter-Managements erklärbar — Folge ist der "winner\'s curse". Die Agency-/Free-Cash-Flow-Erklärung ist ein separater Erklärungsansatz.',
  },
  {
    id: 'corporate-finance-q05',
    topicId: 'behavioral-corporate-finance',
    type: 'multiple',
    question: 'Welche Aussagen zur Begrenzung der Selbstüberschätzung sind korrekt?',
    options: [
      'Längere Mindesthaltedauern von Aktienoptionen und mögliche Verlustbeteiligungen können als vertragliche Anreize wirken.',
      'Die Kontrolle durch Fremdkapitalgeber ist von Anfang an unabhängig vom ökonomischen Erfolg des Unternehmens gleich stark ausgeprägt.',
      'Kalkulation künftiger Cash Flows mit höheren Diskontierungsfaktoren kann Überschätzung entgegenwirken.',
      'Auch Aufsichtsräte als Kontrollorgan können selbst der Gefahr der Selbstüberschätzung unterliegen.',
    ],
    correctAnswers: [0, 2, 3],
    explanation: 'Vertragliche Anreize, höhere Diskontierungsfaktoren und die (eingeschränkte) Kontrollfunktion von Aufsichtsräten sind zutreffend. Falsch ist, dass FK-Geber-Kontrolle unabhängig vom Erfolg gleich stark wirkt — der Kontrollanreiz steigt erst mit wachsender Gefahr ökonomischen Misserfolgs.',
  },
  {
    id: 'corporate-finance-q06',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Wie hat sich die Ausschüttungspolitik US-amerikanischer Industrieunternehmen seit den 1970er-Jahren laut Berk/DeMarzo (2011) entwickelt?',
    options: [
      'Der Anteil ausschüttender Unternehmen ist kontinuierlich gestiegen, reine Dividenden dominieren weiterhin klar.',
      'Der Gesamtanteil ausschüttender Unternehmen ist seit dem Hoch Ende der 1970er strukturell gesunken, wobei sich die Zusammensetzung von reinen Dividenden hin zu Aktienrückkäufen verschoben hat.',
      'Ausschüttungen jeder Art sind seit den 1970er-Jahren praktisch vollständig verschwunden.',
      'Die Zusammensetzung der Ausschüttungsformen hat sich nie verändert.',
    ],
    correctAnswer: 1,
    explanation: 'Der Anteil ausschüttender Unternehmen fiel vom Hoch ca. 75 % (1978) auf ein Tief um 37–40 % und erholte sich leicht auf ca. 47 % (2007); gleichzeitig gewannen Aktienrückkäufe gegenüber reinen Dividenden an Gewicht.',
  },
  {
    id: 'corporate-finance-q07',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Wie reagieren Aktienkurse typischerweise auf Dividendenänderungen, und was folgt daraus für das Managementverhalten?',
    options: [
      'Kürzungen und Erhöhungen lösen symmetrische, betragsmäßig gleich starke Kursreaktionen aus.',
      'Dividendenkürzungen lösen eine stark negative, Dividendenerhöhungen nur eine leicht positive Kursreaktion aus (konsistent mit der Prospect Theory); Manager vermeiden daher Kürzungen und heben Dividenden nur bei geringer künftiger Kürzungsgefahr an — Ergebnis: Dividend Smoothing.',
      'Dividendenkürzungen werden vom Markt grundsätzlich positiv aufgenommen.',
      'Die Kursreaktion auf Dividendenänderungen steht im Widerspruch zur Prospect Theory.',
    ],
    correctAnswer: 1,
    explanation: 'Die Verlustaversion der Prospect Theory erklärt die Asymmetrie: Kürzungen schmerzen stark (stark negative Kursreaktion), Erhöhungen stiften nur geringen Zusatznutzen (leicht positive Reaktion). Manager glätten Dividenden entsprechend (Dividend Smoothing).',
  },
  {
    id: 'corporate-finance-q08',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Was unterscheidet Underpricing und langfristige Underperformance bei IPOs?',
    options: [
      'Es handelt sich um denselben Effekt, nur mit unterschiedlichen Namen.',
      'Underpricing ist ein kurzfristiges Phänomen (positive marktbereinigte Emissionsrendite am ersten Handelstag, z. B. 10–20 % in Deutschland), Underperformance ein langfristiges Phänomen (negative Performance über 3–5 Jahre) — beide treten empirisch gemeinsam auf, sind aber gegenläufig.',
      'Underpricing tritt nur am Neuen Markt auf, Underperformance nur in den USA.',
      'Underperformance beschreibt ausschließlich die Rendite am ersten Emissionstag.',
    ],
    correctAnswer: 1,
    explanation: 'Underpricing (kurzfristig, positive Erstrendite) und Underperformance (langfristig, negative 3–5-Jahres-Rendite) sind zwei getrennte, gegenläufige empirische Phänomene desselben IPO-Prozesses.',
  },
  {
    id: 'corporate-finance-q09',
    topicId: 'behavioral-corporate-finance',
    type: 'single',
    question: 'Welchen Befund liefert Ritter (2014) beim Vergleich von IPO-Firmen mit size-/BM-gematchten Unternehmen über 5 Jahre?',
    options: [
      'IPO-Firmen übertreffen die gematchten Vergleichsunternehmen im geometrischen Mittel deutlich (11,1 % vs. 13,0 % zugunsten der IPOs).',
      'IPO-Firmen bleiben im geometrischen Mittel der Jahre 1–5 hinter den size-/BM-gematchten Vergleichsunternehmen zurück (11,1 % vs. 13,0 %, Differenz −1,9 Prozentpunkte).',
      'Es besteht kein messbarer Renditeunterschied zwischen IPO-Firmen und gematchten Unternehmen.',
      'Der Renditeunterschied ist in jedem Einzeljahr identisch groß.',
    ],
    correctAnswer: 1,
    explanation: 'Ritter (2014): geometrisches Mittel der Jahre 1–5 beträgt 11,1 % für IPO-Firmen gegenüber 13,0 % für size-/BM-gematchte Vergleichsunternehmen — eine Differenz von −1,9 Prozentpunkten, konsistent mit der langfristigen IPO-Underperformance.',
  },
];

export default questions;
