export const questions = [
  {
    id: 'traditionelle-assetklassen-q01',
    type: 'single',
    question: 'Welche Aussage trifft die Definition von Assetklassen im Topic am genauesten?',
    options: [
      'Assetklassen sind juristische Kategorien, die ausschließlich nach der Rechtsform des Emittenten gebildet werden.',
      'Assetklassen sind Gruppen von Anlagen, die wegen vergleichbarer wirtschaftlicher Eigenschaften ähnlich auf fundamentale Faktoren reagieren.',
      'Assetklassen sind nur alternative Anlagen, die keine laufenden Erträge erwirtschaften.',
      'Assetklassen sind einzelne Wertpapiere, die unabhängig von Wachstum, Inflation oder Ressourcen bewertet werden.',
    ],
    correctAnswer: 1,
    explanation: 'Im Topic werden Assetklassen über vergleichbare wirtschaftliche Eigenschaften und ähnliche Reaktionen auf fundamentale Faktoren definiert.',
  },
  {
    id: 'traditionelle-assetklassen-q02',
    type: 'multiple',
    question: 'Welche Aussagen zur Abgrenzung standardisierter und nicht standardisierter Assetklassen sind korrekt?',
    options: [
      'Standardisierte Assetklassen umfassen im Topic unter anderem Aktien, Anleihen, Geldmarktinstrumente, Währungen, Derivate und Fonds.',
      'Nicht standardisierte Assetklassen sind typischerweise hochliquide, fungibel und regelmäßig mit transparenten Preisen handelbar.',
      'Alternative Assetklassen wie Immobilien, Hedgefonds, Private Equity oder Kunst dienen unter anderem Diversifikation und Renditeoptimierung.',
      'Standardisierte Assetklassen werden im Topic als weniger handelbare Einzelstücke mit meist fehlender Austauschbarkeit beschrieben.',
    ],
    correctAnswers: [0, 2],
    explanation: 'Die Merkmale hoher Liquidität, Fungibilität und transparenter Preise gehören zu den standardisierten Assetklassen; Diversifikation und Renditeoptimierung werden den alternativen Anlagen zugeordnet.',
  },
  {
    id: 'traditionelle-assetklassen-q03',
    type: 'single',
    question: 'Welche Kombination beschreibt die Aktiengesellschaft nach dem Topic korrekt?',
    options: [
      'Mindestkapital EUR 120 000, europaweite Sitzverlegung und erleichterte Fusionen innerhalb der EU.',
      'Persönlich haftende Komplementäre, dualistische oder monistische Führung und Rechtsform seit 2004.',
      'Grundkapital in Aktien zerlegt, Mindestnennbetrag EUR 50 000 und Organe Vorstand, Aufsichtsrat, Hauptversammlung.',
      'Nicht börsennotierte Schuldverschreibung, Kapitalgeber häufig Versicherungen, Kommunen oder Sozialversicherungsträger.',
    ],
    correctAnswer: 2,
    explanation: 'EUR 50 000 Grundkapital, Zerlegung in Aktien und die drei Organe beschreiben die AG; die anderen Optionen beschreiben SE, KGaA oder Schuldscheindarlehen.',
  },
  {
    id: 'traditionelle-assetklassen-q04',
    type: 'single',
    question: 'Welche Aussage trennt Aktionärsstellung und Private Equity korrekt?',
    options: [
      'Aktionäre erwerben Anteilsrechte; nicht börsennotierte Beteiligungen werden im Topic als Private Equity eingeordnet.',
      'Aktionäre sind Gläubiger mit Anspruch auf Kupon und Rückzahlung; Private Equity ist eine börsennotierte Inhaberschuldverschreibung.',
      'Aktionäre erhalten ausschließlich Stimmrechte, aber keine Beteiligung an Dividenden oder Liquidationserlösen.',
      'Private Equity bezeichnet im Topic eine standardisierte Assetklasse mit transparenten Preisen und geringen Transaktionskosten.',
    ],
    correctAnswer: 0,
    explanation: 'Mit Aktien werden Anteilsrechte erworben; nicht börsennotierte Beteiligungen werden als Private Equity eingeordnet.',
  },
  {
    id: 'traditionelle-assetklassen-q05',
    type: 'multiple',
    question: 'Welche Paare aus Unterscheidungskriterium und Aktienart passen zusammen?',
    options: [
      'Stimmrecht: Stammaktien und Vorzugsaktien.',
      'Übertragbarkeit: Inhaberaktien und Namensaktien.',
      'Anteil am Grundkapital: Nennwertaktien und Stückaktien.',
      'Bonitätsrisiko: Wandelanleihen und Optionsanleihen.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die drei Kriterien im Topic sind Stimmrecht, Übertragbarkeit und Anteil am Grundkapital; Bonitätsrisiko ist kein Kriterium zur Einteilung von Aktienarten.',
  },
  {
    id: 'traditionelle-assetklassen-q06',
    type: 'single',
    question: 'Welche Aussage zu Vorzugsaktien ist prüfungsnah korrekt?',
    options: [
      'Sie sind Schuldverschreibungen ohne Eigentümerstellung, aber mit kumulativem Kuponanspruch.',
      'Sie dürfen maximal 50 % des Grundkapitals ausmachen; Dividendenausfälle sind kumulativ nachzuzahlen.',
      'Sie haben zwingend volles Stimmrecht, aber keinen Anspruch auf eine Dividende.',
      'Sie sind stets frei übertragbare Inhaberaktien und können nicht mit Liquidationsvorteilen ausgestattet sein.',
    ],
    correctAnswer: 1,
    explanation: 'Das Topic nennt für Vorzugsaktien unter anderem maximal 50 % des Grundkapitals, kumulative Dividendennachzahlung und Sonderstimmrecht nach zwei Jahren Ausfall.',
  },
  {
    id: 'traditionelle-assetklassen-q07',
    type: 'single',
    question: 'Ein Unternehmen will die Eigentümerstruktur besser kontrollieren und Übernahmen erschweren. Welche Aktienform passt zur Logik des Topics am besten?',
    options: [
      'Inhaberaktien, weil Aktionäre nicht namentlich bekannt sind und die Fungibilität besonders hoch ist.',
      'Nennwertaktien, weil Unterpari-Emissionen bei Kapitalerhöhungen verboten sind.',
      'Stammaktien, weil sie immer ohne Stimmrecht ausgestaltet werden.',
      'Vinkulierte Namensaktien, weil Übertragungen nur mit Zustimmung der Gesellschaft erfolgen dürfen.',
    ],
    correctAnswer: 3,
    explanation: 'Namens- und besonders vinkulierte Namensaktien erhöhen den Übernahmeschutz, weil Eigentümer bekannt sind und Übertragungen genehmigt werden müssen.',
  },
  {
    id: 'traditionelle-assetklassen-q08',
    type: 'multiple',
    question: 'Welche Aussagen zu Nennwertaktien und Stückaktien sind korrekt?',
    options: [
      'Nennwertaktien haben einen festen Nennwert von mindestens EUR 1 oder einem Vielfachen davon.',
      'Stückaktien sind nennwertlos, repräsentieren aber einen gleichen Anteil am Grundkapital.',
      'Bei Stückaktien darf der rechnerische Anteil am Grundkapital EUR 1 nicht unterschreiten.',
      'Ein Unternehmen verwendet nach dem Topic gleichzeitig Nennwert- und Stückaktien, um die Fungibilität zu erhöhen.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die ersten drei Aussagen entsprechen dem Topic; dort steht außerdem, dass Unternehmen entweder Nennwert- oder Stückaktien verwenden.',
  },
  {
    id: 'traditionelle-assetklassen-q09',
    type: 'single',
    question: 'Welche Aussage zur Rechtsstellung bei Anleihen und Aktien ist korrekt?',
    options: [
      'Anleihekäufer sind Miteigentümer und können Unternehmensentscheidungen über die Hauptversammlung beeinflussen.',
      'Aktionäre sind Gläubiger mit begrenzter Laufzeit und Anspruch auf Rückzahlung zu festen Zeitpunkten.',
      'Anleihekäufer sind Gläubiger mit Forderungsrecht; Aktionäre sind Miteigentümer mit Beteiligungsrecht.',
      'Namensschuldverschreibungen sind frei übertragbar, während Inhaberschuldverschreibungen nur mit Zustimmung verkauft werden dürfen.',
    ],
    correctAnswer: 2,
    explanation: 'Das Topic grenzt Forderungsrechte der Anleihe von Beteiligungsrechten der Aktie ab; Namensschuldverschreibungen sind gerade nicht ohne Zustimmung übertragbar.',
  },
  {
    id: 'traditionelle-assetklassen-q10',
    type: 'multiple',
    question: 'Welche Zuordnungen zu klassischen Anleihetypen sind korrekt?',
    options: [
      'Festverzinsliche Anleihen: konstanter Kupon.',
      'Variabel verzinsliche Anleihen: Kuponanpassung an Referenzzinssätze.',
      'Nullkuponanleihen: keine laufenden Zinszahlungen, Ertrag aus Differenz zwischen Ausgabe- und Rückzahlungsbetrag.',
      'Nullkuponanleihen: meist kurze Laufzeiten von unter einem Jahr und laufender jährlicher Zinsdienst.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Topic unterscheidet konstanten Kupon, variablen Kupon und keine laufende Kuponzahlung; Nullkuponanleihen haben meist lange Laufzeiten von 10 bis 30 Jahren.',
  },
  {
    id: 'traditionelle-assetklassen-q11',
    type: 'single',
    question: 'Welche Aussage verbindet Kurs, Nominalzins und YTM korrekt?',
    options: [
      'Liegt der Kurs unter Pari, ist die YTM niedriger als der Nominalzins.',
      'Liegt der Kurs über Pari, ist die YTM höher als der Nominalzins.',
      'Liegt der Kurs bei Pari, entspricht die YTM dem Nominalzins.',
      'Die YTM ignoriert Stückzinsen und vergleicht nur Kupon und Nominalbetrag.',
    ],
    correctAnswer: 2,
    explanation: 'Das Topic ordnet zu: Kurs = Pari bedeutet YTM = Nominalzins; unter Pari liegt die YTM darüber, über Pari darunter.',
  },
  {
    id: 'traditionelle-assetklassen-q12',
    type: 'single',
    question: 'Welche Aussage kombiniert weitere Bondformen und Risiken korrekt?',
    options: [
      'Optionsanleihen verlieren nach Ausübung ihre Obligation vollständig; Wandelanleihen behalten dagegen immer Zins- und Tilgungsanspruch.',
      'Schuldscheindarlehen sind börsengehandelt, verlangen externes Rating und lassen sich deshalb besonders leicht vorzeitig verkaufen.',
      'Hybridanleihen sind immer besichert, besitzen kurze Laufzeiten und verbieten dem Emittenten das Aussetzen von Zinsen.',
      'Verlosungsanleihen können vorzeitig getilgt werden; dadurch kann ein Auslosungsrisiko mit Wiederanlagerisiken entstehen.',
    ],
    correctAnswer: 3,
    explanation: 'Bei Verlosungsanleihen werden Tranchen ausgelost und vorzeitig getilgt; das Topic nennt dazu Auslosungsrisiko und daraus folgende Wiederanlagerisiken.',
  },
  {
    id: 'alternative-assetklassen-q01',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welche Gruppe wird im Kapitel als alternative Assetklasse eingeordnet?',
    options: [
      'Geldmarktinstrumente, Währungen und klassische Anleihen.',
      'Immobilien, Hedge Funds, Rohstoffe, Volatilität und Sammlerstücke.',
      'Ausschließlich börsennotierte Aktien und Aktienfonds.',
      'Nur kurzfristige Bankeinlagen mit täglicher Preisstellung.',
    ],
    correctAnswer: 1,
    explanation: 'Kapitel 3 ordnet unter anderem Immobilien, Hedge Funds, Rohstoffe, Volatilität, Sammlerstücke und entsprechende Fonds den alternativen Assetklassen zu.',
  },
  {
    id: 'alternative-assetklassen-q02',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche Merkmale von Hedge Funds nennt das Topic?',
    options: [
      'Suche nach absoluter Performance unabhängig vom Gesamtmarkt.',
      'Sperr-, Kündigungs- und Rücknahmefristen.',
      'Hohe Freiheit beim Einsatz von Short Selling, Leverage, Derivaten und strukturierten Produkten.',
      'Strengere regulatorische Anforderungen als traditionelle Investmentfonds.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Topic nennt absolute Performance, eingeschränkte Rückgabemöglichkeiten und flexible Strategien; geringere, nicht strengere Regulierung wird genannt.',
  },
  {
    id: 'alternative-assetklassen-q03',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Wozu dient die direkte Beteiligung des Hedge-Fund-Managers laut Skriptlogik?',
    options: [
      'Sie reduziert Moral-Hazard-Risiken, weil Manager selbst am Ergebnis beteiligt sind.',
      'Sie ersetzt alle Rücknahmefristen für Anleger.',
      'Sie macht den Fonds automatisch marktneutral.',
      'Sie garantiert eine normale Renditeverteilung.',
    ],
    correctAnswer: 0,
    explanation: 'Die direkte Beteiligung des Managers wird als Mechanismus zur Reduzierung von Moral-Hazard-Risiken genannt.',
  },
  {
    id: 'alternative-assetklassen-q04',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche Formen des Anteilseigneraktivismus nennt das Topic?',
    options: [
      'Strategische Neuausrichtungen wie der Verkauf unrentabler Bereiche.',
      'Vermeidung unnötiger Kapitalbindung mit möglichen Dividendenerhöhungen oder Aktienrückkäufen.',
      'Drängen auf Abberufung von Vorstand oder Aufsichtsrat.',
      'Vollständiger Verzicht auf Einflussnahme bei schlechter Performance.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Aktive Finanzinvestoren können strategische, kapitalstrukturbezogene und personelle Änderungen anstoßen; passive Nicht-Einflussnahme ist gerade nicht der Punkt.',
  },
  {
    id: 'alternative-assetklassen-q05',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welche Zuordnung zu Hedge-Fund-Strategien ist korrekt?',
    options: [
      'Relative Value: Ausnutzung von Fehlbewertungen bei weitgehender Eliminierung von Marktrisiken.',
      'Event Driven: ausschließlich langfristiger Immobilienbestand mit stabilen Mietverträgen.',
      'Global Macro: nur risikolose Geldmarktanlage ohne Leverage.',
      'Equity Market Neutral: bewusster Aufbau einer hohen Netto-Long-Position.',
    ],
    correctAnswer: 0,
    explanation: 'Relative-Value-Strategien nutzen Fehlbewertungen und versuchen Marktrisiken weitgehend auszuschalten; Netto-Long passt eher zu Long-Short Equity in direktionaler Form.',
  },
  {
    id: 'alternative-assetklassen-q06',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche Aussagen zu Renditeeigenschaften von Hedge Funds sind korrekt?',
    options: [
      'Korrelationen sind im Zeitablauf nicht stabil.',
      'In schlechten Aktienmarktphasen kann die Korrelation zu Aktienmärkten vergleichsweise hoch sein.',
      'Viele Hedge-Fund-Renditen sind linksschief und besitzen fette Enden.',
      'Alle Hedge-Fund-Strategien liefern dauerhaft stabile risikoadjustierte Outperformance.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Topic warnt vor instabilen Korrelationen, Linksschiefe und fetten Enden; eine dauerhafte Outperformance aller Strategien wird nicht behauptet.',
  },
  {
    id: 'alternative-assetklassen-q07',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welches Argument spricht im Topic gegen Immobilien-Investments?',
    options: [
      'Tägliche transparente Marktpreise für jedes Objekt.',
      'Geringe Liquidität und Bewertungsprobleme.',
      'Keine Möglichkeit zur Segmentierung nach Region oder Nutzungsart.',
      'Fehlende laufende Cashflows durch Mieteinnahmen in jedem Fall.',
    ],
    correctAnswer: 1,
    explanation: 'Geringe Liquidität, hohe Kapitalbindung und Bewertungsprobleme werden als Gegenargumente genannt.',
  },
  {
    id: 'alternative-assetklassen-q08',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche indirekten Formen der Immobilienanlage nennt das Topic?',
    options: [
      'Geschlossene Immobilienfonds.',
      'Offene Immobilienfonds.',
      'Immobilienaktien und REITs.',
      'Ausschließlich der unmittelbare Erwerb einzelner Liegenschaften.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Geschlossene und offene Fonds sowie Immobilienaktien und REITs sind indirekte Immobilienanlagen; der unmittelbare Erwerb ist Direktanlage.',
  },
  {
    id: 'alternative-assetklassen-q09',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welche Beschreibung passt zu Core/Core-Plus-Immobilieninvestments?',
    options: [
      'Sehr hohes Risiko, 1-4 Jahre Haltedauer und strukturell komplexe Kurzfristmietverträge.',
      'Sehr geringes Risiko durch stabilen Cashflow, lange Haltedauer und Top-Lagen.',
      'Ausschließlich Sonderimmobilien mit hohem Investitionsstau.',
      'Kurzfristige Spekulation in illiquiden Märkten mit kaum prognostizierbaren Ungleichgewichten.',
    ],
    correctAnswer: 1,
    explanation: 'Core/Core Plus steht für sehr geringes Risiko, stabile Cashflows, langfristige Haltedauer, gute Mieterbasis und Top-Lagen.',
  },
  {
    id: 'alternative-assetklassen-q10',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche Aussagen zu Immobilienindizes und Smoothing sind korrekt?',
    options: [
      'Appraisal-Based-Indizes beruhen auf Schätzungen von Gutachtern.',
      'Transaction-Based-Indizes nutzen realisierte Transaktionspreise.',
      'Smoothing kann die gemessene Volatilität von Immobilienzeitreihen reduzieren.',
      'Immobilienaktienindizes sind vollständig unabhängig vom allgemeinen Aktienmarkt.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die ersten drei Aussagen entsprechen dem Topic; Immobilienaktien hängen auch von weiteren Aktienmarktfaktoren ab.',
  },
  {
    id: 'alternative-assetklassen-q11',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Was bedeutet Finanzialisierung von Rohstoffmärkten im Topic?',
    options: [
      'Finanzakteure spielen eine bedeutendere Rolle in den Preisbildungsmechanismen von Rohstoffmärkten.',
      'Rohstoffe können nur noch physisch von Privatanlegern gelagert werden.',
      'Alle Rohstoffpreise werden ausschließlich durch Zentralbanken festgelegt.',
      'Rohstoff-Futures verlieren jede Bedeutung für institutionelle Anleger.',
    ],
    correctAnswer: 0,
    explanation: 'Das Topic beschreibt die zunehmende Rolle von Finanzakteuren in der Preisbildung als Finanzialisierung.',
  },
  {
    id: 'alternative-assetklassen-q12',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche kurzfristigen Determinanten von Rohstoffpreisen nennt das Topic?',
    options: [
      'Angebot und Nachfrage, Kartelle, Rohstofffunde und Nachfrageschocks.',
      'Wechselkurse, Inflation und politische Risiken.',
      'Wetter-/Klimabedingungen, Naturkatastrophen, Transportkosten und Engpässe.',
      'Ausschließlich die historische Dividendenrendite börsennotierter Aktien.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Kurzfristige Rohstoffpreise werden im Topic durch Angebots-/Nachfragefaktoren, Wechselkurse, Inflation, politische Risiken, Wetter und Transportbedingungen beeinflusst.',
  },
  {
    id: 'alternative-assetklassen-q13',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welche Renditekomponente bei Rohstoff-Futures beschreibt die prozentuale Veränderung des Basisinstrumentkurses am Kassamarkt?',
    options: [
      'Collateral Yield.',
      'Spot Return.',
      'Rollrendite.',
      'High Water Mark.',
    ],
    correctAnswer: 1,
    explanation: 'Der Spot Return ist die prozentuale Veränderung des Kurses des Basisinstruments am Kassamarkt.',
  },
  {
    id: 'alternative-assetklassen-q14',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Welche Aussage zu Backwardation und Contango ist korrekt?',
    options: [
      'In Backwardation sind Futures-Kurse niedriger, je länger die Laufzeit ist; Long-Investoren können beim Rollen profitieren.',
      'In Contango sind längere Futures immer günstiger als nahe Futures.',
      'Backwardation bedeutet zwingend, dass keine Rollrendite existiert.',
      'Contango ist für Long-Investoren beim Rollen immer vorteilhaft.',
    ],
    correctAnswer: 0,
    explanation: 'Backwardation bedeutet fallende Futures-Kurse mit längerer Laufzeit; beim Rollen kann das für Long-Investoren eine positive Rollrendite erzeugen.',
  },
  {
    id: 'alternative-assetklassen-q15',
    topicId: 'alternative-assetklassen',
    type: 'multiple',
    question: 'Welche Aussagen zu Digital Assets und Blockchain entsprechen dem Topic?',
    options: [
      'Digitale Vermögenswerte werden nicht von Zentralbank oder öffentlicher Behörde ausgegeben oder garantiert.',
      'Blockchain verwaltet Daten ohne zentrale Instanz nachvollziehbar und manipulationssicher.',
      'Kryptowährungen erfüllen laut Topic derzeit alle ökonomischen Geldfunktionen vollständig.',
      'Kryptowertpapiere sind ein Sonderfall elektronischer Wertpapiere.',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Das Topic betont fehlende Zentralbankgarantie, Blockchain als dezentrale manipulationssichere Datenverwaltung und Kryptowertpapiere als Sonderfall; vollständige Geldfunktionserfüllung wird gerade verneint.',
  },
  {
    id: 'alternative-assetklassen-q16',
    topicId: 'alternative-assetklassen',
    type: 'single',
    question: 'Warum erfüllen Kryptowährungen laut Skript die Geldfunktionen derzeit noch nicht vollständig?',
    options: [
      'Vor allem wegen der enorm hohen Wertschwankung beziehungsweise Volatilität.',
      'Weil sie ausschließlich als physische Münzen existieren.',
      'Weil sie von Zentralbanken garantiert werden.',
      'Weil Blockchain-Daten zentral und beliebig veränderbar gespeichert werden.',
    ],
    correctAnswer: 0,
    explanation: 'Das Skript nennt insbesondere die enorm hohe Volatilität als Grund, warum Kryptowährungen die Geldfunktionen derzeit noch nicht erfüllen.',
  },
  {
    id: 'einfuehrung-q01',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie definiert Kapitel 1 Asset Management?',
    options: [
      'Die ausschließlich physische Verwahrung von Wertpapierurkunden ohne Anlageentscheidung.',
      'Die systematische Dienstleistung der professionellen Kapitalanlage mit dem Ziel, risikoeffiziente Portefeuilles zu bilden.',
      'Die staatliche Aufsicht über Banken, Versicherungen und Wertpapierhandel.',
      'Die einmalige Beratung eines Privatanlegers ohne fortlaufende Betreuung.',
    ],
    correctAnswer: 1,
    explanation: 'Das Topic definiert Asset Management als systematische Dienstleistung der professionellen Kapitalanlage mit dem Ziel risikoeffizienter Portefeuilles; Synonyme sind u. a. Portfolio-, Fonds-, Investment Management und Vermögensverwaltung.',
  },
  {
    id: 'einfuehrung-q02',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche vier Ziele bilden das magische Viereck der Kapitalanlage?',
    options: [
      'Rendite',
      'Risiko',
      'Liquidität',
      'Steuern',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Das magische Viereck spannt das Zielspannungsfeld aus Rendite, Risiko, Liquidität und Steuern auf; auf der Folie ist es als Aufzählung genannt, nicht als gezeichnetes Diagramm.',
  },
  {
    id: 'einfuehrung-q03',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche Aussage trennt klassisches und fondsgestütztes Asset Management korrekt?',
    options: [
      'Klassisches Asset Management ist breit gestreut und schon ab kleinem Vermögen möglich, fondsgestütztes ist teuer und individuell.',
      'Klassisches Asset Management ist individuell, aber teuer und wenig gestreut; fondsgestütztes bietet breite Streuung schon ab kleinem Vermögen, ist aber weniger individuell.',
      'Beide Formen sind hinsichtlich Kosten, Streuung und Individualität identisch.',
      'Fondsgestütztes Asset Management beruht auf einem individuellen Vermögensverwaltungsmandat ohne Streuung.',
    ],
    correctAnswer: 1,
    explanation: 'Klassisches Asset Management ist individuell, aber teuer und wenig gestreut; fondsgestütztes bietet breite Streuung schon ab kleinem Vermögen bei geringerer Individualität.',
  },
  {
    id: 'einfuehrung-q04',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Merkmale kennzeichnen institutionelle Anleger nach Kapitel 1?',
    options: [
      'Es handelt sich um eine juristische Person.',
      'Sie legen überwiegend fremde, von Dritten überlassene Mittel an.',
      'Sie unterliegen hohen gesetzlichen Restriktionen (z. B. KAGG, WpHG, KWG).',
      'Sie legen ausschließlich geringe Beträge ohne professionelles Research an.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Institutionelle Anleger sind juristische Personen mit i. d. R. hohen Anlagebeträgen, legen überwiegend fremde Mittel an und unterliegen hohen gesetzlichen Restriktionen; sie nutzen gerade professionelles Research.',
  },
  {
    id: 'einfuehrung-q05',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche Rollenverteilung im Fondsgeschäft beschreibt Kapitel 1 korrekt?',
    options: [
      'Die Depotbank steuert die Anlagepolitik, die KVG verwahrt das Sondervermögen.',
      'Die KVG steuert die Anlagepolitik des Sondervermögens, die Depotbank verwahrt es und überwacht die KVG.',
      'Die BaFin verwahrt das Sondervermögen und beschäftigt den Fondsmanager.',
      'Der Investor verwahrt das Sondervermögen und kontrolliert die KVG.',
    ],
    correctAnswer: 1,
    explanation: 'Die KVG steuert die Anlagepolitik des Sondervermögens durch Käufe und Verkäufe; die Depotbank verwahrt das Sondervermögen und überwacht die KVG.',
  },
  {
    id: 'einfuehrung-q06',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Worin unterscheiden sich klassische Anlageberatung und Finanzportfolioverwaltung?',
    options: [
      'Die klassische Anlageberatung verlangt eine Generalvollmacht, die Finanzportfolioverwaltung eine Einzelzustimmung.',
      'Die klassische Anlageberatung erfordert das Einverständnis des Kunden vor jedem Geschäft; die Finanzportfolioverwaltung beruht auf einer Generalvollmacht mit höheren EK-Anforderungen.',
      'Beide beruhen auf einer Generalvollmacht und unterscheiden sich nur im Namen.',
      'Die Finanzportfolioverwaltung holt vor jedem Geschäft das Kundeneinverständnis ein.',
    ],
    correctAnswer: 1,
    explanation: 'Die klassische Anlageberatung holt vor jedem Geschäft das Einverständnis des Kunden ein; die Finanzportfolioverwaltung beruht auf einer Generalvollmacht, für die die BaFin höhere EK-Richtlinien fordert.',
  },
  {
    id: 'einfuehrung-q07',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Aussagen zum Sondervermögen sind nach Kapitel 1 korrekt?',
    options: [
      'Es ist vom Vermögen der KVG abgetrennt und vor deren Zugriff bzw. dem ihrer Gläubiger geschützt.',
      'Sein Wert ist die Summe der mit dem aktuellen Rücknahmepreis bewerteten Anteilscheine.',
      'Es wird durch die Depotbank verwahrt.',
      'Es haftet für die Verbindlichkeiten der KVG gegenüber Dritten.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Sondervermögen ist abgetrennt und geschützt, wird durch die Depotbank verwahrt und mit dem aktuellen Rücknahmepreis bewertet; es haftet gerade nicht für KVG-Verbindlichkeiten.',
  },
  {
    id: 'einfuehrung-q08',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Auf welcher Rechtsgrundlage und in welcher Funktion handelt die BaFin nach Kapitel 1?',
    options: [
      'Auf Grundlage des WpHG ausschließlich als Versicherungsaufsicht.',
      'Auf Grundlage des Kreditwesengesetzes (KWG) als Allfinanzaufsicht über alle Bereiche des Finanzwesens.',
      'Als reine Steuerbehörde ohne Aufsicht über Banken.',
      'Als Aufsicht ausschließlich über Offshore-Gebiete.',
    ],
    correctAnswer: 1,
    explanation: 'Die BaFin handelt auf Grundlage des Kreditwesengesetzes als Allfinanzaufsicht über Banken, Versicherungen und Wertpapierhandel; die Pendants sind FMA (Österreich) und FINMA (Schweiz).',
  },
  {
    id: 'traditionelle-assetklassen-q13',
    topicId: 'traditionelle-assetklassen',
    type: 'multiple',
    question: 'Welche Aussagen zur Ratingskala von Moody’s und S&P treffen das Topic?',
    options: [
      'Die Ratingskala bewertet das Ausfallrisiko.',
      'Die Grenze zwischen Investment Grade und spekulativem Bereich liegt zwischen Baa3/BBB− und Ba1/BB+.',
      'Anlagen unterhalb von Baa3/BBB− gelten als Investment Grade.',
      'Bis Baa3/BBB− reicht der Investment-Grade-Bereich.',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Die Ratingskala misst das Ausfallrisiko; die dicke Grenze liegt zwischen Baa3/BBB− und Ba1/BB+ — darüber Investment Grade, darunter spekulativ.',
  },
  {
    id: 'traditionelle-assetklassen-q14',
    topicId: 'traditionelle-assetklassen',
    type: 'single',
    question: 'Warum weicht die versprochene Rendite (ytm) im Rechenbeispiel von der erwarteten Rendite ab?',
    options: [
      'Weil Stückzinsen ignoriert werden und der Kupon doppelt gezählt wird.',
      'Weil das Ausfallrisiko (PD und Recovery) die erwartete Verzinsung mindert; im Beispiel 18,9 % versprochen, aber 9,4 % erwartet.',
      'Weil die versprochene Rendite stets unter der erwarteten liegt.',
      'Weil die erwartete Rendite das Marktrisiko vollständig ausblendet.',
    ],
    correctAnswer: 1,
    explanation: 'Wegen des Ausfallrisikos überzeichnet die versprochene ytm den Ertrag; im Beispiel mit 20 % Ausfallwahrscheinlichkeit und 60 % Recovery ergibt sich eine versprochene ytm von 18,9 %, aber nur 9,4 % erwartet.',
  },
  {
    id: 'traditionelle-assetklassen-q15',
    topicId: 'traditionelle-assetklassen',
    type: 'single',
    question: 'Welche Abgrenzung von Wandel- und Optionsanleihe ist korrekt?',
    options: [
      'Bei der Wandelanleihe bleibt die Anleihe nach Wandlung bestehen, bei der Optionsanleihe erlischt sie.',
      'Bei der Wandelanleihe erlischt die Anleihe nach Wandlung (Gläubiger wird Aktionär); bei der Optionsanleihe bleibt die Anleihe bestehen und der Anleger erhält zusätzlich Aktien.',
      'Beide erlöschen nach Ausübung des Rechts vollständig.',
      'Beide bleiben nach Ausübung in jedem Fall bestehen.',
    ],
    correctAnswer: 1,
    explanation: 'Nach Wandlung erlischt die Wandelanleihe; bei der Optionsanleihe bleibt die Anleihe bestehen und der Anleger erhält zusätzlich Aktien.',
  },
  {
    id: 'traditionelle-assetklassen-q16',
    topicId: 'traditionelle-assetklassen',
    type: 'single',
    question: 'Wie ordnet das Topic die Hybridanleihe bilanziell und steuerlich ein?',
    options: [
      'Handelsbilanziell Fremdkapital, steuerrechtlich Eigenkapital.',
      'Handelsbilanziell Eigenkapital, steuerrechtlich Fremdkapital.',
      'In beiden Sichten ausschließlich Eigenkapital.',
      'In beiden Sichten ausschließlich Fremdkapital.',
    ],
    correctAnswer: 1,
    explanation: 'Hybridanleihen sind handelsbilanziell Eigenkapital, steuerrechtlich jedoch Fremdkapital — die beiden Einordnungen dürfen nicht gleichgesetzt werden.',
  },
  {
    id: 'mathemat-strat-grundlagen-q01',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Wann ist das geometrische Mittel das korrekte Renditemaß?',
    options: [
      'Bei durchschnittlichen Einperiodenrenditen ohne Wiederanlage.',
      'Bei mehrperiodiger Wiederanlage mit Zinseszinseffekten.',
      'Nur bei symmetrischen Verteilungen ohne Extremwerte.',
      'Ausschließlich bei stetigen, zeitadditiven Renditen.',
    ],
    correctAnswer: 1,
    explanation: 'Das geometrische Mittel berücksichtigt Zinseszinseffekte und ist der korrekte Durchschnitt bei Wiederanlage über mehrere Perioden; das arithmetische Mittel überschätzt dann die tatsächliche Wertentwicklung.',
  },
  {
    id: 'mathemat-strat-grundlagen-q02',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Im Folienbeispiel steigt ein Kapital um +100 % und fällt anschließend um −50 %. Welche Mittelwerte ergeben sich?',
    options: [
      'Arithmetisch 0 %, geometrisch +25 %.',
      'Arithmetisch +25 %, geometrisch 0 %.',
      'Beide ergeben +25 %.',
      'Beide ergeben 0 %.',
    ],
    correctAnswer: 1,
    explanation: 'Das arithmetische Mittel ergibt +25 % und suggeriert einen Gewinn; das geometrische Mittel ergibt 0 %, weil das Kapital wieder auf den Anfangswert zurückfällt.',
  },
  {
    id: 'mathemat-strat-grundlagen-q03',
    topicId: 'mathemat-strat-grundlagen',
    type: 'multiple',
    question: 'Welche Faktoren erhöhen nach Kapitel 4 die Zinssensitivität einer Anleihe?',
    options: [
      'Eine längere Restlaufzeit.',
      'Ein niedrigerer Coupon.',
      'Ein höherer Coupon.',
      'Die Eigenschaft als Nullkuponanleihe (Zero-Bond).',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Längere Laufzeit und niedriger Coupon erhöhen die Zinssensitivität; Zero-Bonds sind besonders zinssensitiv. Ein höherer Coupon erzeugt frühere Cashflows und senkt die Sensitivität.',
  },
  {
    id: 'mathemat-strat-grundlagen-q04',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Was leistet die Konvexität gegenüber der Modified Duration?',
    options: [
      'Sie ersetzt die Modified Duration vollständig durch eine lineare Näherung.',
      'Sie korrigiert die lineare Unterschätzung der Modified Duration über den Term 0,5 · C · (Δr)².',
      'Sie misst die Kapitalbindungsdauer in Jahren.',
      'Sie ist nur bei Kursen über pari relevant.',
    ],
    correctAnswer: 1,
    explanation: 'Die Kursänderung wird als −MD · Δr + 0,5 · C · (Δr)² approximiert; die Konvexität korrigiert die lineare Unterschätzung der Modified Duration, die nur für kleine Δr genügt.',
  },
  {
    id: 'mathemat-strat-grundlagen-q05',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Wie wird eine tägliche Standardabweichung nach der Wurzel-Zeit-Regel annualisiert (250 Handelstage)?',
    options: [
      'σ_ann = 250 · σ_d',
      'σ_ann = √250 · σ_d',
      'σ_ann = σ_d / √250',
      'σ_ann = σ_d / 250',
    ],
    correctAnswer: 1,
    explanation: 'Die Volatilität wird über die Wurzel-Zeit-Regel annualisiert: σ_ann = √250 · σ_d.',
  },
  {
    id: 'mathemat-strat-grundlagen-q06',
    topicId: 'mathemat-strat-grundlagen',
    type: 'multiple',
    question: 'Welche Aussagen zu Schiefe und Wölbung realer Assetrenditen sind korrekt?',
    options: [
      'Reale Assetrenditen sind häufig linksschief (Schiefe negativ).',
      'Reale Assetrenditen sind häufig leptokurtisch (Kurtosis größer als 3).',
      'Bei Kurtosis größer als 3 unterschätzt ein reines μ-σ-Kalkül das Risiko systematisch.',
      'Eine Normalverteilung hat eine Kurtosis von 0.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Reale Renditen sind meist linksschief und leptokurtisch (Fat Tails); dann unterschätzt das μ-σ-Kalkül das Risiko. Die Normalverteilung hat eine Kurtosis von 3, nicht 0.',
  },
  {
    id: 'mathemat-strat-grundlagen-q07',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Welche Aussage zum Value-at-Risk ist nach Kapitel 4 korrekt?',
    options: [
      'Der VaR beschreibt den maximal möglichen Verlust eines Portfolios.',
      'Der VaR ist der Verlust, der mit gegebener Wahrscheinlichkeit über einen Zeithorizont nicht überschritten wird; der tatsächliche Verlust kann größer sein.',
      'Der VaR ist unabhängig vom gewählten Konfidenzniveau.',
      'Der VaR kann nicht über die Zeit skaliert werden.',
    ],
    correctAnswer: 1,
    explanation: 'Der VaR ist der Verlust, der mit gegebener Wahrscheinlichkeit über einen Zeithorizont nicht überschritten wird — kein Maximalverlust; er skaliert über die Wurzel-Zeit-Regel und steigt mit dem Konfidenzniveau.',
  },
  {
    id: 'mathemat-strat-grundlagen-q08',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Welche z-Werte nennt Kapitel 4 für die parametrische VaR-Berechnung?',
    options: [
      'z_95% = 1,282 und z_99% = 1,645',
      'z_95% = 1,645 und z_99% = 2,326',
      'z_95% = 1,960 und z_99% = 2,576',
      'z_95% = 2,326 und z_99% = 1,645',
    ],
    correctAnswer: 1,
    explanation: 'Das Topic nennt für den Varianz-Kovarianz-Ansatz z_95% = 1,645 und z_99% = 2,326.',
  },
  {
    id: 'mathemat-strat-grundlagen-q09',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Welchen Wertebereich nimmt der Korrelationskoeffizient an und wie wirkt er auf die Diversifikation?',
    options: [
      'Zwischen 0 und 1; nur bei genau 0 entsteht Diversifikation.',
      'Zwischen −1 und +1; je niedriger die Korrelation, desto größer der Diversifikationseffekt.',
      'Zwischen −1 und +1; je höher die Korrelation, desto größer der Diversifikationseffekt.',
      'Unbegrenzt; die Korrelation hat keinen Einfluss auf die Diversifikation.',
    ],
    correctAnswer: 1,
    explanation: 'Die Korrelation normiert die Kovarianz auf den Bereich −1 bis +1; je niedriger die Korrelation, desto größer der Diversifikationseffekt. Reale Korrelationen schwanken und steigen in Krisen.',
  },
  {
    id: 'mathemat-strat-grundlagen-q10',
    topicId: 'mathemat-strat-grundlagen',
    type: 'single',
    question: 'Warum sind stetige Renditen über die Zeit mit dem arithmetischen Mittel zu mitteln?',
    options: [
      'Weil sie multiplikativ verknüpft sind und Zinseszins enthalten.',
      'Weil sie zeitadditiv sind und über die e-Funktion bzw. den natürlichen Logarithmus umgerechnet werden.',
      'Weil sie immer höher sind als diskrete Renditen.',
      'Weil sie nur in Krisen verwendet werden dürfen.',
    ],
    correctAnswer: 1,
    explanation: 'Stetige Renditen sind zeitadditiv (umrechenbar über e-Funktion und natürlichen Logarithmus) und daher mit dem arithmetischen — nicht dem geometrischen — Mittel zu mitteln.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q01',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'multiple',
    question: 'Welche Inputgrößen bestimmen nach Markowitz die Rendite-Risiko-Kombination eines Portfolios?',
    options: [
      'Die erwarteten Renditen der Einzelanlagen.',
      'Die Volatilitäten der Einzelanlagen als Risikomaß.',
      'Die Korrelationen bzw. Kovarianzen zwischen den Anlagen.',
      'Die Rechtsform der Emittenten der Einzelanlagen.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Markowitz kombiniert erwartete Renditen, Volatilitäten und Korrelationen/Kovarianzen; die Rechtsform der Emittenten ist keine Inputgröße der Portfoliotheorie.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q02',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Wodurch entsteht laut Kapitel 5 der Diversifikationseffekt?',
    options: [
      'Allein durch eine möglichst große Anzahl gehaltener Wertpapiere.',
      'Dadurch, dass die Renditen der Anlagen nicht perfekt positiv korreliert sind.',
      'Dadurch, dass alle Anlagen perfekt positiv korreliert sind.',
      'Dadurch, dass ausschließlich systematisches Risiko gehalten wird.',
    ],
    correctAnswer: 1,
    explanation: 'Diversifikation entsteht, wenn die Anlagen nicht perfekt positiv korreliert sind; bei ρ = +1 addiert sich das Risiko linear und es entsteht kein Effekt.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q03',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Welche Aussage zum Minimum-Varianz-Portfolio (MVP) und zum effizienten Rand ist korrekt?',
    options: [
      'Die gesamte Minimum-Varianz-Kurve ist effizient.',
      'Nur der positiv geneigte Bereich oberhalb des MVP ist der effiziente Rand.',
      'Das MVP liegt stets oberhalb des effizienten Randes.',
      'Der effiziente Rand liegt unterhalb des MVP.',
    ],
    correctAnswer: 1,
    explanation: 'Das MVP markiert den Risikominimum-Punkt; effizient ist nur der positiv geneigte Bereich oberhalb des MVP.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q04',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'multiple',
    question: 'Welche Aussagen zu systematischem und unsystematischem Risiko sind korrekt?',
    options: [
      'Systematisches Risiko (Marktrisiko) ist nicht diversifizierbar.',
      'Unsystematisches Risiko kann in großen Portfolios wegdiversifiziert werden.',
      'Nur systematisches Risiko wird durch eine Risikoprämie entlohnt.',
      'Unsystematisches Risiko wird im CAPM über Beta entlohnt.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Systematisches Risiko ist nicht diversifizierbar und wird allein entlohnt; unsystematisches Risiko ist wegdiversifizierbar und wird nicht entlohnt.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q05',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Was besagt die Tobin-Separation?',
    options: [
      'Sie trennt systematisches von unsystematischem Risiko anhand des Betas.',
      'Sie trennt die Anlageentscheidung (Wahl des Tangentialportfolios) von der Finanzierungsentscheidung (Mischung mit dem risikolosen Asset).',
      'Sie trennt Kurs- von Performanceindizes.',
      'Sie trennt aktives von passivem Management.',
    ],
    correctAnswer: 1,
    explanation: 'Die Tobin-Separation trennt die Anlageentscheidung (Tangentialportfolio) von der individuellen Finanzierungsentscheidung (Mischung mit dem risikolosen Asset).',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q06',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Ein Wertpapier hat rF = 3 %, E(rM) = 10 % und β = 1,4. Welche erwartete Rendite ergibt das CAPM?',
    options: [
      '9,8 %',
      '12,8 %',
      '14,0 %',
      '7,0 %',
    ],
    correctAnswer: 1,
    explanation: 'E(r) = rF + β · [E(rM) − rF] = 3 % + 1,4 · (10 % − 3 %) = 3 % + 9,8 % = 12,8 %.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q07',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Worin unterscheiden sich Capital Market Line (CML) und Security Market Line (SML)?',
    options: [
      'Die CML nutzt Beta als x-Achse, die SML die Standardabweichung.',
      'Die CML arbeitet mit σ und gilt nur für effiziente Portfolios; die SML arbeitet mit Beta und gilt für alle Assets und Portfolios.',
      'Beide arbeiten identisch mit Beta auf der x-Achse.',
      'Die SML gilt nur für effiziente Portfolios, die CML für alle Assets.',
    ],
    correctAnswer: 1,
    explanation: 'Die CML arbeitet im μ-σ-Raum und gilt nur für effiziente Portfolios; die SML arbeitet im μ-β-Raum und gilt für alle Assets und Portfolios. Beide schneiden die Renditeachse bei rF.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q08',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'multiple',
    question: 'Welche Faktormodell-Typen unterscheidet Kapitel 5 im Rahmen der Multifaktormodelle?',
    options: [
      'Makroökonomische Faktormodelle.',
      'Fundamentalfaktormodelle (z. B. KBV, KGV).',
      'Statistische Faktormodelle.',
      'Geografische Zinsstrukturmodelle.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Multifaktormodelle gliedern sich in makroökonomische, fundamentale und statistische Faktormodelle; geografische Zinsstrukturmodelle sind kein im Topic genannter Typ.',
  },
  {
    id: 'grundlagen-der-portfoliotheorie-q09',
    topicId: 'grundlagen-der-portfoliotheorie',
    type: 'single',
    question: 'Welche Annahme ist eine zentrale Voraussetzung der Arbitrage Pricing Theory (APT)?',
    options: [
      'Ein beobachtbares Marktportfolio muss vorliegen.',
      'Es dürfen keine Arbitragemöglichkeiten bestehen.',
      'Alle Renditen müssen normalverteilt sein.',
      'Es darf nur einen einzigen Risikofaktor geben.',
    ],
    correctAnswer: 1,
    explanation: 'Die APT setzt ein Faktormodell, wohl diversifizierte Portfolios und vor allem die Abwesenheit von Arbitragemöglichkeiten voraus; ein beobachtbares Marktportfolio ist gerade nicht nötig.',
  },
  {
    id: 'portfoliomanagement-q01',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Welche Reihenfolge beschreibt den zyklischen Investmentprozess nach Kapitel 6 korrekt?',
    options: [
      'Finanzcontrolling → SAA → Investmentziele → PM i.e.S.',
      'Investmentziele → Strategische Asset Allocation → Portfoliomanagement i.e.S. → Finanzcontrolling.',
      'SAA → TAA → Rebalancing → Reporting.',
      'Investmentziele → Finanzcontrolling → SAA → PM i.e.S.',
    ],
    correctAnswer: 1,
    explanation: 'Der Investmentprozess verläuft zyklisch: Investmentziele, Strategische Asset Allocation, Portfoliomanagement i.e.S. und Finanzcontrolling; SAA und PM i.e.S. bilden den Asset-Allocation-Prozess.',
  },
  {
    id: 'portfoliomanagement-q02',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Welche Ziele bilden das magische Dreieck der Anlageziele?',
    options: [
      'Rendite, Risiko und Steuern.',
      'Rendite, Sicherheit und Liquidität.',
      'Rendite, Liquidität und Diversifikation.',
      'Sicherheit, Steuern und Inflation.',
    ],
    correctAnswer: 1,
    explanation: 'Das magische Dreieck der Anlageziele besteht aus Rendite, Sicherheit und Liquidität und beschreibt den grundlegenden Zielkonflikt.',
  },
  {
    id: 'portfoliomanagement-q03',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Wie unterscheidet sich der Absolute-Return- vom Relative-Return-Ansatz?',
    options: [
      'Absolute Return zielt auf Outperformance gegenüber einer Benchmark, Relative Return auf eine marktunabhängige Rendite.',
      'Absolute Return zielt auf eine positive Rendite unabhängig vom Markt, Relative Return ist benchmark- bzw. peer-group-bezogen.',
      'Beide Ansätze sind benchmarkbezogen und unterscheiden sich nur im Namen.',
      'Absolute Return verzichtet vollständig auf jede Risikosteuerung.',
    ],
    correctAnswer: 1,
    explanation: 'Der Absolute-Return-Ansatz zielt auf eine positive Rendite unabhängig vom Markt; der Relative-Return-Ansatz orientiert sich an einer Benchmark oder Peer Group.',
  },
  {
    id: 'portfoliomanagement-q04',
    topicId: 'portfoliomanagement',
    type: 'multiple',
    question: 'Welche Aussagen zur Strategischen Asset Allocation (SAA) sind korrekt?',
    options: [
      'Sie hat langfristigen Zeithorizont.',
      'Sie verteilt das Kapital auf Assetklassen, Länder und Währungen.',
      'Sie hat empirisch den größten Einfluss auf die Performance.',
      'Sie wählt vorrangig einzelne Branchen und Titel kurzfristig aus.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die SAA ist langfristig, verteilt auf Assetklassen, Länder und Währungen und hat empirisch den größten Performanceeinfluss; die Auswahl von Branchen und Einzeltiteln ist Aufgabe der TAA.',
  },
  {
    id: 'portfoliomanagement-q05',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Welche Aussage zum empirischen Befund von Brinson, Hood & Beebower (1986) ist korrekt?',
    options: [
      'Die Einzeltitelauswahl erklärt rund 91,5 % der Varianz der Portfolioperformance.',
      'Die Asset Allocation erklärt rund 91,5 % der Varianz der Portfolioperformance.',
      'Das Markowitz-Modell erklärt 100 % der Renditehöhe.',
      'Die Taktische Asset Allocation erklärt rund 91,5 % der Renditehöhe.',
    ],
    correctAnswer: 1,
    explanation: 'Empirisch erklärt die Asset Allocation rund 91,5 % der Varianz (Schwankung) der Portfolioperformance — die Aussage betrifft die Varianz, nicht die Renditehöhe.',
  },
  {
    id: 'portfoliomanagement-q06',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Worin unterscheiden sich Portfolio Rebalancing und Portfolio Upgrading?',
    options: [
      'Rebalancing verändert die Zielstruktur bewusst, Upgrading stellt die alte Struktur wieder her.',
      'Rebalancing stellt die ursprüngliche Zielstruktur wieder her; Upgrading verändert die Struktur bewusst aufgrund neuer Informationen.',
      'Beide bezeichnen denselben Vorgang.',
      'Rebalancing ist eine aktive, Upgrading eine rein passive Maßnahme.',
    ],
    correctAnswer: 1,
    explanation: 'Rebalancing ist die passive Rückkehr zur Ausgangsstruktur nach Kursverschiebungen; Upgrading verändert die Struktur bewusst aufgrund neuer Informationen oder Erwartungen.',
  },
  {
    id: 'portfoliomanagement-q07',
    topicId: 'portfoliomanagement',
    type: 'multiple',
    question: 'Welche Faktoren erhöhen nach Kapitel 6 den Bid-Ask-Spread?',
    options: [
      'Ein höheres Risiko der Aktie.',
      'Ein niedrigeres absolutes Preisniveau der Aktie.',
      'Höhere Liquidität des Marktsegments.',
      'Steigende Informationstransparenz des Titels.',
    ],
    correctAnswers: [0, 1],
    explanation: 'Höheres Risiko und ein niedrigeres absolutes Preisniveau erhöhen den Spread; höhere Liquidität und steigende Informationstransparenz verengen ihn.',
  },
  {
    id: 'portfoliomanagement-q08',
    topicId: 'portfoliomanagement',
    type: 'single',
    question: 'Warum reicht das reine Markowitz-Modell für institutionelle Investoren nicht aus?',
    options: [
      'Weil es Korrelationen vollständig ignoriert.',
      'Weil Nebenbedingungen wie Liquidität, Wettbewerbsrenditen, Finanzstärke und gesetzliche Rahmen (z. B. VAG) unberücksichtigt bleiben.',
      'Weil es nur für Privatanleger mathematisch definiert ist.',
      'Weil es ausschließlich systematisches Risiko erfasst.',
    ],
    correctAnswer: 1,
    explanation: 'Für institutionelle Investoren sind Nebenbedingungen wie Liquiditätspflichten, Wettbewerbsrenditen, Finanzstärke und gesetzliche Vorgaben bindend, die das reine Markowitz-Modell nicht abbildet.',
  },
  {
    id: 'performanceanalyse-q01',
    topicId: 'performanceanalyse',
    type: 'multiple',
    question: 'Welche drei Säulen bilden nach Kapitel 7 das Finanzcontrolling?',
    options: [
      'Performanceanalyse',
      'Risikoanalyse',
      'Reporting',
      'Strategische Asset Allocation',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Das Finanzcontrolling besteht aus Performanceanalyse, Risikoanalyse und Reporting; die Strategische Asset Allocation gehört zum Investmentprozess, nicht zu den Säulen des Controllings.',
  },
  {
    id: 'performanceanalyse-q02',
    topicId: 'performanceanalyse',
    type: 'single',
    question: 'Welche Aussage zur geldgewichteten (MWR) und zeitgewichteten Rendite (TWR) ist korrekt?',
    options: [
      'Die MWR misst nur das Marktgeschehen, die TWR berücksichtigt das Timing.',
      'Die MWR ist der interne Zinsfuß des Zahlungsstroms und erfasst Timing und Markt; die TWR ist die geometrische Durchschnittsrendite und misst nur das Marktgeschehen.',
      'Beide Maße sind identisch, sofern keine Steuern anfallen.',
      'Die TWR ist der interne Zinsfuß, die MWR die geometrische Durchschnittsrendite.',
    ],
    correctAnswer: 1,
    explanation: 'Die MWR ist der interne Zinsfuß und erfasst Timing plus Markt; die TWR ist die geometrische Durchschnittsrendite und misst nur das Marktgeschehen (GIPS-Standard).',
  },
  {
    id: 'performanceanalyse-q03',
    topicId: 'performanceanalyse',
    type: 'single',
    question: 'Wie ist ein Vergleich MWR < TWR zu interpretieren?',
    options: [
      'Günstiges Ein-/Auszahlungs-Timing des Investors.',
      'Ungünstiges Ein-/Auszahlungs-Timing des Investors.',
      'Ein Rechenfehler, da MWR nie kleiner als TWR sein kann.',
      'Ein vollständig diversifiziertes Portfolio.',
    ],
    correctAnswer: 1,
    explanation: 'MWR kleiner als TWR bedeutet ungünstiges Timing der Ein- und Auszahlungen; MWR größer als TWR günstiges Timing.',
  },
  {
    id: 'performanceanalyse-q04',
    topicId: 'performanceanalyse',
    type: 'multiple',
    question: 'Welche Zuordnung von risikoadjustiertem Maß und Risikogröße ist korrekt?',
    options: [
      'Sharpe-Ratio misst die Überschussrendite je Einheit Gesamtrisiko (σ).',
      'Treynor-Ratio misst die Überschussrendite je Einheit systematisches Risiko (β).',
      'Jensen-Alpha ist die absolute Über-/Unterrendite gegenüber der CAPM-erwarteten Rendite.',
      'Sharpe-Ratio misst die Überschussrendite je Einheit Beta.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Sharpe nutzt das Gesamtrisiko σ, Treynor das systematische Risiko β, und das Jensen-Alpha misst die absolute Über-/Unterrendite gegenüber der CAPM-Erwartung.',
  },
  {
    id: 'performanceanalyse-q05',
    topicId: 'performanceanalyse',
    type: 'single',
    question: 'Warum können sich Sharpe- und Treynor-Ranking eines Portfolios widersprechen?',
    options: [
      'Weil die Treynor-Ratio die Überschussrendite ignoriert.',
      'Weil ein schlecht diversifiziertes Portfolio (hohes unsystematisches Risiko) nach Treynor (β) besser abschneidet als nach Sharpe (σ).',
      'Weil die Sharpe-Ratio nur für Anleihen gilt.',
      'Weil beide Maße dasselbe Risikomaß verwenden.',
    ],
    correctAnswer: 1,
    explanation: 'Ist ein Portfolio schlecht diversifiziert, trägt es viel unsystematisches Risiko; dann schneidet es nach Treynor (β) besser ab als nach Sharpe (σ), und die Rankings widersprechen sich.',
  },
  {
    id: 'performanceanalyse-q06',
    topicId: 'performanceanalyse',
    type: 'single',
    question: 'Wie ist das Jensen-Alpha grafisch zu deuten?',
    options: [
      'Als Steigung der Wertpapierlinie (SML).',
      'Als vertikaler Abstand der tatsächlichen Portfoliorendite zur CAPM-/SML-Linie; α > 0 bedeutet Outperformance.',
      'Als horizontaler Abstand zum risikolosen Zins.',
      'Als Fläche unter der Capital Market Line.',
    ],
    correctAnswer: 1,
    explanation: 'Das Jensen-Alpha ist der vertikale Abstand der tatsächlichen Rendite zur SML bzw. der Achsenabschnitt der Regression von r_P auf r_BM; α > 0 bedeutet Outperformance.',
  },
  {
    id: 'performanceanalyse-q07',
    topicId: 'performanceanalyse',
    type: 'single',
    question: 'Warum erlaubt das Jensen-Alpha — anders als Sharpe und Treynor — kein einwandfreies Ranking?',
    options: [
      'Weil es die Benchmark nicht berücksichtigt.',
      'Weil das zur Alpha-Erzielung eingegangene Risiko unberücksichtigt bleibt.',
      'Weil es ein reines Renditemaß ohne Bezug zur Benchmark ist.',
      'Weil es nur für nicht-normalverteilte Renditen gilt.',
    ],
    correctAnswer: 1,
    explanation: 'Das Jensen-Alpha ist ein absolutes Maß; ein hohes Alpha kann mit deutlich mehr Risiko erkauft sein, das es allein nicht abbildet — daher kein sauberes Ranking.',
  },
  {
    id: 'performanceanalyse-q08',
    topicId: 'performanceanalyse',
    type: 'multiple',
    question: 'Welche Voraussetzungen bzw. Grenzen nennt Kapitel 7 für die Sharpe-Ratio?',
    options: [
      'Sie ist nur bei normalverteilten Renditen sinnvoll.',
      'Sie setzt μ_P größer r_f voraus.',
      'Der Vergleich ist nur bei gleichem regionalen Exposure aussagekräftig.',
      'Sie ist besonders gut für asymmetrische Optionsrenditen geeignet.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Sharpe-Ratio setzt Normalverteilung und μ_P > r_f voraus und ist nur bei gleichem regionalen Exposure vergleichbar; bei asymmetrischen Optionsrenditen ist sie gerade nicht ohne Anpassung geeignet.',
  },
  {
    id: 'aktives-vs-passives-management-q01',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Welche Markteffizienz-Annahme liegt aktivem bzw. passivem Management zugrunde?',
    options: [
      'Aktiv unterstellt effiziente Märkte, passiv nicht-effiziente Märkte.',
      'Aktiv unterstellt nicht-effiziente Märkte und zielt auf Alpha; passiv unterstellt effiziente Märkte und bildet kostenminimal einen Index nach.',
      'Beide unterstellen effiziente Märkte.',
      'Beide unterstellen nicht-effiziente Märkte.',
    ],
    correctAnswer: 1,
    explanation: 'Aktives Management unterstellt nicht-effiziente Märkte und zielt auf Alpha; passives Management unterstellt effiziente Märkte und bildet kostenminimal einen Index nach.',
  },
  {
    id: 'aktives-vs-passives-management-q02',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Welche Rolle spielt die Benchmark im aktiven gegenüber dem passiven Management?',
    options: [
      'Im passiven Management ist sie das zu schlagende Portfolio, im aktiven das Zielportfolio.',
      'Im passiven Management ist sie das zu replizierende Zielportfolio, im aktiven das zu schlagende Portfolio.',
      'In beiden Fällen ist sie das zu schlagende Portfolio.',
      'In beiden Fällen ist sie irrelevant.',
    ],
    correctAnswer: 1,
    explanation: 'Im passiven Management ist die Benchmark das zu replizierende Zielportfolio; im aktiven Management ist sie das durch Über-/Untergewichtungen zu schlagende Portfolio.',
  },
  {
    id: 'aktives-vs-passives-management-q03',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Was kennzeichnet tilted Management als Mischform?',
    options: [
      'Eine vollständig prognosefreie reine Indexnachbildung.',
      'Eine ausgehend vom passiven Portfolio gezielte Abweichung nach ausgewählten Risikofaktoren, umsetzbar als Core-Satellite-Strategie.',
      'Eine ausschließlich aktive Einzeltitelselektion ohne passiven Kern.',
      'Eine Strategie, die nur in Geldmarktinstrumente investiert.',
    ],
    correctAnswer: 1,
    explanation: 'Tilted Management weicht ausgehend vom passiven Portfolio gezielt nach ausgewählten Risikofaktoren ab und ist als Core-Satellite-Strategie umsetzbar.',
  },
  {
    id: 'aktives-vs-passives-management-q04',
    topicId: 'aktives-vs-passives-management',
    type: 'multiple',
    question: 'Welche Anforderungen muss ein Index erfüllen, um investierbar zu sein?',
    options: [
      'Nachbildbarkeit.',
      'Liquidität der enthaltenen Titel.',
      'Transparenz bei Auswahl und Gewichtung.',
      'Garantierte Outperformance gegenüber dem Gesamtmarkt.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Ein investierbarer Index muss nachbildbar, liquide und transparent sein; eine garantierte Outperformance ist keine Indexanforderung.',
  },
  {
    id: 'aktives-vs-passives-management-q05',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Welche Aussage zum Rechenbeispiel preis- vs. kapitalisierungsgewichteter Index ist korrekt?',
    options: [
      'Der preisgewichtete Index steigt um 14,5 %, der kapitalisierungsgewichtete um 9,2 %.',
      'Der preisgewichtete Index steigt um 9,2 % (arithmetisches Mittel der Kurse), der kapitalisierungsgewichtete um 14,5 %.',
      'Beide Indizes steigen um exakt 12 %.',
      'Der preisgewichtete Index ist das Mittel der Marktwerte, nicht der Kurse.',
    ],
    correctAnswer: 1,
    explanation: 'Im Beispiel steigt der preisgewichtete Index (arithmetisches Mittel der Kurse) um 9,2 %, der kapitalisierungsgewichtete um 14,5 %.',
  },
  {
    id: 'aktives-vs-passives-management-q06',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Worin unterscheiden sich Kurs- und Performanceindex?',
    options: [
      'Der Kursindex reinvestiert Dividenden, der Performanceindex nicht.',
      'Der Performanceindex (Total Return) reinvestiert Dividenden, der Kursindex nicht.',
      'Beide reinvestieren Dividenden in gleicher Weise.',
      'Der Kursindex enthält ausschließlich Anleihen.',
    ],
    correctAnswer: 1,
    explanation: 'Nur der Performanceindex (Total Return, z. B. DAX) reinvestiert Dividenden; der Kursindex (z. B. DJIA) tut dies nicht, sodass die Opportunitätskosten über lange Horizonte steigen.',
  },
  {
    id: 'aktives-vs-passives-management-q07',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Welcher Unterschied besteht beim Insolvenzrisiko zwischen ETFs/Indexfonds und Indexzertifikaten?',
    options: [
      'ETFs und Indexfonds tragen ein Totalverlustrisiko, Indexzertifikate sind Sondervermögen.',
      'ETFs und Indexfonds sind insolvenzgeschütztes Sondervermögen, Indexzertifikate sind Schuldverschreibungen mit Totalverlustrisiko.',
      'Alle drei sind Schuldverschreibungen mit Totalverlustrisiko.',
      'Alle drei sind insolvenzgeschütztes Sondervermögen.',
    ],
    correctAnswer: 1,
    explanation: 'Indexfonds und ETFs sind insolvenzgeschütztes Sondervermögen; Indexzertifikate sind Schuldverschreibungen mit Totalverlustrisiko.',
  },
  {
    id: 'aktives-vs-passives-management-q08',
    topicId: 'aktives-vs-passives-management',
    type: 'multiple',
    question: 'Welche Aussagen zur Empirie und zum Tracking-Error sind korrekt?',
    options: [
      'Über fast alle Aktien-Kategorien schlägt nur eine Minderheit aktiver Fonds die Benchmark.',
      'Aktives Management ist vor Kosten ein Nullsummenspiel.',
      'Der Tracking-Error ist die Volatilität der Renditedifferenz zwischen Portfolio und Benchmark.',
      'Der Tracking-Error ist eine bewusst gewählte aktive Strategie.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Empirisch schlägt nur eine Minderheit aktiver Fonds die Benchmark, und aktives Management ist vor Kosten ein Nullsummenspiel; der Tracking-Error ist die Volatilität der Renditedifferenz und ein unbeabsichtigtes Nachbildungsrisiko, keine aktive Strategie.',
  },
  {
    id: 'aktives-vs-passives-management-q09',
    topicId: 'aktives-vs-passives-management',
    type: 'single',
    question: 'Was beschreibt der Market Cap Bias am Beispiel des MSCI World?',
    options: [
      'Eine Gleichgewichtung aller Titel unabhängig von der Marktkapitalisierung.',
      'Die Dominanz weniger großer Werte durch Kapitalisierungsgewichtung; der US-Anteil stieg von 59,21 % (2018) auf 71,91 % (2026).',
      'Eine vollständige Unabhängigkeit des Index vom US-Markt.',
      'Eine abnehmende Konzentration über die Zeit.',
    ],
    correctAnswer: 1,
    explanation: 'Kapitalisierungsgewichtung erzeugt einen Market Cap Bias: wenige große US-Tech-Werte dominieren, und die Konzentration nimmt zu (US-Anteil 59,21 % → 71,91 %, IT-Anteil bis 27,61 %).',
  },
  {
    id: 'fintechs-im-asset-management-q01',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'Woraus setzt sich der Begriff FinTech zusammen und wann entstand der moderne FinTech-Begriff?',
    options: [
      'Aus „Finance" und „Technik"; entstanden in den 1990er Jahren.',
      'Aus „Financial Services" und „Technology"; der moderne Begriff entstand mit der Finanzkrise 2008.',
      'Aus „Final Technology"; entstanden mit dem ersten transatlantischen Kabel.',
      'Aus „Fonds" und „Technologie"; entstanden 1918 mit Fedwire.',
    ],
    correctAnswer: 1,
    explanation: 'FinTech setzt sich aus Financial Services und Technology zusammen; der moderne FinTech-Begriff entstand mit der Finanzkrise 2008, auch wenn die technischen Wurzeln weiter zurückreichen.',
  },
  {
    id: 'fintechs-im-asset-management-q02',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'In welchem FinTech-Segment ist Robo-Advice verortet?',
    options: [
      'Im Segment Zahlungsverkehr.',
      'Im Segment Vermögensverwaltung.',
      'Im Segment Finanzierung.',
      'Im Segment Sonstige FinTechs.',
    ],
    correctAnswer: 1,
    explanation: 'Robo-Advice ist dem FinTech-Segment Vermögensverwaltung zugeordnet (neben Social Trading, Personal Financial Management sowie Anlage & Banking).',
  },
  {
    id: 'fintechs-im-asset-management-q03',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'Welche Aussage zur extensiven Komplexität ist korrekt?',
    options: [
      'Sie betrifft die Komplexität innerhalb einer einzelnen Person und hängt stark von makroökonomischen Größen ab.',
      'Sie betrifft die Komplexität zwischen Personen und hängt nicht von makroökonomischen Größen ab, da diese für alle Marktteilnehmer gleich sind.',
      'Sie ist identisch mit der intensiven Komplexität.',
      'Sie wird durch Robo Advisory vollständig beseitigt.',
    ],
    correctAnswer: 1,
    explanation: 'Die extensive Komplexität (zwischen Personen) ist von makroökonomischen Größen unabhängig, weil diese für alle Marktteilnehmer gleich sind; bei der intensiven Komplexität wirken sie dagegen mit.',
  },
  {
    id: 'fintechs-im-asset-management-q04',
    topicId: 'fintechs-im-asset-management',
    type: 'multiple',
    question: 'Welche Defizite des traditionellen Asset Managements nennt Kapitel 9?',
    options: [
      'Geringer Grad der Financial Literacy.',
      'Interessenskonflikte zwischen Anleger und Portfoliomanager.',
      'Starke Abhängigkeit von den Fähigkeiten des Portfoliomanagers.',
      'Garantierte Outperformance des aktiven Managements.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Genannt werden u. a. geringe Financial Literacy, Interessenskonflikte und die Abhängigkeit vom Portfoliomanager; das aktive Management hat gerade grds. geringere Erfolgsaussichten.',
  },
  {
    id: 'fintechs-im-asset-management-q05',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'Welche Reihenfolge beschreibt den Robo-Advisory-Prozess korrekt?',
    options: [
      '1) Monitoring/Rebalancing, 2) Onboarding, 3) Strategie-Implementierung.',
      '1) Investor Screening & Onboarding, 2) Investmentstrategie-Implementierung, 3) Monitoring und Rebalancing.',
      '1) Strategie-Implementierung, 2) Monitoring, 3) Onboarding.',
      '1) Onboarding, 2) Monitoring, 3) Strategie-Implementierung.',
    ],
    correctAnswer: 1,
    explanation: 'Der Robo-Advisory-Prozess gliedert sich in 1) Investor Screening & Onboarding, 2) Investmentstrategie-Implementierung und 3) Monitoring und Rebalancing.',
  },
  {
    id: 'fintechs-im-asset-management-q06',
    topicId: 'fintechs-im-asset-management',
    type: 'multiple',
    question: 'Welche Nachteile des Online-Multiple-Choice-Fragebogens beim Onboarding nennt Kapitel 9?',
    options: [
      'Informationsverlust durch das Multiple-Choice-Format.',
      'Kunden interpretieren die Fragen unterschiedlich.',
      'Response Bias, weil vergleichbare Anlegertypen unterstellt werden, obwohl die Antworten subjektiv sind.',
      'Höhere Kosten als beim persönlichen Interview.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Der Fragebogen erzeugt Informationsverlust, unterschiedliche Frageninterpretation und Response Bias; geringere — nicht höhere — Kosten gegenüber dem Interview sind gerade ein Vorteil.',
  },
  {
    id: 'fintechs-im-asset-management-q07',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'Auf welchen Anteil reduziert die mehrstufige ETF-Filterkaskade das Anlageuniversum?',
    options: [
      'Auf rund 30–40 % aller ETFs.',
      'Auf ca. 3–6 % aller ETFs aus der Ausgangsstufe.',
      'Auf genau 50 % aller ETFs.',
      'Auf 0 %, da alle ETFs ausgeschlossen werden.',
    ],
    correctAnswer: 1,
    explanation: 'Die Filterkaskade (Ausschluss von Nischen-/Leveraged-ETFs, kurzer Kurshistorie, ungenügender Liquidität und schlechter Performance) reduziert das Universum auf ca. 3–6 % aller ETFs.',
  },
  {
    id: 'fintechs-im-asset-management-q08',
    topicId: 'fintechs-im-asset-management',
    type: 'single',
    question: 'Was ist das wichtigste Unterscheidungskriterium zwischen einfachen (§ 34f GewO) und aufwendigeren (lizenzierten) Robo-Angeboten?',
    options: [
      'Die Höhe der Mindesteinlage.',
      'Die Ausgestaltung der Portfolioanpassungen (Rebalancing): nur aufwendigere Angebote nehmen eine aktive, automatische taktische Neugewichtung vor.',
      'Die Verwendung von Aktien statt ETFs.',
      'Die Anzahl der Onboarding-Fragen.',
    ],
    correctAnswer: 1,
    explanation: 'Das wichtigste Unterscheidungskriterium ist die Rebalancing-Ausgestaltung: einfache Angebote beschränken sich auf die strategische Allokation mit regelmäßigem Rebalancing, nur lizenzierte Angebote nehmen eine aktive, automatische taktische Neugewichtung vor.',
  },
];

export default questions;
