export const module = {
  id: 'human-resources',
  semesterId: 'semester-4',
  title: 'Human Resources',
  shortTitle: 'HR',
  description:
    'Pruefungsorientierte Lerninhalte zu Human Resource Management, Personalpolitik und Fuehrung.',
  status: 'in-progress',
  examDate: null,
  accent: 'var(--color-module-teal)',
  topics: [
    {
      id: 'einfuehrung',
      title: 'Kapitel 1 · Einführung in das Human Resource Management',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR1 – Einführung',
      estimatedMinutes: 50,
    },
    {
      id: 'unternehmensstrategie-und-personalpolitik',
      title: 'Kapitel 2 · Unternehmensstrategie und Personalpolitik',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR2 – Personalpolitik',
      estimatedMinutes: 60,
    },
    {
      id: 'fuehrung-und-unternehmensethik',
      title: 'Kapitel 3 · Führung, Generationen und Unternehmensethik',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR3 – Personalpolitik 2',
      estimatedMinutes: 55,
    },
    {
      id: 'operative-personalplanung',
      title: 'Kapitel 4 · Operative Personalplanung',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR4 – Operative Personalplanung',
      estimatedMinutes: 55,
    },
    {
      id: 'personalbeschaffung',
      title: 'Kapitel 5 · Personalbeschaffung',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR5 – Personalbeschaffung',
      estimatedMinutes: 55,
    },
    {
      id: 'personalauswahl-und-arbeitszeugnisse',
      title: 'Kapitel 6 · Personalauswahl und Arbeitszeugnisse',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR6 – Personalauswahl & Arbeitszeugnisse',
      estimatedMinutes: 60,
    },
    {
      id: 'personalauswahl-verfahren',
      title: 'Kapitel 7 · Personalauswahl – Verfahren',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR7 – Personalauswahl: Verfahren',
      estimatedMinutes: 60,
    },
    {
      id: 'personaladministration-sozialversicherung-dsgvo',
      title: 'Kapitel 8 · Personaladministration, Sozialversicherung und DSGVO',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR8 – Personaladministration, Sozialversicherung & DSGVO',
      estimatedMinutes: 65,
    },
    {
      id: 'personalcontrolling-onboarding-laufbahnplanung',
      title: 'Kapitel 9 · Personalcontrolling, Onboarding und Laufbahnplanung',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR9 – Personalcontrolling, Onboarding & Laufbahnplanung',
      estimatedMinutes: 65,
    },
    {
      id: 'arbeitsorganisation-und-personalbeurteilung',
      title: 'Kapitel 10 · Arbeitsorganisation und Personalbeurteilung',
      status: 'available',
      hasContent: true,
      source: 'Human Resources · HR10 – Arbeitsorganisation & Personalbeurteilung',
      estimatedMinutes: 65,
    },
  ],
};
