// Quiz-Fragen für das Modul Human Resources (Semester 4).
// Schema analog zu asset-management/questions.js:
// { id, type: 'single' | 'multiple', question, options:[...],
//   correctAnswer:<idx> | correctAnswers:[...], explanation }.
// Alle Inhalte sind ausschließlich aus den Topic-Quellen (HR1–HR10) abgeleitet.

export const questions = [
  // ───────────────────────── Kapitel 1 · Einführung ─────────────────────────
  {
    id: 'einfuehrung-q01',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Wie definiert das Topic Human Resource Management?',
    options: [
      'Als rein juristische Disziplin, die ausschließlich das Arbeitsvertragsrecht regelt.',
      'Als Bereich der Betriebswirtschaft, der sich mit dem Produktionsfaktor Arbeit bzw. dem Personal auseinandersetzt und auf nachhaltige Wertschöpfung zielt.',
      'Als Teilgebiet des Marketings, das ausschließlich die Außenwerbung des Unternehmens steuert.',
      'Als kurzfristige Kostenkontrolle, die nur die Minimierung von Lohnkosten verfolgt.',
    ],
    correctAnswer: 1,
    explanation: 'HRM ist der Bereich der Betriebswirtschaft, der sich mit dem Produktionsfaktor Arbeit befasst; Ziel ist nachhaltiger Erfolg, Werterhaltung und Wertschöpfung auf lange Sicht.',
  },
  {
    id: 'einfuehrung-q02',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche Reihenfolge gibt die Prozesskette der operativen Personalarbeit korrekt wieder?',
    options: [
      'Einsatz → Beschaffung → Führung → Entwicklung → Beurteilung → Freisetzung',
      'Beschaffung → Einsatz → Führung → Beurteilung → Entwicklung → Freisetzung',
      'Beurteilung → Beschaffung → Einsatz → Führung → Freisetzung → Entwicklung',
      'Führung → Beschaffung → Beurteilung → Einsatz → Entwicklung → Freisetzung',
    ],
    correctAnswer: 1,
    explanation: 'Die Prozesskette lautet: Beschaffung → Einsatz → Führung → Beurteilung → Entwicklung → Freisetzung.',
  },
  {
    id: 'einfuehrung-q03',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Worin unterscheiden sich Personalpolitik und Personalmanagement laut Topic?',
    options: [
      'Personalpolitik ist der gesamte Aufgabenbereich, Personalmanagement nur die Leitlinie.',
      'Beide Begriffe sind Synonyme und können beliebig getauscht werden.',
      'Personalpolitik ist der Gestaltungsrahmen bzw. die Leitlinie, Personalmanagement der gesamte Aufgabenbereich für personelle Fragen.',
      'Personalpolitik bezeichnet nur die Personalbeschaffung, Personalmanagement nur die Personalfreisetzung.',
    ],
    correctAnswer: 2,
    explanation: 'Personalpolitik ist der Gestaltungsrahmen/die Leitlinie; Personalmanagement ist der gesamte Aufgabenbereich (Systemgestaltung + Verhaltenssteuerung). Eine häufige Verwechslung.',
  },
  {
    id: 'einfuehrung-q04',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche drei Zielarten verfolgt das HRM laut Topic gleichzeitig?',
    options: [
      'Wirtschaftliche Ziele (z. B. optimaler Einsatz des Faktors Arbeit, Kostenminimierung).',
      'Soziale Ziele (z. B. Arbeitsschutz, Ergonomie, Mitbestimmung).',
      'Individuelle Ziele (z. B. interessante Arbeit, gesichertes Einkommen, Persönlichkeitsentfaltung).',
      'Steuerrechtliche Ziele (z. B. Minimierung der Körperschaftsteuer).',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'HRM verfolgt wirtschaftliche, soziale und individuelle Ziele gleichzeitig; steuerrechtliche Ziele werden nicht als eigene Zielart genannt.',
  },
  {
    id: 'einfuehrung-q05',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche der folgenden Faktoren zählen zu den fünf Einflussfaktoren auf das HRM?',
    options: [
      'Werte',
      'Technologie',
      'Markt',
      'Globalisierung',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Die fünf Einflussfaktoren sind Werte, Technologie, Markt, Organisation und Globalisierung — alle vier genannten gehören dazu.',
  },
  {
    id: 'einfuehrung-q06',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welcher Wandel kennzeichnet den Übergang von der Personalverwaltung zum Personalmanagement?',
    options: [
      'Vom complex man zum homo oeconomicus und von dynamisch zu statisch.',
      'Vom homo oeconomicus zum complex man und vom statischen zum dynamischen Umfeld.',
      'Von der Wettbewerbsorientierung zur Bürokratie.',
      'Von Zufriedenheit als Ziel zur reinen Rechtmäßigkeit.',
    ],
    correctAnswer: 1,
    explanation: 'Der Kern des Wandels ist der Übergang vom homo oeconomicus zum complex man und vom statischen zum dynamischen Umfeld.',
  },
  {
    id: 'einfuehrung-q07',
    topicId: 'einfuehrung',
    type: 'multiple',
    question: 'Welche Zuordnungen zur Gliederung des Arbeitsrechts sind korrekt?',
    options: [
      'Arbeitsvertragsrecht gehört zum individuellen Arbeitsrecht.',
      'Arbeitsschutzrecht gehört zum individuellen Arbeitsrecht.',
      'Tarifvertragsrecht gehört zum kollektiven Arbeitsrecht.',
      'Mitbestimmungsrecht gehört zum individuellen Arbeitsrecht.',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Individuell: Arbeitsvertrags- und Arbeitsschutzrecht; kollektiv: Tarifvertrags- und Mitbestimmungsrecht. Das Mitbestimmungsrecht ist kollektiv, nicht individuell.',
  },
  {
    id: 'einfuehrung-q08',
    topicId: 'einfuehrung',
    type: 'single',
    question: 'Welche ist die schwächste der vier Mitbestimmungsstufen des Betriebsrats?',
    options: [
      'Mitbestimmungsrecht (gemeinsame Entscheidung).',
      'Anhörungs- und Zustimmungsrecht.',
      'Informationsrecht.',
      'Mitwirkungs-/Beratungsrecht.',
    ],
    correctAnswer: 2,
    explanation: 'Die vier Stufen reichen von schwach zu stark: Informationsrecht → Mitwirkungs-/Beratungsrecht → Anhörungs-/Zustimmungsrecht → Mitbestimmungsrecht. Das Informationsrecht ist die schwächste Stufe.',
  },

  // ──────────── Kapitel 2 · Unternehmensstrategie und Personalpolitik ────────────
  {
    id: 'strategie-personalpolitik-q01',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Was unterscheidet "Köpfe" von "Kapazitäten" in der Personalplanung?',
    options: [
      'Köpfe sind Vollzeitäquivalente, Kapazitäten die reine Personenzahl.',
      'Köpfe sind die Anzahl der Mitarbeiter ohne Teilzeitfaktor, Kapazitäten die Full-Time-Equivalents (Vollzeitäquivalente).',
      'Köpfe und Kapazitäten bezeichnen denselben Wert.',
      'Köpfe zählen nur leitende Angestellte, Kapazitäten nur Arbeiter.',
    ],
    correctAnswer: 1,
    explanation: 'Köpfe = Anzahl der Mitarbeiter ohne Berücksichtigung von Teilzeitfaktoren; Kapazitäten = Full-Time-Equivalents (rechnerische Vollzeitäquivalente). Beide nicht gleichsetzen.',
  },
  {
    id: 'strategie-personalpolitik-q02',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Wie sind leitende Angestellte nach § 5 Abs. 3 BetrVG einzuordnen?',
    options: [
      'Sie sind weder arbeitsrechtlich Arbeitnehmer noch im Sinne des BetrVG Arbeitnehmer.',
      'Sie sind arbeitsrechtlich Arbeitnehmer, gelten aber nicht als Arbeitnehmer im Sinne des BetrVG.',
      'Sie sind im Sinne des BetrVG voll wahlberechtigt und wählbar.',
      'Sie sind im Arbeitsrecht keine Arbeitnehmer, im BetrVG aber schon.',
    ],
    correctAnswer: 1,
    explanation: 'Leitende Angestellte sind arbeitsrechtlich Arbeitnehmer, gelten aber gerade nicht als Arbeitnehmer im Sinne des BetrVG (weder wahlberechtigt noch wählbar).',
  },
  {
    id: 'strategie-personalpolitik-q03',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Welcher Leitsatz und Zeithorizont gehören zum strategischen Management?',
    options: [
      '„Die Dinge richtig tun" (Effizienz), bis 1 Jahr.',
      '„Die richtigen Dinge tun" (Effektivität), 2–5 Jahre.',
      '„Der Grund, warum" (normativ), über 5 Jahre.',
      '„Die Dinge schnell tun", über 10 Jahre.',
    ],
    correctAnswer: 1,
    explanation: 'Strategisches Management: Leitsatz „die richtigen Dinge tun" (Effektivität), Zeithorizont 2–5 Jahre. Personalpolitik ist hier angesiedelt.',
  },
  {
    id: 'strategie-personalpolitik-q04',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Wodurch unterscheiden sich Effektivität und Effizienz im Topic?',
    options: [
      'Effektivität heißt „die Dinge richtig tun" (operativ), Effizienz „die richtigen Dinge tun" (strategisch).',
      'Effektivität heißt „die richtigen Dinge tun" (strategisch), Effizienz „die Dinge richtig tun" (operativ).',
      'Beide bezeichnen dasselbe und unterscheiden sich nur im Zeithorizont.',
      'Effektivität ist normativ, Effizienz ist nachhaltig.',
    ],
    correctAnswer: 1,
    explanation: 'Strategisch = „die richtigen Dinge tun" (Effektivität); operativ = „die Dinge richtig tun" (Effizienz). Eine häufige Verwechslung.',
  },
  {
    id: 'strategie-personalpolitik-q05',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Warum ist die Mitarbeiterqualifikation laut Topic ein nachhaltiger Wettbewerbsvorteil?',
    options: [
      'Weil sie kurzfristig und leicht durch Wettbewerber kopiert werden kann.',
      'Weil sie schwerer und langfristiger imitierbar ist als Produkteigenschaften, Produktionsverfahren oder Marketingkonzeption.',
      'Weil sie keine strategische Bedeutung besitzt.',
      'Weil sie ausschließlich durch das 13. Monatsgehalt entsteht.',
    ],
    correctAnswer: 1,
    explanation: 'Mitarbeiterqualifikation ist ein nachhaltiger Wettbewerbsvorteil, weil sie schwerer und langfristiger imitierbar ist als Produkteigenschaften, Produktionsverfahren oder Marketingkonzeption.',
  },
  {
    id: 'strategie-personalpolitik-q06',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'multiple',
    question: 'Welche Pflichten treffen den Arbeitgeber aus dem Arbeitsvertrag?',
    options: [
      'Entgeltzahlung',
      'Fürsorge',
      'Zeugnis- und Urlaubsgewährung',
      'Gehorsams- und Treuepflicht',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Arbeitgeberpflichten: Entgeltzahlung, Fürsorge, Zeugnis, Urlaub. Gehorsam und Treue sind dagegen Arbeitnehmerpflichten.',
  },
  {
    id: 'strategie-personalpolitik-q07',
    topicId: 'unternehmensstrategie-und-personalpolitik',
    type: 'single',
    question: 'Was beschreibt der psychologische Vertrag nach Schein (1970)?',
    options: [
      'Einen schriftlich fixierten, notariell beglaubigten Arbeitsvertrag.',
      'Einen impliziten, ungeschriebenen Vertrag über Geben und Nehmen beider Seiten.',
      'Einen Tarifvertrag zwischen Gewerkschaft und Arbeitgeberverband.',
      'Eine gesetzliche Vorschrift des Betriebsverfassungsgesetzes.',
    ],
    correctAnswer: 1,
    explanation: 'Der psychologische Vertrag nach Schein (1970) ist ein impliziter, ungeschriebener Vertrag über das wechselseitige Geben und Nehmen beider Seiten.',
  },

  // ──────── Kapitel 3 · Führung, Generationen und Unternehmensethik ────────
  {
    id: 'fuehrung-ethik-q01',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Wie grenzt das Topic Ethik und Moral voneinander ab?',
    options: [
      'Ethik und Moral sind Synonyme.',
      'Ethik ist die kritische Reflexion gesellschaftlicher Praxis und Moral; Moral ist das akzeptierte Wert- und Normengefüge eines Kulturkreises.',
      'Moral ist die Wissenschaft, Ethik das tatsächliche Handeln.',
      'Ethik bezeichnet nur das Gesetz, Moral nur das individuelle Gefühl.',
    ],
    correctAnswer: 1,
    explanation: 'Ethik ist die kritische Reflexion/Wissenschaft; Moral ist das akzeptierte Wert- und Normengefüge eines Kulturkreises, Praxis das tatsächliche Handeln.',
  },
  {
    id: 'fuehrung-ethik-q02',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Welche Ethikposition formuliert Kant mit dem kategorischen Imperativ?',
    options: [
      'Eine glücksorientierte Tugendethik.',
      'Eine pflichtorientierte (deontologische) Ethik.',
      'Eine rein utilitaristische, folgenorientierte Ethik.',
      'Eine Diskursethik ohne ethische Maßstäbe.',
    ],
    correctAnswer: 1,
    explanation: 'Kant begründet mit dem kategorischen Imperativ eine pflichtorientierte (deontologische) Ethik; die glücksorientierte Tugendethik stammt von Aristoteles.',
  },
  {
    id: 'fuehrung-ethik-q03',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Wodurch unterscheiden sich utilitaristische und deontologische Ethik?',
    options: [
      'Utilitaristisch = pflichtorientiert; deontologisch = folgenorientiert.',
      'Utilitaristisch = folgenorientiert (Nutzen der Folgen); deontologisch = pflichtorientiert (unabhängig von den Folgen).',
      'Beide bewerten ausschließlich die Folgen einer Handlung.',
      'Beide bewerten ausschließlich die Pflicht unabhängig von Folgen.',
    ],
    correctAnswer: 1,
    explanation: 'Utilitaristisch/konsequentialistisch = folgenorientiert (Nutzen der Folgen); deontologisch = pflichtorientiert (unabhängig von den Folgen). Das Trolley-Problem verdeutlicht beide Logiken.',
  },
  {
    id: 'fuehrung-ethik-q04',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Welche Zuordnung im Ebenenmodell der ethischen Bezugsfelder ist korrekt?',
    options: [
      'Führungsethik = Makro, Unternehmensethik = Meso, Wirtschaftsethik = Mikro.',
      'Wirtschaftsethik = Makro, Unternehmensethik = Meso, Führungsethik = Mikro.',
      'Unternehmensethik = Makro, Wirtschaftsethik = Meso, Führungsethik = Mikro.',
      'Alle drei liegen auf derselben Ebene.',
    ],
    correctAnswer: 1,
    explanation: 'Das Ebenenmodell lautet: Wirtschaftsethik (Makro) → Unternehmensethik (Meso) → Führungsethik (Mikro), eingebettet in die Sozialethik.',
  },
  {
    id: 'fuehrung-ethik-q05',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Welche Aussage zum Verhältnis von Legalität und Moral trifft das Topic?',
    options: [
      'Was legal ist, ist automatisch auch moralisch richtig.',
      'Legalität ist die Mindestanforderung, aber nicht automatisch moralische Richtigkeit; Unternehmensethik wird im Graubereich zwischen Gesetz und Praxis relevant.',
      'Moralische Richtigkeit ist unabhängig vom Gesetz immer geringer als Legalität.',
      'Unternehmensethik ist nur dann relevant, wenn ein Gesetz verletzt wurde.',
    ],
    correctAnswer: 1,
    explanation: 'Legalität ist die Mindestanforderung, aber nicht automatisch moralische Richtigkeit. Unternehmensethik wirkt im Graubereich zwischen Gesetz und Praxis.',
  },
  {
    id: 'fuehrung-ethik-q06',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'multiple',
    question: 'Welche Leitlinien nennt das Topic für generationengerechte Führung?',
    options: [
      'Wertschätzung und offene Feedback-Kultur',
      'Individuelle Entwicklung und digitale Offenheit',
      'Intergenerative Teams und Flexibilisierung',
      'Strikte Gleichbehandlung ohne Berücksichtigung von Wertprägungen',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Generationengerechte Führung setzt auf Wertschätzung, offene Feedback-Kultur, individuelle Entwicklung, digitale Offenheit, intergenerative Teams und Flexibilisierung — nicht auf das Ignorieren von Wertprägungen.',
  },
  {
    id: 'fuehrung-ethik-q07',
    topicId: 'fuehrung-und-unternehmensethik',
    type: 'single',
    question: 'Womit misst die Arbeitgeberqualität laut Topic die Arbeitszufriedenheit?',
    options: [
      'Über einen einzigen Vergütungswert.',
      'Über acht Parameter (u. a. Aufgabenstellung, Führung, Teamklima, Vergütung).',
      'Ausschließlich über die Anzahl der Mitarbeitenden.',
      'Über die Höhe des Weltjahresumsatzes.',
    ],
    correctAnswer: 1,
    explanation: 'Arbeitgeberqualität misst die Arbeitszufriedenheit über acht Parameter (u. a. Aufgabenstellung, Führung, Teamklima, Vergütung) und bildet eine Achse der Employer Matrix.',
  },

  // ────────────── Kapitel 4 · Operative Personalplanung ──────────────
  {
    id: 'operative-planung-q01',
    topicId: 'operative-personalplanung',
    type: 'multiple',
    question: 'Welche vier Kompetenzdimensionen umfasst ein Anforderungsprofil?',
    options: [
      'Fachkompetenz',
      'Persönlichkeitskompetenz',
      'Methodenkompetenz',
      'Sozialkompetenz',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Das Vier-Felder-Kompetenzmodell umfasst Fach-, Persönlichkeits-, Methoden- und Sozialkompetenz.',
  },
  {
    id: 'operative-planung-q02',
    topicId: 'operative-personalplanung',
    type: 'single',
    question: 'Wozu dient ein Anforderungsprofil?',
    options: [
      'Es ersetzt das Arbeitszeugnis.',
      'Es übersetzt abstrakte Anforderungen in messbare Soll-Ausprägungen (z. B. Skala 1–7) und macht Bewerberprofile vergleichbar.',
      'Es legt ausschließlich das Gehalt fest.',
      'Es ist ein gesetzlich vorgeschriebener Bestandteil des Arbeitsvertrags.',
    ],
    correctAnswer: 1,
    explanation: 'Das Anforderungsprofil übersetzt abstrakte Anforderungen in messbare Soll-Ausprägungen (z. B. Skala 1–7) und ermöglicht einen Soll-Ist-Profilvergleich.',
  },
  {
    id: 'operative-planung-q03',
    topicId: 'operative-personalplanung',
    type: 'single',
    question: 'Welche Eigenschaft soll eine Stellenbeschreibung laut Topic haben?',
    options: [
      'Sie ist mitarbeiterbezogen und beschreibt die konkrete Person.',
      'Sie legt Aufgaben funktionsbezogen und mitarbeiterunabhängig fest.',
      'Sie sollte fester Bestandteil des Arbeitsvertrags sein.',
      'Sie ist identisch mit dem Anforderungsprofil.',
    ],
    correctAnswer: 1,
    explanation: 'Die Stellenbeschreibung legt Aufgaben funktionsbezogen und mitarbeiterunabhängig fest; sie sollte nicht fester Vertragsbestandteil sein, um Änderbarkeit zu wahren.',
  },
  {
    id: 'operative-planung-q04',
    topicId: 'operative-personalplanung',
    type: 'multiple',
    question: 'Welche Karrierewege bieten moderne Karrieremodelle laut Topic gleichwertig an?',
    options: [
      'Linienlaufbahn (Führung)',
      'Fachlaufbahn',
      'Projektlaufbahn',
      'Ausschließlich disziplinarische Führungslaufbahn',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Moderne Karrieremodelle bieten neben der Linienlaufbahn gleichwertige Fach- und Projektlaufbahnen — Karriere ist nicht mit disziplinarischer Führung gleichzusetzen.',
  },
  {
    id: 'operative-planung-q05',
    topicId: 'operative-personalplanung',
    type: 'single',
    question: 'Was zeigt die Funktionsmatrix?',
    options: [
      'Nur die Gehaltsspannen einzelner Stellen.',
      'Sie bündelt alle Anforderungsprofile eines Unternehmens und zeigt vertikale (Level A–F) wie horizontale (Funktionsfamilien) Entwicklungswege.',
      'Ausschließlich die Sozialversicherungsbeiträge.',
      'Nur das Organigramm des Vorstands.',
    ],
    correctAnswer: 1,
    explanation: 'Die Funktionsmatrix bündelt alle Anforderungsprofile und zeigt vertikalen Aufstieg über Level A–F sowie horizontalen Wechsel zwischen Funktionsfamilien.',
  },
  {
    id: 'operative-planung-q06',
    topicId: 'operative-personalplanung',
    type: 'single',
    question: 'Was unterscheidet offenes von latentem Beschaffungspotential?',
    options: [
      'Offenes Potential meint Abwerbung, latentes die sofort verfügbaren Bewerber.',
      'Latentes Potential meint u. a. Abwerbung und die Steigerung der Erwerbstätigkeit; offenes Potential die unmittelbar verfügbaren Personen.',
      'Beide Begriffe bezeichnen dasselbe.',
      'Offenes Potential bezieht sich nur auf interne, latentes nur auf externe Mitarbeiter.',
    ],
    correctAnswer: 1,
    explanation: 'Latentes Beschaffungspotential meint Abwerbung und Steigerung der Erwerbstätigkeit; offenes und latentes Potential dürfen nicht verwechselt werden.',
  },

  // ─────────────────── Kapitel 5 · Personalbeschaffung ───────────────────
  {
    id: 'beschaffung-q01',
    topicId: 'personalbeschaffung',
    type: 'single',
    question: 'Welche Grundunterscheidung trifft die Personalbeschaffung?',
    options: [
      'Zwischen befristeter und unbefristeter Beschaffung.',
      'Zwischen internen Wegen (vorhandene Mitarbeiterpotenziale) und externen Wegen (Arbeitsmarkt außerhalb des Unternehmens).',
      'Zwischen tariflicher und außertariflicher Beschaffung.',
      'Zwischen quantitativer und qualitativer Beschaffung.',
    ],
    correctAnswer: 1,
    explanation: 'Personalbeschaffung erfolgt grundsätzlich über interne Wege (vorhandene Mitarbeiterpotenziale) und externe Wege (Arbeitsmarkt außerhalb des Unternehmens).',
  },
  {
    id: 'beschaffung-q02',
    topicId: 'personalbeschaffung',
    type: 'multiple',
    question: 'Welche der folgenden Wege gehören zu den internen Beschaffungswegen?',
    options: [
      'Versetzung',
      'Innerbetriebliche Ausschreibung',
      'Mehrarbeit und Personalentwicklung',
      'Guerilla-Recruiting',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Interne Wege sind Versetzung, Personalentwicklung, innerbetriebliche Ausschreibung und Mehrarbeit; Guerilla-Recruiting ist ein externer Weg.',
  },
  {
    id: 'beschaffung-q03',
    topicId: 'personalbeschaffung',
    type: 'single',
    question: 'Warum ist Personalbeschaffung ein reziproker Prozess?',
    options: [
      'Weil nur das Unternehmen sucht und entscheidet.',
      'Weil Organisation und Individuum gegenseitig bieten und nachfragen; ein Vertrag entsteht nur bei weitgehend komplementären Interessen.',
      'Weil ausschließlich der Bewerber Bedingungen stellt.',
      'Weil der Prozess immer beim Betriebsrat beginnt.',
    ],
    correctAnswer: 1,
    explanation: 'Personalbeschaffung ist ein reziproker Aushandlungsprozess: Organisation und Individuum bieten und fragen gegenseitig nach; ein Vertrag entsteht nur bei weitgehend komplementären Interessen.',
  },
  {
    id: 'beschaffung-q04',
    topicId: 'personalbeschaffung',
    type: 'single',
    question: 'Wie unterscheiden sich Sourcing und Arbeitnehmerüberlassung?',
    options: [
      'Sourcing ist die Bereitstellung über Überlassungsmodelle, Arbeitnehmerüberlassung die aktive Direktansprache.',
      'Sourcing ist die aktive Identifikation und Ansprache von Kandidaten; Arbeitnehmerüberlassung stellt Arbeitskräfte über Überlassungsmodelle bereit.',
      'Beide bezeichnen dasselbe Verfahren.',
      'Sourcing betrifft nur interne, Arbeitnehmerüberlassung nur freiwillige Sozialleistungen.',
    ],
    correctAnswer: 1,
    explanation: 'Sourcing ist die aktive Identifikation und Direktansprache von Kandidaten; Arbeitnehmerüberlassung stellt Arbeitskräfte über Überlassungsmodelle (extern/intern, Inhouse-, Master-Service) bereit.',
  },
  {
    id: 'beschaffung-q05',
    topicId: 'personalbeschaffung',
    type: 'single',
    question: 'Welche Risiken nennt das Topic beim Guerilla-Recruiting?',
    options: [
      'Es ist immer und in jeder Branche uneingeschränkt empfehlenswert.',
      'In konservativen Branchen drohen Seriositäts- und Reputationsrisiken sowie Zielgruppen-Unpassung.',
      'Es ist gesetzlich verboten.',
      'Es eignet sich nur für die interne Beschaffung.',
    ],
    correctAnswer: 1,
    explanation: 'Guerilla-Recruiting ist nicht unkritisch zu empfehlen: In konservativen Branchen drohen Seriositäts- und Reputationsrisiken sowie Zielgruppen-Unpassung.',
  },
  {
    id: 'beschaffung-q06',
    topicId: 'personalbeschaffung',
    type: 'multiple',
    question: 'Anhand welcher Kategorien werden Vor- und Nachteile interner vs. externer Beschaffung verglichen?',
    options: [
      'Allgemeines',
      'Qualifikation',
      'Motivation',
      'Steuerrecht',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Der Vergleich erfolgt entlang der Kategorien Allgemeines, Qualifikation und Motivation; beide Seiten haben in jeder Kategorie gemischte Effekte.',
  },

  // ──────── Kapitel 6 · Personalauswahl und Arbeitszeugnisse ────────
  {
    id: 'auswahl-zeugnis-q01',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'single',
    question: 'Wie ist das Assessment Center laut Topic einzuordnen?',
    options: [
      'Als eigenständiges Einzelinstrument der Personalauswahl.',
      'Als Kombination aus Vorstellungsgespräch, Testverfahren und situativen Verfahren.',
      'Als grafologisches Gutachten.',
      'Als ärztliche Eignungsuntersuchung.',
    ],
    correctAnswer: 1,
    explanation: 'Das Assessment Center ist kein eigenes Einzelinstrument, sondern die Kombination aus Vorstellungsgespräch, Testverfahren und situativen Verfahren.',
  },
  {
    id: 'auswahl-zeugnis-q02',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'single',
    question: 'Welche Note steht hinter der Formulierung „stets zu unserer vollsten Zufriedenheit"?',
    options: [
      '3 · befriedigend',
      '1 · sehr gut',
      '4 · ausreichend',
      '2 · gut',
    ],
    correctAnswer: 1,
    explanation: '„Stets zu unserer vollsten Zufriedenheit" entspricht der Note 1 · sehr gut (stets + vollsten).',
  },
  {
    id: 'auswahl-zeugnis-q03',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'single',
    question: 'Welche Note transportiert „zu unserer vollen Zufriedenheit" (ohne „stets")?',
    options: [
      '1 · sehr gut',
      '2 · gut',
      '3 · befriedigend',
      '5 · mangelhaft',
    ],
    correctAnswer: 2,
    explanation: '„Zu unserer vollen Zufriedenheit" entspricht der Note 3 · befriedigend; fehlt „stets", sinkt die Note. Klassische Verwechslungsfalle mit „stets zu unserer vollsten Zufriedenheit" (sehr gut).',
  },
  {
    id: 'auswahl-zeugnis-q04',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'multiple',
    question: 'Welche Formulierungen sind im Zeugniscode negativ codiert?',
    options: [
      '„Hatte Verständnis für seine Arbeit"',
      '„Gesundes Selbstvertrauen"',
      '„Hat sich bemüht"',
      '„Erzielte selbständig optimale Lösungen"',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Negativ codiert sind „hatte Verständnis für seine Arbeit", „gesundes Selbstvertrauen" und „bemüht". „Erzielte selbständig optimale Lösungen" steht dagegen für eine sehr gute Arbeitsweise.',
  },
  {
    id: 'auswahl-zeugnis-q05',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'multiple',
    question: 'Welche fünf Beurteilungsdimensionen der Leistung unterscheidet das Topic?',
    options: [
      'Leistungsbereitschaft und Arbeitsbefähigung',
      'Arbeitsweise und Arbeitserfolg',
      'Führungsfähigkeit',
      'Sozialversicherungsbeitrag',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die fünf Beurteilungsdimensionen sind Leistungsbereitschaft, Arbeitsbefähigung, Arbeitsweise, Arbeitserfolg und Führungsfähigkeit. Der Sozialversicherungsbeitrag gehört nicht dazu.',
  },
  {
    id: 'auswahl-zeugnis-q06',
    topicId: 'personalauswahl-und-arbeitszeugnisse',
    type: 'single',
    question: 'Welches Element gehört NICHT zur festen Struktur eines Arbeitszeugnisses?',
    options: [
      'Überschrift und Einleitung',
      'Tätigkeitsbeschreibung und Leistungsbeurteilung',
      'Sozialverhalten, Beendigungsgrund und Schlusssatz',
      'Eine Aufstellung der monatlichen Sozialversicherungsbeiträge',
    ],
    correctAnswer: 3,
    explanation: 'Das Arbeitszeugnis enthält Überschrift, Einleitung, Tätigkeitsbeschreibung, Leistungsbeurteilung, Sozialverhalten, Beendigungsgrund, Schlusssatz sowie Datum und Unterschrift — nicht jedoch eine Aufstellung der Sozialversicherungsbeiträge.',
  },

  // ───────────── Kapitel 7 · Personalauswahl – Verfahren ─────────────
  {
    id: 'auswahl-verfahren-q01',
    topicId: 'personalauswahl-verfahren',
    type: 'single',
    question: 'Welche drei Verfahren bilden zusammen das Assessment Center?',
    options: [
      'Bewerbungsanalyse, Fragebogen und Background-Check.',
      'Vorstellungsgespräch, Testverfahren und situative Verfahren.',
      'Grafologisches Gutachten, ärztliche Untersuchung und Background-Check.',
      'Insights-MDI, ProfileXT und grafologisches Gutachten.',
    ],
    correctAnswer: 1,
    explanation: 'Vorstellungsgespräch, Testverfahren und situative Verfahren bilden zusammen das Assessment Center; grafologische Gutachten stehen eigenständig daneben.',
  },
  {
    id: 'auswahl-verfahren-q02',
    topicId: 'personalauswahl-verfahren',
    type: 'multiple',
    question: 'Welche drei Ebenen betrachtet eine ganzheitliche Personalauswahl laut Topic?',
    options: [
      'Kompetenzen',
      'Verhalten',
      'Motive',
      'Sozialversicherungsstatus',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Eine ganzheitliche Auswahl betrachtet drei Ebenen: Kompetenzen, Verhalten und Motive.',
  },
  {
    id: 'auswahl-verfahren-q03',
    topicId: 'personalauswahl-verfahren',
    type: 'single',
    question: 'Welche Farbe ordnet das Insights-MDI-Modell dem analytischen Typ zu?',
    options: [
      'Rot (dominant)',
      'Blau (analytisch)',
      'Grün (stetig)',
      'Gelb (initiativ)',
    ],
    correctAnswer: 1,
    explanation: 'Das Insights-MDI-Modell ordnet vier Typen je einer Farbe zu: Blau (analytisch), Rot (dominant), Grün (stetig), Gelb (initiativ).',
  },
  {
    id: 'auswahl-verfahren-q04',
    topicId: 'personalauswahl-verfahren',
    type: 'single',
    question: 'Was unterscheidet beim Insights-Rad das Selbstbild vom Fremdbild?',
    options: [
      'Selbst- und Fremdbild beschreiben dieselbe Eigenschaft immer gleich.',
      'Dieselbe Eigenschaft kann im Selbstbild positiv und im Fremdbild negativ wahrgenommen werden — jede Stärke kann von außen als Schwäche erscheinen.',
      'Das Selbstbild beschreibt Eigenschaften negativ, das Fremdbild positiv.',
      'Das Selbstbild bezieht sich nur auf Kompetenzen, das Fremdbild nur auf Motive.',
    ],
    correctAnswer: 1,
    explanation: 'Dieselbe Eigenschaft kann im Selbstbild positiv und im Fremdbild negativ wahrgenommen werden; das Selbstbild beschreibt Eigenschaften positiv, das Fremdbild dieselben negativ.',
  },
  {
    id: 'auswahl-verfahren-q05',
    topicId: 'personalauswahl-verfahren',
    type: 'single',
    question: 'Was vergleicht die Stilanalyse über die Dimensionen D/I/S/G?',
    options: [
      'Brutto- und Nettogehalt.',
      'Den adaptierten (situativ angepassten) Stil und den Basis-Stil (Grundprägung).',
      'Interne und externe Beschaffungswege.',
      'Soll- und Ist-Arbeitszeit.',
    ],
    correctAnswer: 1,
    explanation: 'Die Stilanalyse stellt den adaptierten (situativ angepassten) und den Basis-Stil (Grundprägung) über die vier Dimensionen D/I/S/G gegenüber.',
  },
  {
    id: 'auswahl-verfahren-q06',
    topicId: 'personalauswahl-verfahren',
    type: 'single',
    question: 'Wie funktioniert das Anforderungsband-Prinzip bei ProfileXT?',
    options: [
      'Das individuelle Ergebnis ist das dunkle Band, die Stellenanforderung die hervorgehobene Box.',
      'Das dunkle Band ist die positionsspezifische Stellenanforderung, die hervorgehobene Box das individuelle Ergebnis; verglichen werden 1–10-Skalenwerte.',
      'Beide Werte sind identisch und nicht zu vergleichen.',
      'Das Anforderungsband misst ausschließlich das Gehalt.',
    ],
    correctAnswer: 1,
    explanation: 'ProfileXT vergleicht individuelle 1–10-Skalenwerte mit dem positionsspezifischen Anforderungsband: Das dunkle Band ist die Stellenanforderung, die hervorgehobene Box das individuelle Ergebnis.',
  },

  // ──── Kapitel 8 · Personaladministration, Sozialversicherung, DSGVO ────
  {
    id: 'admin-sozial-dsgvo-q01',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'multiple',
    question: 'Welche der folgenden Zweige gehören zu den fünf Zweigen der gesetzlichen Sozialversicherung?',
    options: [
      'Arbeitslosenversicherung und Krankenversicherung',
      'Unfallversicherung',
      'Pflege- und Rentenversicherung',
      'Hausratversicherung',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die fünf Zweige sind Arbeitslosen-, Kranken-, Unfall-, Pflege- und Rentenversicherung. Die Hausratversicherung gehört nicht dazu.',
  },
  {
    id: 'admin-sozial-dsgvo-q02',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Welchen Anteil am Bruttolohn machen die Personalzusatzkosten laut Topic etwa aus?',
    options: [
      'ca. 10 %',
      'ca. 25 %',
      'ca. 40 %',
      'ca. 60 %',
    ],
    correctAnswer: 2,
    explanation: 'Die Personalzusatzkosten (gesetzlich, tariflich, freiwillig) betragen ca. 40 % des Bruttolohns.',
  },
  {
    id: 'admin-sozial-dsgvo-q03',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Seit wann gilt die DSGVO als unmittelbar anwendbares EU-Recht?',
    options: [
      'seit 25.05.2016',
      'seit 25.05.2018',
      'seit 01.01.2020',
      'seit 25.05.2020',
    ],
    correctAnswer: 1,
    explanation: 'Die DSGVO gilt seit dem 25.05.2018 als unmittelbar anwendbares EU-Recht.',
  },
  {
    id: 'admin-sozial-dsgvo-q04',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Welcher Bußgeldrahmen gilt nach Art. 83 Abs. 5 DSGVO für größere Verstöße (z. B. gegen die Grundsätze des Art. 5)?',
    options: [
      'bis 10 Mio. € oder 2 % des Weltjahresumsatzes',
      'bis 20 Mio. € oder 4 % des Weltjahresumsatzes',
      'bis 5 Mio. € oder 1 % des Weltjahresumsatzes',
      'bis 50 Mio. € oder 10 % des Weltjahresumsatzes',
    ],
    correctAnswer: 1,
    explanation: 'Größere Verstöße (Art. 83 Abs. 5) werden mit bis zu 20 Mio. € oder 4 % des Weltjahresumsatzes geahndet; kleinere Verstöße (Art. 83 Abs. 4) mit bis zu 10 Mio. € oder 2 %.',
  },
  {
    id: 'admin-sozial-dsgvo-q05',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Welche Aussage zu den Anforderungen der DSGVO an Schutzmaßnahmen ist korrekt?',
    options: [
      'Die DSGVO schreibt konkrete, abschließend aufgezählte Schutzmaßnahmen vor.',
      'Die DSGVO schreibt keine konkreten Schutzmaßnahmen vor; Unternehmen wählen risikoangemessen und müssen den Stand der Technik einhalten.',
      'Die DSGVO verlangt für jede Verarbeitung die Einwilligung des Datenschutzbeauftragten.',
      'Die DSGVO verbietet jede Verarbeitung personenbezogener Daten.',
    ],
    correctAnswer: 1,
    explanation: 'Die DSGVO schreibt keine konkreten Schutzmaßnahmen vor; Unternehmen wählen risikoangemessen und müssen den aktuellen Stand der Technik einhalten.',
  },
  {
    id: 'admin-sozial-dsgvo-q06',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Welche Rolle hat der/die Datenschutzbeauftragte laut Topic?',
    options: [
      'Er/sie trifft selbst alle Datenschutzentscheidungen des Unternehmens.',
      'Er/sie berät und schult, trifft aber selbst keine Entscheidungen, genießt jedoch besonderen Abberufungs- und Kündigungsschutz.',
      'Er/sie ist ausschließlich für die Lohnabrechnung zuständig.',
      'Er/sie ist nur ab 20 Personen und sonst nie zu benennen.',
    ],
    correctAnswer: 1,
    explanation: 'Der/die Datenschutzbeauftragte berät und schult, entscheidet aber nicht selbst, und genießt besonderen Abberufungs- und Kündigungsschutz. Er/sie ist auch unabhängig von der Personenzahl zu benennen, wenn DSFA-pflichtige oder sensible Verarbeitungen vorliegen.',
  },
  {
    id: 'admin-sozial-dsgvo-q07',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Wie ordnet das Topic die betriebliche Altersvorsorge ein?',
    options: [
      'Als Geldleistung wie das 13. Monatsgehalt.',
      'Als Vorsorgeleistung, die gegen Alter, Invalidität, Tod und Unfall absichert.',
      'Als gesetzliche Pflichtleistung des Staates.',
      'Als Sachleistung.',
    ],
    correctAnswer: 1,
    explanation: 'Die betriebliche Altersvorsorge ist eine Vorsorgeleistung (Absicherung gegen Alter, Invalidität, Tod, Unfall); das 13. Monatsgehalt ist dagegen eine Geldleistung.',
  },
  {
    id: 'admin-sozial-dsgvo-q08',
    topicId: 'personaladministration-sozialversicherung-dsgvo',
    type: 'single',
    question: 'Warum ist Personalcontrolling laut Topic mehr als reine Kontrolle?',
    options: [
      'Weil es ausschließlich vergangenheitsbezogene Daten erhebt.',
      'Weil es ein zukunftsgerichteter Regelkreis ist (Planung → Ist-Messung → Soll-Ist-Vergleich → Maßnahmen).',
      'Weil es nur die Lohnzahlung überwacht.',
      'Weil es identisch mit der Entgeltabrechnung ist.',
    ],
    correctAnswer: 1,
    explanation: 'Personalcontrolling ist ein zukunftsgerichteter Regelkreis (Planung → Ist-Messung → Soll-Ist-Vergleich → Maßnahmen) und nicht nur vergangenheitsbezogene Kontrolle.',
  },

  // ──── Kapitel 9 · Personalcontrolling, Onboarding, Laufbahnplanung ────
  {
    id: 'controlling-onboarding-q01',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'single',
    question: 'Wodurch werden Kennzahlen der Personalstatistik erst aussagekräftig?',
    options: [
      'Durch ihre bloße Erhebung als absolute Zahl.',
      'Durch Vergleich mit Bezugswerten (Vorjahr, Plan/Soll, Branchendurchschnitt).',
      'Durch Umrechnung in Fremdwährung.',
      'Durch Veröffentlichung im Arbeitszeugnis.',
    ],
    correctAnswer: 1,
    explanation: 'Kennzahlen werden erst durch den Vergleich mit Bezugswerten (Vorjahr, Plan/Soll, Branchendurchschnitt) aussagekräftig.',
  },
  {
    id: 'controlling-onboarding-q02',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'single',
    question: 'Wie ist die Quote der effektiven Arbeitszeit definiert?',
    options: [
      'Soll-Arbeitszeit / Ist-Arbeitszeit',
      'Ist-Arbeitszeit / Soll-Arbeitszeit',
      'Ist-Arbeitszeit / vereinbarte Arbeitszeit',
      'Mehrarbeit / Ausfallzeiten',
    ],
    correctAnswer: 1,
    explanation: 'Die Quote der effektiven Arbeitszeit setzt Ist über Soll (Ist-Arbeitszeit / Soll-Arbeitszeit) — nie umgekehrt.',
  },
  {
    id: 'controlling-onboarding-q03',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'single',
    question: 'Wie leitet sich die Ist-Arbeitszeit aus der Soll-Arbeitszeit ab?',
    options: [
      'Ist = Soll + Feiertage − Mehrarbeit',
      'Ist = Soll − Ausfallzeiten + Mehrarbeit',
      'Ist = Soll + Ausfallzeiten − Mehrarbeit',
      'Ist = vereinbart − Freistellungen',
    ],
    correctAnswer: 1,
    explanation: 'Soll = vereinbart − Feiertage − Freistellungen; Ist = Soll − Ausfallzeiten + Mehrarbeit.',
  },
  {
    id: 'controlling-onboarding-q04',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'multiple',
    question: 'Welche Posten zählen laut Topic zu den Abgängen, die in die gesamte Fluktuation eingehen?',
    options: [
      'Natürliche Fluktuation (Pensionierung, Tod)',
      'Kündigungen und Trennungen',
      'Neueinstellungen',
      'Mehrarbeit',
    ],
    correctAnswers: [0, 1],
    explanation: 'Abgänge = natürliche Fluktuation (Pensionierung, Tod) plus Kündigungen/Trennungen. Neueinstellungen sind Zugänge, Mehrarbeit ist keine Fluktuationsgröße.',
  },
  {
    id: 'controlling-onboarding-q05',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'single',
    question: 'Wie verteilt sich das Lernen im 70/20/10-Modell?',
    options: [
      '70 % formale Bildung, 20 % soziales Lernen, 10 % Erfahrung',
      '70 % Erfahrung, 20 % soziales Lernen, 10 % formale Bildung',
      '70 % soziales Lernen, 20 % Erfahrung, 10 % formale Bildung',
      '70 % E-Learning, 20 % Seminare, 10 % Mentoring',
    ],
    correctAnswer: 1,
    explanation: 'Das 70/20/10-Modell verteilt das Lernen auf 70 % Erfahrung, 20 % soziales Lernen und 10 % formale Bildung; der 70-%-Anteil ist gezielt zu steuern.',
  },
  {
    id: 'controlling-onboarding-q06',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'multiple',
    question: 'Welche drei gleichwertigen Pfade bietet die Laufbahnplanung laut Topic?',
    options: [
      'Fachlicher Pfad',
      'Führungspfad',
      'Projekt-/lateraler Pfad',
      'Sozialversicherungspfad',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die Laufbahnplanung bietet drei gleichwertige Pfade: fachlich, Führung und Projekt/lateral.',
  },
  {
    id: 'controlling-onboarding-q07',
    topicId: 'personalcontrolling-onboarding-laufbahnplanung',
    type: 'single',
    question: 'Was beschreibt der Personaleinsatz im engeren Sinne?',
    options: [
      'Die Anpassung des Qualifikationsprofils der Person durch Auswahl und Entwicklung.',
      'Die Arbeitsgestaltung und -organisation der Stelle.',
      'Die Berechnung der Personalzusatzkosten.',
      'Die Ableitung der Soll-Arbeitszeit.',
    ],
    correctAnswer: 1,
    explanation: 'Personaleinsatz i. e. S. ist die Arbeitsgestaltung/-organisation der Stelle; die Adaption des Qualifikationsprofils erfolgt dagegen über Personalauswahl/-entwicklung. Beide sind Pole der wechselseitigen Adaption.',
  },

  // ──── Kapitel 10 · Arbeitsorganisation und Personalbeurteilung ────
  {
    id: 'arbeitsorg-beurteilung-q01',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'multiple',
    question: 'Welche der folgenden zählen zu den fünf klassischen Formen der Arbeitsorganisation?',
    options: [
      'Job Rotation und Job Enlargement',
      'Job Enrichment',
      'Teilautonome Arbeitsgruppen und Qualitätszirkel',
      'Desk-Sharing',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Die fünf klassischen Formen sind Job Rotation, Job Enlargement, Job Enrichment, teilautonome Arbeitsgruppen und Qualitätszirkel. Desk-Sharing gehört zur Arbeitsort-Flexibilisierung.',
  },
  {
    id: 'arbeitsorg-beurteilung-q02',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'single',
    question: 'Wie unterscheiden sich Job Enlargement und Job Enrichment?',
    options: [
      'Job Enlargement erweitert die Aufgabe vertikal um Verantwortung, Job Enrichment horizontal um gleichartige Tätigkeiten.',
      'Job Enlargement erweitert horizontal um gleichartige Tätigkeiten (Arbeitsbreite), Job Enrichment vertikal um Planungs-, Entscheidungs- und Kontrollanteile (Arbeitstiefe).',
      'Beide erweitern ausschließlich die Arbeitszeit.',
      'Beide bezeichnen dasselbe.',
    ],
    correctAnswer: 1,
    explanation: 'Job Enlargement erweitert horizontal um gleichartige Tätigkeiten (Arbeitsbreite); Job Enrichment vertikal um Planungs-, Entscheidungs- und Kontrollanteile (Arbeitstiefe). Häufige Verwechslung.',
  },
  {
    id: 'arbeitsorg-beurteilung-q03',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'multiple',
    question: 'Welche Grundtypen der Arbeitszeitflexibilisierung nennt das Topic?',
    options: [
      'Chronometrisch (Dauer der Arbeitszeit)',
      'Chronologisch (Lage der Arbeitszeit)',
      'Mischformen',
      'Geografisch (Standort des Unternehmens)',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Flexibilisierung setzt an der Dauer (chronometrisch) und an der Lage (chronologisch) an, ergänzt um Mischformen.',
  },
  {
    id: 'arbeitsorg-beurteilung-q04',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'single',
    question: 'Welche Kernregel zur werktäglichen Arbeitszeit nennt das Topic (ArbZG)?',
    options: [
      '8 Stunden werktäglich, nicht verlängerbar.',
      '8 Stunden werktäglich, verlängerbar auf 10 Stunden, wenn im Schnitt über 6 Kalendermonate oder 24 Wochen 8 Stunden nicht überschritten werden.',
      '10 Stunden werktäglich, verlängerbar auf 12 Stunden über 12 Monate.',
      '6 Stunden werktäglich ohne Ausgleichsmöglichkeit.',
    ],
    correctAnswer: 1,
    explanation: 'Werktägliche Arbeitszeit = 8 Stunden; verlängerbar auf 10 Stunden, wenn im Schnitt über 6 Kalendermonate oder 24 Wochen 8 Stunden täglich nicht überschritten werden.',
  },
  {
    id: 'arbeitsorg-beurteilung-q05',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'single',
    question: 'Was kennzeichnet die Kernzeit bei einem Gleitzeitmodell?',
    options: [
      'Der Arbeitnehmer darf zu dieser Zeit fernbleiben.',
      'In der Kernzeit besteht Anwesenheitspflicht, während Beginn und Ende der Arbeitszeit innerhalb eines Rahmens frei wählbar sind.',
      'Die Kernzeit ist die maximale Wochenarbeitszeit.',
      'Die Kernzeit ersetzt das Arbeitszeitkonto.',
    ],
    correctAnswer: 1,
    explanation: 'Bei Gleitzeit wählt der Arbeitnehmer Beginn und Ende der Arbeitszeit in einem Rahmen selbst; in der Kernzeit besteht Anwesenheitspflicht. Abweichungen werden auf einem Arbeitszeitkonto saldiert.',
  },
  {
    id: 'arbeitsorg-beurteilung-q06',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'single',
    question: 'Wie ist das 360-Grad-Feedback laut Topic einzuordnen?',
    options: [
      'Als Beurteilungs- und Vergütungsinstrument, das direkt mit Beförderungen verknüpft wird.',
      'Als freiwilliges Entwicklungsinstrument, das Selbst- und Fremdbild aus mehreren Perspektiven vergleicht und blinde Flecken sichtbar macht.',
      'Als rein technisches Verfahren der Entgeltabrechnung.',
      'Als gesetzlich vorgeschriebene jährliche Pflichtbeurteilung.',
    ],
    correctAnswer: 1,
    explanation: 'Das 360-Grad-Feedback ist die umfassendste Beurteilungsform und ein freiwilliges Entwicklungs-, kein Beurteilungsinstrument; es vergleicht Selbst- und Fremdbild aus mehreren Perspektiven und macht blinde Flecken sichtbar. Es darf nicht mit Gehalts- oder Beförderungsentscheidungen verknüpft werden.',
  },
  {
    id: 'arbeitsorg-beurteilung-q07',
    topicId: 'arbeitsorganisation-und-personalbeurteilung',
    type: 'single',
    question: 'Welche Beurteilungsform gilt im Topic als die umfassendste und aufwendigste?',
    options: [
      'Die einfache Mitarbeiterbeurteilung durch eine Person.',
      'Das 360-Grad-Feedback (Vorgesetzte, Kollegen, Mitarbeiter und Kunden).',
      'Die Selbsteinschätzung allein.',
      'Die ärztliche Eignungsuntersuchung.',
    ],
    correctAnswer: 1,
    explanation: 'Das 360-Grad-Feedback ist die umfassendste und aufwendigste Form, da es Vorgesetzte, Kollegen, Mitarbeiter und Kunden einbezieht.',
  },
];

export default questions;
